### ISSUE TITLE
Save icon?

### ISSUE THREAD

**Issue by Chaphasilor** [tabler/tabler-icons#10]
I couldn't find an icon for a save button, you know, that floppy disk icon.

I believe this is rather essential and it would be great if you could add it :D

**Comment by codecalm** [comment]
will be tommorow :)

**Comment by codecalm** [comment]
![device-floppy](https://user-images.githubusercontent.com/1282324/77483371-4b579680-6e28-11ea-8d01-18bfdf337ca0.png)

**Comment by codecalm** [comment]
done
