### ISSUE TITLE
Reusing and extending the icon components

### ISSUE THREAD

**Issue by matthias-jaeger-timetac** [tabler/tabler-icons#101]
Dear Paweł Kuna, 
Sorry for raising this issue, I couldn't find a contact mail from you. I work for a software company in the UX team. We are considering of using your awesome icon set in production of our new react app. The following question raised. We will be extending the set with a few more custom components in the same style. Would it be in your interest that we commit the changes here, licensed MIT as well of course. Then our dev team could pull the components fresh from here.  Please let me know if that would be OK for you? Regards, Matthias (matthias.jaeger@timetac.com)

**Comment by codecalm** [comment]
Hi @matthias-jaeger-timetac!
Thank you for your kind words! If only the icons will fit stylistically to the rest, there is no problem to include them in the project :)

**Comment by matthias-jaeger-timetac** [comment]
Hello @codecalm thank you for the fast reply. I'm sure I will do all that's needed to incorporate the friendly overall style in the new icons as well. Here is a sample of a variant of `mug.svg` for you. I have added three lines resembling a steaming, hot coffee inside of the mug. :D Do you have any document with fixed guidelines regarding corner radii, similarity of curves and offsets from the edge I should follow strictly? Regards from Austria, :-) Matthias 

![mug-steaming](https://user-images.githubusercontent.com/76048310/102309701-a490c880-3f69-11eb-8115-7d894a2a4f9e.png)

**Comment by sergej-tschak** [comment]
Hi, I would be interested which requirements do you have for contribution to your repository except for style consistency?

**Comment by FreexD** [comment]
@sergej-tschak @matthias-jaeger-timetac I think tabler icons should setup a contribution/style guide for contributors. @codecalm we should probably work on that in the nearest future
