### ISSUE TITLE
Icon Naming Conventions

### ISSUE THREAD

**Issue by drakbar** [tabler/tabler-icons#1013]
Hi,

Tabler Icons is a cool collection.

I just finished writing a c++ binding to all the symbols in `tabler-icons.ttf`. Now I am able to display the  icons inside of programs that load up the font file  :+1: . While writing the code generator I ran into some issues with the names of the  icons as defined in [tags.json](https://github.com/tabler/tabler-icons/blob/master/tags.json). Specifically the icons (very few) that begin with numbers. Which if you are generating a binding to a language that prohibits that type of naming convention, and you try using that metadata file to generate variable names for each icon: you get hosed by the names that begin with numbers. I am not sure if this project is stuck with this oversight (i.e. changing those names would be considered breaking), but  if it is at all possible to change them I would advocate for doing so. If not I would recommend to not increase the small list of names that do.
 
 The names that I am referring to are:
 ```
 12-hours
123
24-hours
2fa
360-view
360
3d-cube-sphere-off
3d-cube-sphere
3d-rotate
```

Otherwise I love the collection.
Here is `tabler-icons` inside a c++ desktop application.
![image](https://github.com/tabler/tabler-icons/assets/20728117/9069ec9b-9c27-4b31-8243-0042afb3aaec)

**Comment by codecalm** [comment]
what do you think about it:

```
hours-12
number-123
hours-24
auth-2fa
view-360
view-360-arrow
cube-3d--sphere-off
cube-3d-sphere
rotate-3d
```

**Comment by drakbar** [comment]
@codecalm 

That will work perfectly!!

**Comment by BG-Software-BG** [comment]
Icon `360-view` will be renamed to `view-360-number` because icon `view-360` already exists.
