### ISSUE TITLE
Using class names returns a filled icon

### ISSUE THREAD

**Issue by aubryll** [tabler/tabler-icons#102]
Hi, sorry for this issue, this was my last option, I created a [question ](https://stackoverflow.com/questions/65230614/some-tabler-font-icons-appearing-filled)on stackoverflow but it did not yield anything.

We are trying to use your awesome lib in our React project, we noticed it can be done either by importing the element or via class name. 

We chose the class name approach but shortly hit a snag; icons appear filled, an example is the discount icon. We opened the `tabler-icons.html` that comes with your NPM package and noticed it also showed filled icons, how can we remove the fill?

**Comment by FreexD** [comment]
@aubryll I'll try and chech that and get back to you. I'm myself using tabler-icons in a react project and it appears to bo working fine. Can you maybe try to create a codepen with this issue reproduction for the time being? It would be helpful if I don't manage to reproduce the issue.

**Comment by aubryll** [comment]
Hi @FreexD  please find the codepen [here](https://codepen.io/aubryll/pen/LYRjpRy).

**Comment by provinzkraut** [comment]
I'm facing the same issue. It seems to be related to #13

**Comment by FreexD** [comment]
@aubryll thanks for the repro. @provinzkraut you're right, that's probably it. We'll be introducing new iconfont build process soon where we plan to fix the issue. For now as a workaround I'd suggest using other way of embedding tabler-icons line svgs, sprite, pngs or react.

**Comment by aubryll** [comment]
@FreexD  Thank you. Kindly update us when you fix it.

**Comment by aubryll** [comment]
I managed to get the font fixed with [@provinzkraut  suggestion](https://github.com/tabler/tabler-icons/issues/102#issuecomment-749010091) you can find a fixed font [here](https://drive.google.com/file/d/1fBn9S0xcX-7Xj3PcIGvdeOHKUqBxH1dV/view?usp=sharing), it might help in the interim while we wait for the fix.

**Comment by codecalm** [comment]
@aubryll can you check now v1.39.1? :)
