### ISSUE TITLE
[Icon request] Thought bubble

### ISSUE THREAD

**Issue by patrickmccallum** [tabler/tabler-icons#1026]
Just a request for a thought bubble, could be tagged under dream, daydream, think, etc.

Along the lines of but more tabler :) 

![image](https://github.com/tabler/tabler-icons/assets/11825795/d23021d7-f5e6-4d38-8534-ee815148a8ef)

**Comment by BG-Software-BG** [comment]
[bubble icon](https://tabler.io/icons/icon/bubble) was added in v3.2

... together with some variants - see more at https://tabler.io/icons/changelog
