### ISSUE TITLE
icon-squares-filled is missing

### ISSUE THREAD

**Issue by pc-pallon** [tabler/tabler-icons#1031]
`icon-squares-filled` is missing from the beta and released version 3.0.0. It has been there in previous versions and also [3.0.0-alpha](https://github.com/tabler/tabler-icons/blob/v3.0.0-alpha.1/icons/squares-filled.svg). What is the reason this icon is left out?

**Comment by BG-Software-BG** [comment]
@pc-pallon do you mean icon-square-filled? It still there https://tabler.io/icons/icon/square (just use switch to get filled version).

**Comment by pc-pallon** [comment]
I meant icon-square**s**-filled, plural squares. This is how it's supposed to look like.

<img width="114" alt="Screenshot 2024-03-11 at 17 06 53" src="https://github.com/tabler/tabler-icons/assets/143699616/ed8430cb-ffa0-4e09-9322-4003e40df5b5">

**Comment by codecalm** [comment]
fixed in 3.0.1 🙂

**Comment by pc-pallon** [comment]
Thank you for quick fix! But the new icon looks different from the previous one.

Old: 
<img width="114" alt="Screenshot 2024-03-11 at 17 06 53" src="https://github.com/tabler/tabler-icons/assets/143699616/a7b53acf-e25a-418e-8015-527dbe528bcb">

New: 
![Screenshot 2024-03-13 at 09 58 18](https://github.com/tabler/tabler-icons/assets/143699616/823a4dec-71b1-41be-93c0-3230dbebd30d)

**Comment by BG-Software-BG** [comment]
With v3 filled is a separate style and the old version of `icon-squares-filled` doesn't match other "filled" icons so we decided to change it.

If you really need the old version you can add a request to add it with other name. We'll try to do this in one of the next versions.

**Comment by pc-pallon** [comment]
Thank you for the explanation. I'll make a request if our design team thinks we need something like the old version.

**Comment by BG-Software-BG** [comment]
pc-pallon previous icon came back in v3.1 as [squares-selected](https://tabler.io/icons/icon/squares-selected)
