### ISSUE TITLE
Bug: Site styling is broken with latest release

### ISSUE THREAD

**Issue by ickynavigator** [tabler/tabler-icons#1041]
It appears that the dark mode styles are not correctly applied to the documentation page
page - https://tabler.io/docs/getting-started

<img width="1710" alt="Screenshot 2024-03-11 at 21 51 38" src="https://github.com/tabler/tabler-icons/assets/46367335/765905b9-948e-4452-842f-cdf2aca0ed01">

**Comment by codecalm** [comment]
fixed 🙂

**Comment by ickynavigator** [comment]
thanks!!!
