### ISSUE TITLE
`tabler-sprite.svg`  has disappeared in v3

### ISSUE THREAD

**Issue by lovasoa** [tabler/tabler-icons#1044]
Hello !
  In SQLPage, I depend on the `tabler-sprite.svg` : https://github.com/lovasoa/SQLpage/blob/main/sqlpage/tabler-icons.svg?short_path=a1ce7ab
  Was it removed on purpose from 3.0 ? Could it be added back ?

**Comment by codecalm** [comment]
`tabler-sprite.svg` has been moved to `@tabler/icons-sprite` package

**Comment by lovasoa** [comment]
Thanks !

**Comment by MGeurts** [comment]
I can not find tabler-sprite.svg or tabler-sprite-nostroke.svg.
Can someone post the correct URL to the file?

Thanks.

**Comment by lovasoa** [comment]
https://cdn.jsdelivr.net/npm/@tabler/icons-sprite@3.0.1/dist/tabler-sprite.svg
