### ISSUE TITLE
[Icon request] `picnic-table`

### ISSUE THREAD

**Issue by mauriciabad** [tabler/tabler-icons#1055]
Hi, can you add a picnic table icon, I already designed one by myself that fits Tabler Icons that you can use as reference. 

<img width="154" alt="Screenshot 2024-03-13 at 11 38 28 PM" src="https://github.com/tabler/tabler-icons/assets/12821361/9a7f5d68-09b5-469a-81cd-00b11d1df3aa">

The path is: `M16 7L18 16M8 7L6 16M5 7H19M21 12H3`

```svg
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M16 7L18 16M8 7L6 16M5 7H19M21 12H3" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

This may be useful for this other issue: https://github.com/tabler/tabler-icons/issues/900

**Comment by BG-Software-BG** [comment]
Can you make a PR with this icon @mauriciabad ?

**Comment by mauriciabad** [comment]
Done! https://github.com/tabler/tabler-icons/pull/1066

Let me know if I did it right, I may suggest more icons. 😄

**Comment by mauriciabad** [comment]
The icon has been added
