### ISSUE TITLE
Some icons with arrows are wrong copied to Figma or Sketch

### ISSUE THREAD

**Issue by xjure** [tabler/tabler-icons#106]
I noticed that a few arrows have bugs when you copy them to Figma or Sketch. I think the first and the last points are connected.

![Icons with errors](https://user-images.githubusercontent.com/9645731/105342839-26b38300-5be1-11eb-9a4a-4fd6729b6c89.png)

**Comment by codecalm** [comment]
@xjure thank you for issue. Can you try newest version? I just checked icons in Sketch and everything is okay

![Screenshot 2021-01-21 at 12 29 14](https://user-images.githubusercontent.com/1282324/105345229-4b5d2a00-5be4-11eb-82d0-7197b7e912b6.png)

**Comment by xjure** [comment]
I forgot to mention that I copied them from tablericons.com, not directly from this repo.
I just copied it from the web and the bug is still present.

See the video below
https://user-images.githubusercontent.com/9645731/105350938-25d41e80-5bec-11eb-8f7f-9129736f6bdb.mp4

**Comment by codecalm** [comment]
sorry, but this site is not connected with our project. Try https://tabler-icons.io - there is official site with search and newest version of icons.

**Comment by xjure** [comment]
Oh, great! I didn't know about this domain. Thank you.
