### ISSUE TITLE
Copy svg icon with preset stroke width

### ISSUE THREAD

**Issue by xjure** [tabler/tabler-icons#107]
Can you please make that if the user selects stroke width next to the search and copy an SVG icon that stroke width is applied to copied icon?
Currently 'copy SVG' has 2px stroke width by default.

The only way to do that is to open icon details, change stroke width again, and then copy SVG.

Thank you!

**Comment by codecalm** [comment]
thank you for issue, I'll check it! :)

**Comment by codecalm** [comment]
@xjure can you try now? :)

**Comment by xjure** [comment]
On the first load of the page, it wasn't working, but I refreshed the page, and now it's working.
I like how you save stroke width in the local cache.
Thank you!
