### ISSUE TITLE
Website outlined/filled hiding icons

### ISSUE THREAD

**Issue by patrickmccallum** [tabler/tabler-icons#1074]
Hi there, not sure if this is the correct repo, but the sites new update for styles allowing you to select either filled or outlined is hiding icons when users search for them. 

E.g. the sitemap icon has an outline variant but no filled variant, and many exist the other way around which makes it seem as though tabler doesnt have an appropriate icon when searching for them unless the user knows to switch to the different variant.

Would it possible to get a "Both" or "All" filter which is selected by default?

**Comment by BG-Software-BG** [comment]
Each icon has an outline style and it's selected by default.

For now, we don't plan to add "All" option, but maybe we could add some note that not all icons have filled version.

Thanks for your suggestion.
