### ISSUE TITLE
Text editor icons.

### ISSUE THREAD

**Issue by alex-oleshkevich** [tabler/tabler-icons#11]
Hi Pawel,
first thanks for your work, it is just amazing!

My 50c: 
It might be a good idea to have rich text editor icons in this pack.
Some icons may be:

* bold
* italic 
* underline
* link/unlink
* strikethrough
* embed image
* embed video
* embed object
* iframe
* ordered list
* unordered list
* quote
* separator (horizontal line)
* align left/middle/right/justify
* insert table/row/column
* go fullscreen
* text color
* background color
* undo/redo

**Comment by codecalm** [comment]
First part of icons :) 

<img width="1033" alt="Screenshot 2020-03-25 at 22 43 30" src="https://user-images.githubusercontent.com/1282324/77588407-16137d00-6eea-11ea-844a-878f55f5a22d.png">

**Comment by codecalm** [comment]
and the next part

<img width="1329" alt="Screenshot 2020-03-26 at 00 02 00" src="https://user-images.githubusercontent.com/1282324/77593791-1d8c5380-6ef5-11ea-98d0-e4799d590b77.png">

**Comment by codecalm** [comment]
it's live in version 1.3 :)
