### ISSUE TITLE
Sunrise and sunset icons are wrongly named

### ISSUE THREAD

**Issue by SimonPadbury** [tabler/tabler-icons#111]
Can you change to the correct names for these two icons:

1. Your `sunset` icon has an up arrow. Therefore, this should be _sunrise_ (dawn).
2. Your `sunshine` icon has a down arrow. Therefor this should be _sunset_ (dusk; sundown).

**Comment by FreexD** [comment]
Thanks! Fixed in https://github.com/tabler/tabler-icons/commit/48d88887d77409a0cc48f39bfe464ee1efd55454
