### ISSUE TITLE
Issue with some icons

### ISSUE THREAD

**Issue by hishamabri** [tabler/tabler-icons#1110]
Some icons have suddenly changed and became filled.
Was this an intentional change?
![image](https://github.com/tabler/tabler-icons/assets/5760752/84fa071f-2788-4a90-9550-10d527142fcb)

Another icon I noticed has changed is the TbStar. Previously an outline. Now filled.

I'm on react

Thanks

**Comment by BG-Software-BG** [comment]
`react-icons` is not a package created by Tabler team. See https://www.npmjs.com/package/@tabler/icons-react if you want an official Tabler package for React.

https://tabler.io/icons/icon/book and https://tabler.io/icons/icon/star icons have both outline and filled versions.
