### ISSUE TITLE
[Icon Request] state/province icon

### ISSUE THREAD

**Issue by sebastienbarre** [tabler/tabler-icons#1114]
Would be nice to have an icon to represent a state or province. 
Now this would mostly apply to the USA in my use-case, so I was thinking of maybe a map of the USA with a pin on one of its state?  There are just too many US states for one icon per state.

Thanks 

Seen online:

<img width="1407" alt="image" src="https://github.com/tabler/tabler-icons/assets/329967/f8383d80-5cbb-44ce-8c4a-3728f5d828ce">

**Comment by BG-Software-BG** [comment]
I think that it's impossible to make a map of the USA as a 24x24 px icon.
