### ISSUE TITLE
[Icon Request] fee icon

### ISSUE THREAD

**Issue by sebastienbarre** [tabler/tabler-icons#1116]
Thanks for all the work. It would nice to have an icon representing a fee.
I'm thinking of a $ sign inside the existing Tabler tag icon for example, to represent an additional amount of money attached to something.

Thanks!

Seen online:

<img width="1401" alt="image" src="https://github.com/tabler/tabler-icons/assets/329967/91a8ab75-3234-44f4-a1f0-c0627cf8c50b">

**Comment by BG-Software-BG** [comment]
Maybe https://tabler.io/icons/icon/receipt-2 icon could be good for your need?

**Comment by sebastienbarre** [comment]
Close enough, thank you :)
