### ISSUE TITLE
Lines of some icons overlap causing visible spots

### ISSUE THREAD

**Issue by xorinzor** [tabler/tabler-icons#112]
The lines in some of the icons seem to overlap/intersect, causing spots to appear. This only seems to happen when you use a partially transparent color.

To demonstrate this, I increased the stroke-width to a high amount, this is just for visual effect, even at a stroke-width of 1 these spots are visible.

![Screenshot (2)](https://user-images.githubusercontent.com/4212335/106202744-a1b90280-61ba-11eb-857a-99d0468a3999.png)
![Screenshot (1)](https://user-images.githubusercontent.com/4212335/106202751-a2ea2f80-61ba-11eb-90c8-a3e1702503a3.png)

There might be other icons with the same issue, these 2 are just the ones I have used which have the issue.

**Comment by tofful** [comment]
I think that is expected if you add transparency to the paths, try by just using a solid color to the icon and apply transparency to the parent `<div>` container instead @xorinzor

**Comment by FreexD** [comment]
@xorinzor tabler icons are build upon SVG paths and will always overlap in some places. Try out @tofful advice :)

**Comment by DVSoftware** [comment]
Sorry to resurrect such an old issue, but merging paths with svgo solves this issue, however this would mean every icon in the repository needs to be updated.
If such solution is acceptable, I can make a PR that does this.
