### ISSUE TITLE
[Icon Request] more traditional handshake icon

### ISSUE THREAD

**Issue by sebastienbarre** [tabler/tabler-icons#1120]
Howdy. This request is minor, since there is already a handshake icon in Tabler (see below) 

<img width="149" alt="image" src="https://github.com/tabler/tabler-icons/assets/329967/5953e257-1851-4e07-9c5b-cfbd1778000a">

Would it possible to have an alternate version that is not in the shape of a heart, since the current one conveys a meaning that might not coincide with a handshake in a "professional" setting? Ideally the end of a dressed shirt would be visible on the wrist, to reflect the context.

Thank you

For example:

<img width="1095" alt="image" src="https://github.com/tabler/tabler-icons/assets/329967/19a9c087-98e0-4fe9-a230-fdf9be261128">

<img width="974" alt="image" src="https://github.com/tabler/tabler-icons/assets/329967/a98a3244-5ed4-41e8-b5ec-8de899f72a20">

**Comment by BG-Software-BG** [comment]
I think that more traditional handshakre can be impossible to fit in 24x24 px icon.
