### ISSUE TITLE
Tabler UMD is bundled with react build files

### ISSUE THREAD

**Issue by theMasix** [tabler/tabler-icons#113]
Hello. I'm using `react@17.0.1` alongside `@tabler/icons@1.38.1` npm package and its icon components.
I did a performance analyze with [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/) on my site and an analyze with `source-map-explorer` which is recommended by CRA documentation, [Analyzing the Bundle Size
](https://create-react-app.dev/docs/analyzing-the-bundle-size/). In both cases, I noticed there is a UMD file named `@tabler/icons/icons-react/dist/index.umd.js` in build files.

![image](https://user-images.githubusercontent.com/22872117/106388890-c0efa400-63f5-11eb-8507-d52dbe54308e.png)

I think it's extravagant to exist a UMD file with `637KB` in build files!
So How can I fix it and avoid bundling a UMD file in build process?

**Comment by adambrgmn** [comment]
I just encountered this issue as well. And it seems to be related to the fact that `@tabler/icons` defines the UMD build of the library on the `browser` prop in `package.json`:

```js
{
  "main": "./icons-react/dist/index.cjs.js",
  "module": "./icons-react/dist/index.esm.js",
  "browser": "./icons-react/dist/index.umd.js", // <-- this one
  "types": "./icons-react/index.d.ts",
}
```

And by default `webpack` resolves [`browser` before `module` and `main` fields](https://webpack.js.org/configuration/resolve/#resolvemainfields).

I usually use `microbunde` to build libraries, which is irrelevant in this case, but they recommend putting a UMD build under the key `unpkg` or `umd:main`. [They don't even use the `browser` key anymore](https://github.com/developit/microbundle#-installation--setup--).

I would love to provide a PR to change this, if the maintainers agree on the issue 😊

**Comment by theMasix** [comment]
@adambrgmn Thanks for useful and precise info about the issue. So I think @codecalm can help us.

**Comment by adambrgmn** [comment]
Just a quick tip on how to fix this at this moment, that I forgot to mention last time:

If you control your webpack config you can add an alias:

```js
module.exports = {
  resolve: {
    alias: {
      '@tabler/icons': path.resolve('./node_modules/@tabler/icons/icons-react/dist/index.esm.min.js'),
    },
  },
};
```

If you can't control the webpack config you will have to point directly towards the correct file:

```js
import * as Tabler from '@tabler/icons/icons-react/dist/index.esm.js';
```

This solves the immediate issue until it can be resolved in this project.
