### ISSUE TITLE
Open in new tab icon

### ISSUE THREAD

**Issue by titoworlddev** [tabler/tabler-icons#1134]
### Icon name

open-new-tab

### Use cases

It is used to put a button that takes you to a new page.
For example: you have a product recommendation website and you want to open the product website, then you put this icon on the button

### Design ideas

![image](https://github.com/tabler/tabler-icons/assets/70041483/613e395c-c97f-46b1-b151-289082161c07)
![image](https://github.com/tabler/tabler-icons/assets/70041483/5097c339-09ec-4aa1-b4b8-d4283d998215)
![image](https://github.com/tabler/tabler-icons/assets/70041483/0425c7e1-7155-4974-ace2-02ec5434cd8f)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by BG-Software-BG** [comment]
The icon is already in the Tabler library. It's called [external-link](https://tabler.io/icons/icon/external-link)

**Comment by longprao** [comment]
This took me a long whilte that I could not find this icon, I searched for all kinds of query like "arrow", "open new tab", "tab", "square arrow", "share" etc... but never thought it was "external-link" until I googled to find this github. 

So would it be possible to add another name like "open-new-tab" to this icon, or make such query to show the "external-link" icon? @BG-Software-BG

**Comment by BG-Software-BG** [comment]
The "external-link" name is quite common for this icon.

We'll add more tags to make it easier to be found on https://tabler.io/icons.
