### ISSUE TITLE
Layers icon for maps

### ISSUE THREAD

**Issue by alizehkhan** [tabler/tabler-icons#1144]
### Icon name

layers

### Use cases

I need a layers icon for the button to see the map options available eg. satellite, terrain, roads etc.

### Design ideas

![layers](https://github.com/tabler/tabler-icons/assets/59119022/7c8f1c8b-bb5e-4bc3-8e36-256abb51f14c)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by agentphoenix** [comment]
@alizehkhan would something like the existing `stack-2` work for your use case?

**Comment by alizehkhan** [comment]
> @alizehkhan would something like the existing `stack-2` work for your use case?

Yes that's perfect! I missed this. Thanks so much for sharing. Will close this issue.
