### ISSUE TITLE
Need theme 

### ISSUE THREAD

**Issue by morbishreejioff** [tabler/tabler-icons#117]
Hi, friend, Is it possible to get the theme used in tabler-icons.io?
Please reply on this,
Many Thanks 
regards
Amitt

**Comment by morbishreejioff** [comment]
Hi friend,
Is there any chance to reply?
Thanks in advance!

**Comment by zaddok** [comment]
Perhaps consider asking the creators of that .io website for more information about the stuff at that .io website?

I’m not sure anyone on GitHub knows much about that website.

**Comment by FreexD** [comment]
Hi @morbishreejioff :) https://tabler-icons.io/ uses a custom theme made from scratch by Tabler maintainers ;) We do not obfuscate the website css so you can just unminify and use it :) The unminified, uncompiled css sources however are not available.
