### ISSUE TITLE
Icon font is misaligned in Flutter

### ISSUE THREAD

**Issue by adiospace** [tabler/tabler-icons#118]
Hi,

first of all, thank you for this awesome font!

I'm using it in a Flutter app, as an icon font, and it seems it's a bit misaligned. Here's a snapshot next to Material Icons font to see the difference.

<img width="226" alt="CleanShot 2021-03-11 at 19 06 39@2x" src="https://user-images.githubusercontent.com/31248/110825901-35dbb680-829d-11eb-834a-e03e93a29cf6.png">

Any ideas why?

**Comment by adiospace** [comment]
I went on Sketch, open 2 icons, select the paths and convert them into outlines and now I get this...

![wel04vwaAr2TP8VWnUCi96UiRd6CK3b9Kev5Afe7](https://user-images.githubusercontent.com/31248/110831552-062fad00-82a3-11eb-9092-1803ab5dc9d6.jpeg)


which is an improvement, but still a bit misaligned.

**Comment by zaddok** [comment]
It depends on what size your intending to use the icons at.  I have the opposite problem. I tend to make the font smaller, and have to futz around with padding to get them to align correctly. There’s not going to be a one size fits all solution here. Just adjust the padding/margin/size to suit your needs.

**Comment by zaddok** [comment]
But is, there are a few that do genuinely not align perfectly, but I assume your referring to overall general alignment.

**Comment by FreexD** [comment]
@zaddok @adiospace can this be related to #14 ?

**Comment by ranfdev** [comment]
This is not specific to flutter, it's a problem even on the web when using the icon fonts

**Comment by ranfdev** [comment]
The issue is also clearly visible in the included example webpage: https://github.com/tabler/tabler-icons/blob/master/iconfont/tabler-icons.html

![Screenshot from 2022-06-11 13-45-34](https://user-images.githubusercontent.com/23294184/173186521-e1aecb7a-322f-4206-8afe-fae770bd2957.png).

I've solved this issue by adding a css transform:
```css
i.ti {
  /* 
  compensates the wrong top spacing in the iconfont.  
  See https://github.com/tabler/tabler-icons/issues/118/ 
  */
  transform: translateY(-1px); 
}
```

**Comment by codecalm** [comment]
it's fixed already! :)
