### ISSUE TITLE
"circle-dashed-letter-letter-v" icon must be removed.

### ISSUE THREAD

**Issue by mnakhli** [tabler/tabler-icons#1189]
### Description

"circle-dashed-letter-letter-v" icon is wrong.
Thanks for updates you provide.

### Package

- [X] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [ ] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.11.0

### Browser

- [X] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Steps to reproduce

.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by BG-Software-BG** [comment]
Thanks for reporting this @mnakhli!

Details: Both https://tabler.io/icons/icon/circle-dashed-letter-v and https://tabler.io/icons/icon/circle-dashed-letter-letter-v exist. The latter should be removed.
