### ISSUE TITLE
Stroke prop not accepting a Number. Has to be a ColorValue.

### ISSUE THREAD

**Issue by jbejas** [tabler/tabler-icons#1190]
### Description

You cannot set the stroke prop value to any Icon as it does not accept a Number value. It requires a ColorValue value. If the stroke prop is set, the icon dissapears.

"Type 'number' is not assignable to type 'ColorValue'."

### Package

- [ ] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [X] @tabler/icons-react-native
- [ ] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.11.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [X] iOS
- [ ] Android
- [ ] Other/not relevant

### Steps to reproduce

1. Install the library in your react native project.
2. import any Icon from the library in any component or view.
3. Add the stroke prop with a numeric value.
4. see the error on TS. "Type 'number' is not assignable to type 'ColorValue'."

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by BG-Software-BG** [comment]
It's not a bug – the `stroke` property is for setting the color of the stroke. To change the width of the stroke, you should use the `strokeWidth` property, which accepts numbers.

See more at: https://tabler.io/docs/icons/react-native.
