### ISSUE TITLE
[File Request] tags.json file not available in all 3.x.x versions

### ISSUE THREAD

**Issue by Tomic-Riedel** [tabler/tabler-icons#1196]
Hi!
In all Tabler 2.x.x versions, there has been a `tags.json` file available which was very helpful when wanting to implement a search functionality in his own app. Here is the file I mean in version 2.47.0: https://github.com/tabler/tabler-icons/blob/v2.47.0/tags.json

Is there a similar file available in 3.x versions that makes it possible to parse all the tags of the icons? If not, can this be added to the repo again?

I know that there is a similar file in the tabler icons figma repository, but this is also only till version 2.47.0.

Thank you very much!

**Comment by BG-Software-BG** [comment]
There is no `tags.json` in @tabler/icons 3.x.x repository but you can clone the repo and run `pnpm run build:icons`.
 It should create a `icons.json` file in `packages/icons` directory. It will have a structure similar to old `tags.json`.

**Comment by metacurb** [comment]
@Tomic-Riedel and for anyone else with this issue, as there doesn't seem to be a desire to export the json file:

The icons.json file exists in the installed library, so just needs to be exposed.  Update the `package.json` like so:


```diff
diff --git a/node_modules/@tabler/icons/package.json b/node_modules/@tabler/icons/package.json
index e4e1246..20e5c68 100644
--- a/node_modules/@tabler/icons/package.json
+++ b/node_modules/@tabler/icons/package.json
@@ -9,6 +9,7 @@
     "url": "git+https://github.com/tabler/tabler-icons.git"
   },
   "exports": {
+    "./icons.json": "./icons.json",
     "./*": [
       "./icons/*"
     ]
```

Then, set up `patch-package` (or your patching library of choice) and you should be good to go!
