### ISSUE TITLE
Smartphone vibrating

### ISSUE THREAD

**Issue by nboisteault** [tabler/tabler-icons#12]
First thank you for all those SVGs!
I'd love to see an icon for smartphone vibrating. Thanks again.

**Comment by codecalm** [comment]
will be available in next release :)

**Comment by codecalm** [comment]
![device-mobile-vibration](https://user-images.githubusercontent.com/1282324/77802066-6588b300-707a-11ea-93f4-2caf7a3b2ccc.png)

**Comment by eladeyal-intel** [comment]
@codecalm is this a familiar icon for vibrating?? I would not have known what it stands for if I didn't follow this thread. I think you need more lines around the phone, something like here https://xkcd.com/228/

**Comment by nboisteault** [comment]
> @codecalm is this a familiar icon for vibrating?? I would not have known what it stands for if I didn't follow this thread. I think you need more lines around the phone, something like here https://xkcd.com/228/

Maybe one more smaller line at each side could make it more understandable ?

**Comment by codecalm** [comment]
how about that?

<img width="234" alt="Screenshot 2020-03-28 at 18 25 09" src="https://user-images.githubusercontent.com/1282324/77829307-822bf600-7121-11ea-9594-4888c9975c46.png">

**Comment by codecalm** [comment]
or like that:

<img width="260" alt="Screenshot 2020-03-28 at 18 36 15" src="https://user-images.githubusercontent.com/1282324/77829563-18ace700-7123-11ea-894e-48116f2bbf1b.png">

**Comment by codecalm** [comment]
and third version:

<img width="204" alt="Screenshot 2020-03-28 at 18 39 01" src="https://user-images.githubusercontent.com/1282324/77829611-6f1a2580-7123-11ea-8195-b9ffed0f889e.png">

**Comment by nboisteault** [comment]
I vote for the second version but is the gray color intentional ?

**Comment by codecalm** [comment]
no, it's just screenshot from editor

**Comment by eladeyal-intel** [comment]
I vote for the second version too. thanks!!

**Comment by codecalm** [comment]
done, https://github.com/tabler/tabler-icons/releases/tag/v1.4.0
