### ISSUE TITLE
Building with Vite and SolidJS includes all icons

### ISSUE THREAD

**Issue by martinpengellyphillips** [tabler/tabler-icons#1203]
### Description

When building my application (that uses `@tabler/icons-solidjs`) with Vite I was expecting icons to be tree shaken to only include the ones imported. But ALL icons are being included in the build.

Example import:

```jsx
import {
  IconArrowNarrowRight,
  IconTrendingDown,
  IconTrendingUp,
} from "@tabler/icons-solidjs";
```

Running `vite build` results in all tabler icons being included, greatly bloating the application bundle. 

I see there were related issues reported against Svelte integration., but none specific to the Solid integration.

### Package

- [ ] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [X] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.11.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Steps to reproduce

1. Add `@tabler/icons-solidjs` to package (`pnpm add`)
2. Import an icon and use it (e.g.   `import { IconTrendingUp } from "@tabler/icons-solidjs";`
3. Run `vite build` (via `pnpm run build`)
4. Note that ALL tabler icons are processed and included in the build.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by levinit** [comment]
also in svelte, see https://github.com/tabler/tabler-icons/issues/669

**Comment by odnamrataizem** [comment]
Downgrading to the latest 2.x release fixed it for me, but I'd miss out on the new icons released since then.
