### ISSUE TITLE
`@tabler/icons-solidjs` 3.x.x bundle size issue

### ISSUE THREAD

**Issue by benoitv-code** [tabler/tabler-icons#1215]
### Description

I have a Vite project importing symbols from `@tabler/icons-solidjs`.

When using `@tabler/icons-solidjs` version `2.47.0`, the bundle size is 115.59 kB
When using `@tabler/icons-solidjs` version `3.14.0`, the bundle size is  2,795.96 kB

This is a huge bump.
My package.json defines `"type": "module"`, so I think the correct `esm` module should be imported, keeping only the imported symbols.

Is there an issue with `@tabler/icons-solidjs` version 3 in that regard?

I've seen #793 and #1161, but I am not sure they are related.

### Package

- [ ] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [X] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.14.0

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Steps to reproduce

1. Create a vite project
2. Import `import { IconSearch } from "@tabler/icons-solidjs";`
3. Build the client code
4. Notice the huge bundle size

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by goenning** [comment]
@inetol doesn't seem like that PR made much difference, still seeing this issue on `3.18.0`, did it work for you?

**Comment by inetol** [comment]
The PR didn't make it to `3.18.0`, if it's not reverted for some reason it should be included in the next release

**Comment by Citvej** [comment]
Any progress on this? We're currently dealing with a similar issue in NextJS 16 where tree-shaking doesn't seem to be happening.
