### ISSUE TITLE
Bed Icon Size Mismatch in Tabular Icons

### ISSUE THREAD

**Issue by sinjuangajan** [tabler/tabler-icons#1219]
### Description

I am using a set of icons (bed, bath, measure) in a web layout. However, the bed icon is noticeably smaller than the bath and measure icons, resulting in an inconsistent visual appearance.

![Screenshot 2024-09-06 095251](https://github.com/user-attachments/assets/b13f6b04-e0ec-419b-a509-1fca50f956cf)

### Package

- [X] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [ ] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.14.0

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [ ] Safari
- [X] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [X] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Steps to reproduce

1. Implement the bed, bath, and measure icons on a web page.
2. Observe that the bed icon is smaller than the bath and measure icons.

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by BG-Software-BG** [comment]
It's not a bug. There are a lot of icons that don't have 100% width or 100% height. 

This is because some of the objects/elements represented by the icons aren't square in real life. For example, a bed typically has a width larger than its height, so it's normal for its proportions to be different.

**Comment by sinjuangajan** [comment]
Thank you for the explanation. I understand that the icons represent real-life objects with varying proportions. From my perspective, visual consistency is crucial. Since these icons fall under the real estate category, similar to social media icons, any significant size discrepancy might affect their appearance. To address the issue with the bed icon, I’m opting for a customized icon approach for these specific icons instead of using web fonts to ensure better visual alignment.

![ICONS](https://github.com/user-attachments/assets/5781e59d-f4b7-43e2-83a7-b253afee2389)
