### ISSUE TITLE
[Icon Request] Food-related icons

### ISSUE THREAD

**Issue by doersino** [tabler/tabler-icons#122]
Hiya! I love *Tabler Icons* – so much that I'm happily using them throughout a recent project, a recipe-focused static site generator called [nyum](http://github.com/doersino/nyum). As part of its layout, certain properties of recipes are labelled with your brilliant icons – indicating whether they're *spicy* (`flame`), *vegan* (`leaf`), or contain *meat* (`bone`). [Here's an example recipe page](https://doersino.github.io/nyum/_site/cheesebuldak.html), in case you're curious.

Recently, I received a request for additional labels (see https://github.com/doersino/nyum/issues/7) that I can't find any relevant icons for among *Tabler Icons*, namely the following (along with my ad-hoc suggestions):

* *sweet*: Perhaps a piece of *candy*.
* *sour*: Could be a *lemon slice*.
* *salty*: A simplified *salt shaker*.
* *bitter*: A mug with steam rising, implying *coffee*. The existing `cup` icon doesn't quite evoke the same idea.
* *umami*: This one's difficult, perhaps best served with a *mushroom* or a *tomato*.
* *spicy*: `flame` works, but a *chili pepper* would be great!
* *meat*: Similarly, `bone` gets the point across, but a *steak* would be unambiguous.

I understand that designing icons is a time-consuming process, so I'd be very grateful if you were to consider adding some of these suggestions! I'm positive they'd also come in handy for other users.

**Comment by codecalm** [comment]
![Screenshot 2021-04-18 at 15 19 34](https://user-images.githubusercontent.com/1282324/115147067-85aa5c00-a059-11eb-879f-c7c824509a08.png)

:)

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v1.40.0 :)

**Comment by doersino** [comment]
Thank you so much!

I've left a small tip in your PayPal – I know it doesn't cover the time it must've taken to draw these icons, but I hope it shows my appreciation nonetheless.
