### ISSUE TITLE
[Icon Request] Heading icons H1 / H2 / H3 ...

### ISSUE THREAD

**Issue by lostdesign** [tabler/tabler-icons#123]
Hi there, I've seen that a generic heading icon exists, but I'd need specific heading icons for the different sizings. I tried to create them my own but could not get them to look like the base icons properly.

Thanks in advance!

**Comment by Hopiu** [comment]
@lostdesign There are already some icons H1 to H6, or are you looking for something else?
https://tabler-icons.io/i/h-1
https://tabler-icons.io/i/h-2
https://tabler-icons.io/i/h-3
https://tabler-icons.io/i/h-4
https://tabler-icons.io/i/h-5

**Comment by lostdesign** [comment]
Oh well, I could not find these looking for h1 and heading - maybe these tags should be added? Doubt anyone searches for h-1? Thanks for linking me these :D 

So then, its not a icon request anymore, but a tagging request?

**Comment by codecalm** [comment]
fixed! :)
