### ISSUE TITLE
[Icon Request] 10 and Joker

### ISSUE THREAD

**Issue by OctopBP** [tabler/tabler-icons#1230]
### Icon name

IconNumber10, IconJoker

### IconNumber10
There are all numbers from 0 to 9 in large size, and it definitely makes sense. But I think 10 can be an exception. There are a few cases where it is needed, and IconNumber10Small looks different.
In my example, I am working on card game statistics, and 10 is a big headache for now.
It would be great to have an IconNumber10 icon.
(Duplicate: https://github.com/tabler/tabler-icons/issues/825)

### IconJoker
This is also needed for cards, but I guess it can be used in many other cases.

PS: Thank you for your work!

### Design ideas

![2316782](https://github.com/user-attachments/assets/93f79cc2-aa63-439e-bb86-f22e12c6be81)
![carnival-joker-icon-vector-34532307](https://github.com/user-attachments/assets/b2d1eb0c-5888-4481-aa03-7dd616af3589)

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)
- [X] I have searched existing icons to make sure it does not already exist and I didn't find any.
- [X] I am not requesting a brand logo and the art is not protected by copyright.
- [X] I have provided appropriate use cases for the icon(s) requested.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v3.18.0 🙂 

![tabler-icons-3 18 0@2x](https://github.com/user-attachments/assets/8b5a9ad4-0739-4cfc-978b-7d4953b5c734)

**Comment by OctopBP** [comment]
Thank you!
