### ISSUE TITLE
Multiple spelling errors in icon tags

### ISSUE THREAD

**Issue by chris-thorn** [tabler/tabler-icons#1259]
### Description

I was browsing the catalogue to find suitable icons, and found multiple spelling mistakes in some of the tags. For example, my search for `electric` didn't return as many results as I was expecting, and on browsing the icons manually I found that a number of them had the tag `electirc` and `electrity` or `electricy`.

Here are a couple of examples:

![image](https://github.com/user-attachments/assets/2a4bc3a9-9273-46ec-baac-e034e1143ab9)

I was wondering what might be the best way to do a "bulk" spell check of all the icons?

_What follows is probably a separate issue, so I'm happy to resubmit separately if required..._

Additionally, searching for part of an icon's name in the search box on the main website doesn't seem to produce any results. It seems that the search box _only_ searches tags. This is problematic if, for example, I want to search for components related to electric circuits, but the word `circuit` isn't in the collection of tags for that icon.

### Search for `circuit` on the website:

![image](https://github.com/user-attachments/assets/ff038482-8b85-4384-a9e7-2ac302d8a072)

### Search for `circuit` in the repo:

![image](https://github.com/user-attachments/assets/e8434c07-090e-43d8-a241-f3509f18e3c5)

### Package

- [X] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [ ] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

latest

### Browser

- [ ] Chrome/Chromium
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [X] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [ ] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [X] Other/not relevant

### Steps to reproduce

Not required

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by BG-Software-BG** [comment]
@chris-thorn 

The screenshot for `circuit` is not from our official website, which is https://tabler.io/icons. There are much more results for `circuit` search.  
![image](https://github.com/user-attachments/assets/1f409ab1-8ec3-4c95-bf54-ea00edb13e09)

Thanks for noticing typos in the circuit icons. We'll fix them in the next release.
