### ISSUE TITLE
Error using Nextjs

### ISSUE THREAD

**Issue by Eriickson** [tabler/tabler-icons#126]
![image](https://user-images.githubusercontent.com/38663299/115437470-350e3c80-a1da-11eb-83f9-6d5d7764083a.png)

![image](https://user-images.githubusercontent.com/38663299/115437554-5111de00-a1da-11eb-9659-98cd593158ee.png)

**Comment by FreexD** [comment]
@Eriickson for now try https://stackoverflow.com/a/65978156 to fix your problem. 

@adambrgmn it's most likely related to changes from: https://github.com/tabler/tabler-icons/pull/116. We are now exporting the ESM bundle using the `exports` field - thats what's probably loaded in the node SSR bundle. The fix on our side would be to export the CJS bundle instead - but I'm not certain if it's really a bug on our side.. What do you think?

**Comment by adambrgmn** [comment]
Ah, I actually thought Next had things in place to handle this! But your solution @FreexD seems reasonable!

**Comment by matha-io** [comment]
Hello ! What about importing components like this : `import IconFa2 from '@tabler/icons/IconFa2` ?
With Next.js, we could then use this : 

`const IconFa2 = dynamic(() => import('@tabler/icons/IconFa2'))`;

or more dynamic : 

`const Icon = dynamic(() => import(`@tabler/icons/${name}`))`;

Or maybe export a default, so we can : 

`const Icon = dynamic(() => import('@tabler/icons').then(mod => mod[name]))`;

What do you think ?
