### ISSUE TITLE
Are calendar-week and calendar-month mislabeled?

### ISSUE THREAD

**Issue by sebastienbarre** [tabler/tabler-icons#1274]
### Description

Looking at the new 3.23.0 release (https://github.com/tabler/tabler-icons/releases/tag/v3.23.0)
and I can't help but wonder if the `calendar-week` and `calendar-month` icons are mislabeled? 
Shouldn't be the other way around?

<img width="689" alt="image" src="https://github.com/user-attachments/assets/684cf31c-41f1-4932-9d52-a9b9acac0720">

Maybe I'm missing something, but `calendar-month` looks to me above as 7 dots, indicating the 7 days in a week...

Conversely, `calendar-week` below looks like a calendar that has all its days filled, and a calendar page is usually a month:

<img width="690" alt="image" src="https://github.com/user-attachments/assets/751371ec-83eb-421a-9a70-91d8c167152f">

Just curious about the logic, or if I'm missing something.
Thanks!

### Package

- [X] @tabler/icons
- [ ] @tabler/icons-eps
- [ ] @tabler/icons-pdf
- [ ] @tabler/icons-png
- [ ] @tabler/icons-webfont
- [ ] @tabler/icons-sprite
- [ ] @tabler/icons-preact
- [ ] @tabler/icons-react
- [ ] @tabler/icons-react-native
- [ ] @tabler/icons-solid
- [ ] @tabler/icons-svelte
- [ ] @tabler/icons-vue
- [ ] Figma plugin
- [ ] source/main
- [ ] other/not relevant

### Version

3.23.0

### Browser

- [X] Chrome/Chromium
- [X] Firefox
- [X] Safari
- [ ] Edge
- [ ] iOS Safari
- [ ] Opera
- [ ] Other/not relevant

### Operating system

- [ ] Windows
- [ ] Linux
- [X] macOS
- [ ] ChromeOS
- [ ] iOS
- [ ] Android
- [ ] Other/not relevant

### Steps to reproduce

N/A, see preview above

### Checklist

- [X] I have searched if someone has submitted a similar issue before and there weren't any. (Please make sure to also search closed issues, as this issue might already have been resolved.)

**Comment by BG-Software-BG** [comment]
You're right @sebastienbarre. We'll fix them in the next release.
