### ISSUE TITLE
Use Tabler icons with license in Iconbox

### ISSUE THREAD

**Issue by sayjeyhi** [tabler/tabler-icons#130]
Can I add this icon pack to Iconbox: 

https://app.iconbox.space/
https://github.com/iconsbox

**Comment by FreexD** [comment]
@sayjeyhi sure!

**Comment by sayjeyhi** [comment]
Sure, thanks, I'll send updates here

**Comment by sayjeyhi** [comment]
TablerIcons added to Iconbox now. thanks to this great icon pack. <3 

https://app.iconbox.space/?package=Tabler
