### ISSUE TITLE
Download link on tabler-icons.io broken

### ISSUE THREAD

**Issue by doersino** [tabler/tabler-icons#132]
It points to https://github.com/tabler/tabler-icons/releases/download/v1.40.2/tabler-icons-1.40.2.zip – there is no such version.

**Comment by ToastcodeDev** [comment]
Exactly

**Comment by codecalm** [comment]
oh, sorry, will be fixed soon :)

**Comment by doersino** [comment]
Absolutely no hurry at all, just thought I’d let you know! 😊

**Comment by codecalm** [comment]
fixed :) By the way, there is a new version (1.41)
