### ISSUE TITLE
Icon Request: Expand/Collapse

### ISSUE THREAD

**Issue by xjure** [tabler/tabler-icons#135]
On the "IconSelector" maybe you could add the tag 'expand', and create a new icon with inverted arrows for the 'collapse'.
![CleanShot 2021-05-06 at 08 11 50](https://user-images.githubusercontent.com/9645731/117249945-baccf180-ae42-11eb-97cc-9e9c9a48cec0.png)

**Comment by bwiggs** [comment]
This would be great for toggling all items open/close in an accordion.
