### ISSUE TITLE
wrong pixel size in fonticon

### ISSUE THREAD

**Issue by 7ymekk** [tabler/tabler-icons#14]
I tried tabler-icons in my C++/Qt app as a replacement for FontAwesome and I noticed that I have to set font.pixelSize=46 to get 36px size. in FA font.pixelSize=36 gives proper 36px icons

**Comment by codecalm** [comment]
@7ymekk can you show me any screenshot with this bug?

**Comment by 7ymekk** [comment]
Here's screenshot from LibreOffice - same issue

![image](https://user-images.githubusercontent.com/1269434/77568073-5d891180-6ec8-11ea-9915-6d5d2c780d63.png)

**Comment by codecalm** [comment]
thank you, I'll check it! :)

**Comment by GitHubRulesOK** [comment]
Traditional since the dawn of time issue 72points = 25.4 mm = 96dpi issue

**Comment by kjvdven** [comment]
Noticed the same issue, when I replaced the icons in my design from font-awesome to tabler-icons. 
Using webfonts.

**Comment by FreexD** [comment]
@GitHubRulesOK @7ymekk can you check if using fonts from https://github.com/tabler/tabler-icons/pull/104 the problem still occurs?

**Comment by 7ymekk** [comment]
@FreexD it's way better as the icons are now in vertical center and some of them match the FA size, although all icons should have the same, or at least very close to each other, sizes. Please take a look at the screenshot below. First 3 icons are FontAwesome with pretty much standarized sizes +- 1px. 4 latter icons are Tabler. 2 first icons from Tabler are noticeable smaller than the third icon, and 4th icon is the biggest one. It won't look too good in an application UI when placed near each other.

I used LibreOffice to generate this screenshot. I can't check it in my app unfortunately, as I decided to go with commercial FontAwesome set.

![image](https://user-images.githubusercontent.com/1269434/104567632-4a118780-564f-11eb-96cb-d9d93c143cb9.png)

**Comment by FreexD** [comment]
Thanks @7ymekk . I know what the problem is now. I'll try to fix that ;)

**Comment by codecalm** [comment]
@7ymekk most of tabler icons has 2px space between icon and border, so it will be impossible to do like fontawesome. We would have to rewrite all icons

**Comment by 7ymekk** [comment]
@codecalm exactly, that's the problem I meant. Some icons have paddings, some doesn't, which makes UI inconsistent and it's really noticeable (you can see it in graphics I provided above). 
TablerIcons is really great and has just the perfect license, but unfortunately various paddings disqualifies its usage in more serious projects as it will never pass pixel perfect testing. I know I could change padding for some controls so icons would match each other but that adds more complexity in font usage.

if you're not planning on fixing this manner then I guess the issue can be invalidated/closed.
