### ISSUE TITLE
[Icon Request] Generic Protocol

### ISSUE THREAD

**Issue by Chaphasilor** [tabler/tabler-icons#140]
Hi,

I'm looking for an icon that represents any **protocol** or **URL scheme**.  
Specifically, the icon will belong to a setting that registers an app as a handler for a specific URL scheme, like `magnet:` or `web+coffe:` :)

It might make sense to split this into two icons, one for protocol (maybe something like `://`) and one for schemes ¯\\\_(ツ)\_/¯  
<sub>(While you're at it, adding icons for common protcols, like `http(s)://`, `ftp://`, `smb://`, etc., wouldn't hurt either :D )</sub>

It's not urgent, so please take your time ^^  
Looking forward to what you come up with! <3

**Comment by 0xflotus** [comment]
There are something like `slashes` but I also looking for an icon for protocols like `://`

**Comment by BG-Software-BG** [comment]
[protocol](https://tabler.io/icons/icon/protocol) was added in v2.45
