### ISSUE TITLE
Copy svg not working

### ISSUE THREAD

**Issue by yahu1031** [tabler/tabler-icons#143]
Copy SVG button not working all the time. It is not copying anything to clipboard. this is happening like 6-7 times out of 10. once it started not working it never works again on any icon but it shows copied toast.

**Comment by codewithkyle** [comment]
Steps to recreate:

1. Go to [https://tabler-icons.io/](https://tabler-icons.io/)
2. Scroll down until a new batch of icons are rendered
3. Click on an icon
4. Click the "Copy SVG" button
