### ISSUE TITLE
[Icon Request] Strikethrough as S icon

### ISSUE THREAD

**Issue by churichard** [tabler/tabler-icons#146]
The existing strikethrough icon (consisting of the letter U with a line through it) is very similar to the icon for underline, and they could easily be confused for each other if the two icons are in close proximity.

I think it would be great for another icon for strikethrough to be added: the letter S with a line through it. For inspiration you can take a look at Notion's hovering toolbar.

**Comment by prologic** [comment]
Yes can we change thie please?

Some have committed that it looks like a [top tall hat](https://twtxt.net/twt/4yydgaa) or a [dick](https://twtxt.net/twt/2gb4f5a) 😳

**Comment by codecalm** [comment]
@churichard @prologic how about that?

![Screenshot 2021-11-23 at 21 25 29](https://user-images.githubusercontent.com/1282324/143098650-8f96b152-9032-4029-a81d-6ab89fdea684.png)

**Comment by churichard** [comment]
Thanks @codecalm for taking a look at this!

I would personally prefer the S to be more "defined" so that it looks more like an S. The icon looks pretty abstract right now and I'm not sure if people would know what it does without prior knowledge.

It could be as simple as just connecting the top and bottom pieces to the middle horizontal line, but I'll leave that up to you!

**Comment by sorenpeter** [comment]
Hi, you had one back in https://github.com/tabler/tabler-icons/releases/tag/v1.38.1
![strikethrough](https://user-images.githubusercontent.com/8458421/143130248-3b4142fb-ca56-4463-a1dc-dbe1a9464e40.png)

But I agree that the line of the S should not be broken:
![strikethrough2](https://user-images.githubusercontent.com/8458421/143130250-137d97e5-2cfc-4f95-ae91-608c357b4c45.png)

**Comment by sorenpeter** [comment]
PR:  `.ti-strikethrough:before { content: "\ec62"; text-decoration: line-through; }`

producing:
<img width="188" alt="Screenshot 2021-11-23 at 22 34 55" src="https://user-images.githubusercontent.com/8458421/143133066-9b550ddd-4319-4c5e-8b7b-47ee7a6d0ba3.png">

**Comment by codecalm** [comment]
fixed in 1.45 :)
