### ISSUE TITLE
Missing zoom-out and zoom-question icons

### ISSUE THREAD

**Issue by mjchang** [tabler/tabler-icons#147]
zoom-out and zoom-question icons are missing even though they're available on the [website](https://tabler-icons.io/)

**Comment by giubatt** [comment]
Could also use this

**Comment by codecalm** [comment]
sorry, but tablericons .com is't connected with this project, please use tabler-icons.io :)

**Comment by giubatt** [comment]
> sorry, but tablericons.com is't connected with this project, please use https://tabler-icons.io :)

It's also displayed on https://tabler-icons.io, and the .svg is available in this repo, it's just not exported as a react component

**Comment by codecalm** [comment]
ah, sure
I'll check it

**Comment by mjchang** [comment]
@codecalm Bump on this. See https://github.com/tabler/tabler-icons/pull/148

**Comment by mjchang** [comment]
awesome thanks!
