### ISSUE TITLE
Database Icons

### ISSUE THREAD

**Issue by dflock** [tabler/tabler-icons#15]
Fantastic work so far!

Would love to see a set of database icons:

### Database Objects

- Database
- Table
- View
- Query
- Key
- Index
- Stored Procedure
- Function
- Schema
- User, Group, Role
- CSV file
- Log, Log File\table

### Database Actions

- Insert into Table
- Delete from Table
- Update Table
- Take table offline/bring table online
- Export Data
- Import Data
- Run Query
- Run Stored Procedure
- Grant/revoke Permissions
- Replication

**Comment by codecalm** [comment]
we'll see what we can do :)

**Comment by codecalm** [comment]
first part of database icons:

<img width="1229" alt="Screenshot 2020-10-14 at 14 25 10" src="https://user-images.githubusercontent.com/1282324/95988467-39236100-0e29-11eb-9787-3044e7ef3bc1.png">

**Comment by dflock** [comment]
Great work!

Looks like that last icon the one for Table... I would expect that to be more grid like, or symmetrical, maybe.

**Comment by dflock** [comment]
Great to see some more of these made it into the latest release, 1.39 :partying_face:

**Comment by codecalm** [comment]
@dflock more icons soon :)
