### ISSUE TITLE
Export the SVG files

### ISSUE THREAD

**Issue by simontaisne** [tabler/tabler-icons#150]
What about exporting the SVG files in addition to the React components?

For those using Next.js with SVGR this would allow such usage with dynamic import.

```tsx
const svg = {
  heart: dynamic<SVGProps<SVGSVGElement>>(() =>
    import('@tabler/icons/icons/heart.svg').then((mod) => mod.ReactComponent)
  ),
  ...
}

const Icon = ({ icon, ...props }) => {
  const Svg = svg[icon];

  return <Svg {...props} />;
};
```

**Comment by simontaisne** [comment]
@codecalm any opinion?

**Comment by codecalm** [comment]
@simontaisne I want to separate Tabler packages into png, vue, react, etc. By the way I will also take care of this task :)

**Comment by simontaisne** [comment]
Sounds great! Looking forward to it 💯

**Comment by codecalm** [comment]
@simontaisne we've added `*.svg` files do package.json config, can you try now? :)

**Comment by codecalm** [comment]
https://tabler.io/docs/icons/svelte
