### ISSUE TITLE
Delete exports field in package.json

### ISSUE THREAD

**Issue by ar53n** [tabler/tabler-icons#153]
Hello, thanks for the quality icon pack, but I have one problem with the `exports` field in package.json using the` vite` builder. I think this field is now being misused in `tabler-icons`.

https://github.com/vitejs/vite/issues/3250 First, i think it's vite problem, but later i thought that correct behavior

How i want it use:
```
import settingsUrl from "@tabler/icons/icons/settings.svg?url";
```

**Comment by alexgleason** [comment]
I worked around this issue by including the following in my webpack configuration:

```js
  resolve: {
    alias: {
      // Override tabler's package.json to allow importing .svg files directly
      // https://stackoverflow.com/a/35990101/8811886
      '@tabler': resolve('node_modules', '@tabler'),
    },
    // ...
  }
```
