### ISSUE TITLE
Size dropdown at https://tabler-icons.io/ not changing width/height of SVG code 

### ISSUE THREAD

**Issue by tomgenoni** [tabler/tabler-icons#157]
First, thank you for creating this resource. Really nice set of icons. 

The "Size" dropdown option at https://tabler-icons.io/ doesn't seem to affect the resulting SVG code. If the "Size" is set to `32px` the SVG made available to download or copy is the following. Note the height/width are both `24`.

```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-2fa" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
   <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
   <path d="M7 16h-4l3.47 -4.66a2 2 0 1 0 -3.47 -1.54"></path>
   <path d="M10 16v-8h4"></path>
   <line x1="10" y1="12" x2="13" y2="12"></line>
   <path d="M17 16v-6a2 2 0 0 1 4 0v6"></path>
   <line x1="17" y1="13" x2="21" y2="13"></line>
</svg>
```

The "Stroke" dropdown seems to works fine.

**Comment by FreexD** [comment]
@tomgenoni thanks for reporting that :) When manipulating the size we should set the `height`, `width` and `viewBox` accordingly in the downloaded SVGs.
