### ISSUE TITLE
Using icons with React Native

### ISSUE THREAD

**Issue by shelleyphant** [tabler/tabler-icons#158]
Hi, I'd love to use your icons for my React Native project, however importing via npm gives the following warning

Package @tabler/icons has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in ../node_modules/@tabler/icons/package.json

Have I just added the wrong package, or is this something you're still working on?

**Comment by FreexD** [comment]
@shelleyphant I guess there is no reason why tabler-icons should not work in React-Native as well :) I guess the package.json would need some tweaks to achieve that :) @shelleyphant are you willing to contribute a PR to fix the react-native support? :)

**Comment by 50UM3N** [comment]
@FreexD @shelleyphant  Hello I convert all the icons into react native svg component recently for an application. And also upload in the npm. Here is the GitHub link https://github.com/50UM3N/tabler-icons-react-native and npm link https://www.npmjs.com/package/tabler-icons-react-native

**Comment by JavaScriptJohn** [comment]
This would be very nice to have.

**Comment by carlosriveroib** [comment]
any updates on this?

**Comment by IhsenBouallegue** [comment]
updates?... 😢

**Comment by javialcantaras** [comment]
any updates?
