### ISSUE TITLE
Calendar icon with +

### ISSUE THREAD

**Issue by zaddok** [tabler/tabler-icons#16]
Would love an icon that represents "add calendar entry"

**Comment by GitHubRulesOK** [comment]
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z"/>
  <rect x="4" y="5" width="16" height="16" rx="2" />
  <line x1="16" y1="3" x2="16" y2="7" />
  <line x1="8" y1="3" x2="8" y2="7" />
  <line x1="4" y1="11" x2="20" y2="11" />
  <line x1="09" y1="16" x2="15" y2="16" />
  <line x1="12" y1="13" x2="12" y2="19" />
</svg>

**Comment by eladeyal-intel** [comment]
The cross is too big, it touches the calendar outline.

**Comment by GitHubRulesOK** [comment]
better ?
the problem is keeping it proportional in centre of existing shape

![image](https://user-images.githubusercontent.com/12754913/78944191-40059b80-7ab5-11ea-8ed4-40b18b3937e1.png)

```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-calendar-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
<path stroke="none" d="M0 0h24v24H0z"/>
<rect x="4" y="5" width="16" height="16" rx="2" />
<line x1="16" y1="3" x2="16" y2="7" />
<line x1="8" y1="3" x2="8" y2="7" />
<line x1="4" y1="11" x2="20" y2="11" />
<line x1="10" y1="16" x2="14" y2="16" />
 <line x1="12" y1="14" x2="12" y2="18" />
</svg>
```

**Comment by eladeyal-intel** [comment]
Both are fine imo

**Comment by codecalm** [comment]
I've added new calendar icons

<img width="949" alt="Screenshot 2020-04-10 at 15 37 25" src="https://user-images.githubusercontent.com/1282324/78994782-3295f300-7b41-11ea-804b-65fed61d7d9e.png">

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v1.5.0

**Comment by zaddok** [comment]
Amazing!!
