### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by remigermain** [tabler/tabler-icons#165]
can you add a brand-linux ? like  [tux](https://en.wikipedia.org/wiki/Linux) maybe , thx.

**Comment by codecalm** [comment]
how about that: 

![Screenshot 2021-11-16 at 20 42 16](https://user-images.githubusercontent.com/1282324/142054494-99086425-553f-48b2-90d7-37c4d71ea0fc.png)

**Comment by remigermain** [comment]
Yes, it's good, but tux will be good for the reference of all linux and not only of a specific distro. thx
