### ISSUE TITLE
Add icon like clear trash (request)

### ISSUE THREAD

**Issue by arisdevx** [tabler/tabler-icons#170]
Please add icon for permanent delete like clear trash.. 
like this image.

![1918192-200](https://user-images.githubusercontent.com/25075490/143356502-501ed6b0-840e-4bf6-8fee-dee707cccaaa.png)

**Comment by codecalm** [comment]
how about that: https://tabler-icons.io/i/trash-off ?

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v1.46.0

**Comment by arisdevx** [comment]
thank you very much.. trash-off is like inactive trash..
