### ISSUE TITLE
[Icon Request] Chair/Seat

### ISSUE THREAD

**Issue by eddiepineapples** [tabler/tabler-icons#172]
- As in a place to sit or...
- For use in theatrical terms (purchasing a seat)

Thank you!

**Comment by codecalm** [comment]
what do you think about this: 

![Screenshot 2021-12-09 at 01 31 48](https://user-images.githubusercontent.com/1282324/145312854-52a2ac35-71e2-4dde-8594-6539950852f2.png)

**Comment by eddiepineapples** [comment]
﻿
That was fast! I like both options. The one without legs is more suited for our usage (event tickets) but the one with legs is definitely more recognizable as a chair.

**Comment by codecalm** [comment]
made in https://github.com/tabler/tabler-icons/releases/tag/v1.48.0 and https://github.com/tabler/tabler-icons/releases/tag/v1.52.0 :)
