### ISSUE TITLE
Tabler Icon figma Plugin

### ISSUE THREAD

**Issue by ashdesigns** [tabler/tabler-icons#173]
Badly need a tabler icon Figma plugin 

you took reference code from here : https://github.com/feathericons/figma-feather

**Comment by FreexD** [comment]
@ashdesigns are you willing to contribute on this? :) For now you can use https://www.figma.com/community/file/1042928259792594757 to get icons in figma easily :) I'm adding a feature request label to this - we will consider that in the future development plans :)

**Comment by codecalm** [comment]
@ashdesigns try Tabler Icons plugin here: https://www.figma.com/community/plugin/1169807996149376642/Tabler-Icons 

:)
