### ISSUE TITLE
[Icon Request] Quote

### ISSUE THREAD

**Issue by DaDoBaag** [tabler/tabler-icons#174]
The only available "quote" or "citation" icon is the blockquote
![tabler-icon-blockquote](https://user-images.githubusercontent.com/42080855/145442240-48a0154d-774c-4e1b-aaf4-b66cb7ee55f1.png)
but I'd like to use the quotes only without the block, so like this
![tabler-icon-quote](https://user-images.githubusercontent.com/42080855/145443900-6229989c-6ea1-4f04-82a6-ef933faf5bb5.png)
Would appreciate it <3

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v1.49.0 :)
