### ISSUE TITLE
.DS_Store somehow slipped in npm module

### ISSUE THREAD

**Issue by whaaaley** [tabler/tabler-icons#175]
![image](https://user-images.githubusercontent.com/7419947/145759047-5873a975-9832-43d6-8769-cb5b5f7f891f.png)

Not a huge deal, but it broke one of my scripts that convert the icons to SVG data URLs for use in CSS. The script assumed everything in the dir was an svg, but it broke when it hit this. Just a heads up!

11/10 icons btw!

**Comment by codecalm** [comment]
hi @whaaaley, are you talking about zip package or npm version?

**Comment by whaaaley** [comment]
@codecalm Sorry I didn't mention, it's the npm version!

**Comment by FreexD** [comment]
.DS_Store was added to .npmignore :) thanks for reporting that @whaaaley
