### ISSUE TITLE
rings in olympics icon need to overlap

### ISSUE THREAD

**Issue by bricas** [tabler/tabler-icons#177]
The olympic rings icon just feels off if the rings don't overlap. Reference: https://en.wikipedia.org/wiki/Olympic_symbols#Rings

**Comment by bricas** [comment]
Doesn't seem to have changed as far as I can tell.

**Comment by bricas** [comment]
Hoping to get this re-opened.

Expecting:
![image](https://user-images.githubusercontent.com/18400/215099545-15cec7cf-dedc-46c1-9c92-02a89609712c.png)

Current:
![image](https://user-images.githubusercontent.com/18400/215099617-3d2ed6a2-1a17-486c-80fe-a5bf1fb6d1b6.png)

**Comment by codecalm** [comment]
unfortunately, but in 24px grid and 2px stroke it's impossible to overlap rings on that small image
