### ISSUE TITLE
TypeScript conflict type error

### ISSUE THREAD

**Issue by bud-mo** [tabler/tabler-icons#180]
Running `tsc` on a project with tabler-icons in react appear this error:

```
../project-name/node_modules/@tabler/icons/icons-react/index.d.ts:3:11 - error TS2430: Interface 'TablerIconProps' incorrectly extends interface 'SVGAttributes<SVGElement>'.
  Types of property 'stroke' are incompatible.
    Type 'string | number | undefined' is not assignable to type 'string | undefined'.
      Type 'number' is not assignable to type 'string | undefined'.

3 interface TablerIconProps extends SVGAttributes<SVGElement> { color?: string; size?: string | number; stroke?: string | number; }
            ~~~~~~~~~~~~~~~

```

After digging in types I think I found the source of the issue:
The type defined into `@tabler/icons/icons-react/index.d.ts` specify `stroke` property as `stroke?: string | number` which conflicts with the one defined by react as `stroke?: string | undefined;`.

I suspect the property used in this library is a bit different from the one defined by [W3C specification](https://www.w3.org/TR/SVG11/painting.html#StrokeProperty)

Taking a component for an example:
```jsx
import * as React from "react";

function IconZoomQuestion({
  size = 24,
  color = "currentColor",
  stroke = 2,
  ...props
}) {
  return <svg xmlns="http://www.w3.org/2000/svg" className="icon icon-tabler icon-tabler-zoom-question" width={size} height={size} viewBox="0 0 24 24" strokeWidth={stroke} stroke={color} fill="none" strokeLinecap="round" strokeLinejoin="round" {...props}><path stroke="none" d="M0 0h24v24H0z" fill="none" /><circle cx={10} cy={10} r={7} /><path d="M21 21l-6 -6" /><line x1={10} y1={13} x2={10} y2={13.01} /><path d="M10 10a1.5 1.5 0 1 0 -1.14 -2.474" /></svg>;
}

export default IconZoomQuestion;
```

We can see the `stroke` property is used as `strokeWidth` and `color` is used as `stoke`.
Which lead to this error and potentially can confuse many des.

## Quick fix
Enable the `skipLibCheck` option in `tsconfig.json` file:
```
{
  "compilerOptions": {
    "skipLibCheck": true
  }
}

```

## Suggestion
IMHO is better to not use the react package with the "dirty fix" and use the SVGs directly with a package like SVGR.

**Comment by cmmdmx** [comment]
Same issue for me, please fix!

**Comment by FreexD** [comment]
@bud-mo @cmmdmx can you share typescript versions and configs for your projects? :) I'd then be able to reproduce and fix this issue :)

**Comment by max-crcl** [comment]
Sure.

tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["./src"]
}
```

typescript (package.json):

```json
"@tabler/icons": "^1.68.0",
"typescript": "^4.6.4",
```

I'm currently using it inside a React Project scaffolded by vitejs, quite straigth from the docs, with React 17.

**Comment by saramorillon** [comment]
Hello, I have the same issue.
My tsconfig.json :
```
{
  "include": ["src", "tests", "vite.config.ts"],
  "compilerOptions": {
    "outDir": "dist",
    "target": "es5",
    "module": "commonjs",
    "jsx": "react",
    "sourceMap": true,
    "esModuleInterop": true,
    "strict": true
  }
}
```
My package.json :
```
{
    "@tabler/icons": "^1.90.0",
    "react": "^18.2.0",
    "typescript": "^4.8.2"
}
```

**Comment by Ridermansb** [comment]
Hey .. any update on this?
I'm haivng the same issue

```
"@tabler/icons": "^2.5.0",
"react": "^18.2.0",
 "react-dom": "^18.2.0",
"typescript": "^4.9.5",
```

**Comment by codecalm** [comment]
@Ridermansb you should use `@tabler/icons-react` library instead of `@tabler/icons` :)
