### ISSUE TITLE
Replace Gulp task "optimize" to using svg/svgo

### ISSUE THREAD

**Issue by WinterSilence** [tabler/tabler-icons#182]
[svg/svgo](https://github.com/svg/svgo) optimize icons better than [current implementation](https://github.com/tabler/tabler-icons/blob/5235090dae2d37af873376e736aab39bc773bd5b/gulpfile.js#L497). I'm suggest to use svg/svgo instead current "optimize" task. This package has been tested in practice and is used in Bootstrap Icons ([svgo.config.js](https://github.com/twbs/icons/blob/main/svgo.config.js)).

**Comment by WinterSilence** [comment]
@

**Comment by FreexD** [comment]
@WinterSilence are you willing to contribute on this? :)
