### ISSUE TITLE
[Icon Request] Vinyl Record icons

### ISSUE THREAD

**Issue by SierraNB** [tabler/tabler-icons#184]
An icon for a generic disc exists, but my project references both compact discs, 12" vinyl records and 7" vinyl records. I can't use one icon for all since that would cause confusion, and simply changing the color or size wouldn't be accessible and would still be confusing.

I'm suggesting a vinyl record icon be added, specifically a [33 1/2 RPM 12" vinyl record](https://en.wikipedia.org/wiki/LP_record), and a [45RPM 7" Vinyl Record ](https://en.wikipedia.org/wiki/Single_(music)) (see 7" format).

If both cannot be added and you can only pick one, the 33 1/2 RPM 12" Vinyl Record would be the better choice.

Thank you

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.53.0 :)
