### ISSUE TITLE
[Icon Request] C#

### ISSUE THREAD

**Issue by fingers10** [tabler/tabler-icons#189]

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.53.0 :)

**Comment by fingers10** [comment]
Hi @codecalm , 

Many thanks for adding `C#` logo. The following is the most commonly used logo for `C#`

![C# Logo](https://user-images.githubusercontent.com/43729469/151576680-70739567-b887-4c87-af64-330cb2c42fd3.png)

Please can you consider updating the logo?
