### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by RustBeard** [tabler/tabler-icons#19]
It will be nice to have icons like: 

- Facebook
- Twitter
- Linkedin
- Youtube
- Instagram
- Pinterest
- Snapchat
- Reddit

**Comment by codecalm** [comment]
First part of social/brand icons: 

![tabler-icons-1 9 0](https://user-images.githubusercontent.com/1282324/83903484-81859080-a75e-11ea-817b-022600fce110.png)

more here: https://github.com/tabler/tabler-icons/releases/tag/v1.9.0

**Comment by jrlanglois** [comment]
Few more suggestions, if you don't me tacking them on this Issue:
- YouTube
- Twitch
- Firefox
- Tumblr
- DeviantArt
- Reddit
- SoundCloud
- LinkedIn

**Comment by codecalm** [comment]
done! :)
