### ISSUE TITLE
Rendering issue?

### ISSUE THREAD

**Issue by shadear** [tabler/tabler-icons#193]
Hi, i have noticed a different bihaviour between chrome and firefox.
Using Vitesse template with unocss [link](https://github.com/antfu/vitesse-lite)

code snippet:
```vue
  <i class="text-4xl block opacity-100 bg-black text-black i-tabler-search" />
  <i class="text-4xl block opacity-100 bg-black text-black i-carbon-search" />
```
Up: Tabler
Down: Carbon

Chrome : Version 97.0.4692.71 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/47904282/150213510-729d148c-313c-4a39-b3d5-d8ed5cb7d567.png)

Firefox Developer Edition: 97.0b3 (64-bit)
![image](https://user-images.githubusercontent.com/47904282/150213760-10cdc26e-ccf1-4664-838f-ec20a3b90978.png)

**Comment by codecalm** [comment]
@shadear it looks like Firefox uses rgba colour or colour with opacity

**Comment by shadear** [comment]
Oh ok, if this is not related then feel free to close.
