### ISSUE TITLE
[Icon request] First responder badges

### ISSUE THREAD

**Issue by SierraNB** [tabler/tabler-icons#194]
The current badge icons resemble military ranks compared to badges first responders would wear. 
Linked below are examples of badges that first responders such as fire fighters, disaster response teams or emergency medical technicians wear.

Examples: 

[Fire department badge](https://www.pinmart.com/fire-department-badge-pin/)
[Generic badge shape (EMS, Fire, Police, Security)](https://cdn.shopify.com/s/files/1/0241/0041/products/4183G-600_grande.jpg?v=1533658966)
[More traditional badge shape for law enforcement](https://as2.ftcdn.net/v2/jpg/03/37/94/73/500_F_337947345_Bcd5UJwMgejs4Q0Ls2OgIL0IjJtMlXjm.jpg)
[Star shaped badge for law enforcement and security](https://www.galls.com/photos/styles/qm/zoom/S01-730.jpg)

Thank you

**Comment by codecalm** [comment]
I'll work on it! :) thank you for your sponsorship! ❤️
