### ISSUE TITLE
[Icon request] Basic road signs

### ISSUE THREAD

**Issue by SierraNB** [tabler/tabler-icons#195]
I adding in these icons would be a great addition to the current collection and would be very helpful in my current project involving traffic awareness. I've tried to give suggestions that are universal to any country to make the icons universal instead of localized to western countries. 

**Road icon:** [A road going away from the camera](https://cdn1.iconfinder.com/data/icons/working-tools-3/64/x-12-512.png)

**Stop sign:** [An octagon](https://upload.wikimedia.org/wikipedia/commons/f/fc/Thai_Stop_Sign.JPG) design is commonly used throughout the world, but an [inverted triangle in a circle design](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Vienna_Convention_road_sign_B2b-V4.svg/1280px-Vienna_Convention_road_sign_B2b-V4.svg.png) is also common. [Source](https://en.wikipedia.org/wiki/Stop_sign)
A shape alone wouldn't be enough to convey that the icon is a stop sign, I think adding in a [raised hand](https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Israel_road_sign_302.svg/1280px-Israel_road_sign_302.svg.png) inside would convey that it's a stop sign.

**Yield sign:** [An inverted triangle](https://upload.wikimedia.org/wikipedia/commons/f/f9/Give_way_outdoor.jpg) is used by [every country in the world.](https://en.wikipedia.org/wiki/Yield_sign)

**Priority road:** [An outlined diamond](https://en.wikipedia.org/wiki/Priority_signs)

**Speed limit signs:** [A red circle ](https://upload.wikimedia.org/wikipedia/commons/d/de/Hungary_road_sign_C-033-50.svg) is used commonly throughout europe, africa and asia, while a [vertical rectangle](https://upload.wikimedia.org/wikipedia/commons/8/8b/MUTCD_R2-1.svg) is common in north america.  [Source](https://en.wikipedia.org/wiki/Speed_limit)
But this brings a question as to how the numbers inside would be implemented, perhaps create an icon for each multiple of 10 up to 200 (160km/h is the highest speed limit in the world), or a redesign of the program allowing numbers to be added in procedurally.

**No entry sign:** [This design](https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/NO_road_sign_302.svg/1280px-NO_road_sign_302.svg.png) is used in pretty much every country, and would be helpful as a "no entry/denied" icon in general.

**No parking:** Simply the current parking icon with a line crossing it out.

I would like to add in a thank you to the tabler team - Your resources have been immensely useful and I can't thank you enough for your work.

**Comment by codecalm** [comment]
A part of road sign was added in https://github.com/tabler/tabler-icons/releases/tag/v1.54.0

![image](https://user-images.githubusercontent.com/1282324/154918798-889bf0f1-7e7d-4b29-a6e2-40fa67b39930.png)

I'm working on next part of road signs :)
