### ISSUE TITLE
cdnjs version outdated

### ISSUE THREAD

**Issue by saracmert** [tabler/tabler-icons#197]
Hi,

It seems that the cdnjs version is outdated. The latest version there is 1.35.0, while the actual version here is 1.53.0. This seems to be a problem at cdnjs's side, but I'm not sure.

https://cdnjs.com/libraries/tabler-icons

**Comment by codecalm** [comment]
hi @saracmert 
`tabler-icons` npm lib is deprecated, use `@tabler/icons` instead

you can use `unpkg` instead of `cdnjs`: https://unpkg.com/@tabler/icons@1.53.0/iconfont/tabler-icons.min.css
