### ISSUE TITLE
[Icon Request] DotNet Bot

### ISSUE THREAD

**Issue by fingers10** [tabler/tabler-icons#199]
![Official DotNet Bot](https://user-images.githubusercontent.com/43729469/151578331-8936b628-22e0-4003-a967-60dbfc286a04.png)

[Reference SVG Link for official dotnet bot](https://github.com/dotnet/brand/blob/main/dotnet-bot-illustrations/dotnet-bot/dotnet-bot.svg)

**Comment by codecalm** [comment]
its not possible to make 24 line icon based on this logo, sorry
