### ISSUE TITLE
[Icon Request] Phisical excercises icons: yoga, cardio, strength

### ISSUE THREAD

**Issue by aszwaj** [tabler/tabler-icons#203]
Could you provide three icons similar to "run" or "bike" for the following sports activities: yoga, strength training, cardio training?

**Comment by codecalm** [comment]
yoga was added in https://github.com/tabler/tabler-icons/releases/tag/v1.54.0 🙂

for strength training maybe you can use `barbell` icon? https://tabler-icons.io/i/barbell

**Comment by aszwaj** [comment]
Thanks for your prompt action on those icons.
We have already upgraded our product to use yoga icon. Good point as for
the barbell icon for strength training.

Adam

pon., 21 lut 2022 o 09:39 Paweł Kuna ***@***.***> napisał(a):
