### ISSUE TITLE
Iconfont: allow to customize the font format to ship

### ISSUE THREAD

**Issue by xvello** [tabler/tabler-icons#206]
While backwards compatibility with other browsers is great, it is not necessary for all websites. I'd like to only ship the `woff2` font, as it is sufficient to cover the target browsers for my project.

Bootstrap icons allow to [override the $bootstrap-icons-font-src variable](https://github.com/twbs/icons/blob/190eb16e74404d27b1772f094ca7de7b37ca7415/font/bootstrap-icons.scss#L2-L3) to limit the formats to ship and reduce the asset bundle size.

I started a branch introducing a similar variable, but [your font-face definition](https://github.com/tabler/tabler-icons/blob/aeb94bc15dfe4fd0d85e3f0f0df52f5147a627d2/iconfont/tabler-icons.scss#L10-L28) is a bit more complex, so I wanted to discuss implementation first. 

- Would you accept a PR introducing such changes?
- Why does the main font-face declaration have two `src` attributes? Is this a IE-specific workaround?
- How would we handle the media query targetting webkit browsers?

**Comment by FreexD** [comment]
@xvello great idea! Of course we would accept a PR adding this functionality if you are willing to contribute :) About the two font-face `src` attributes - you are right. IE does not support multiple `url('...') format('...')` and only accepts a single url in font-face src - also only supports EOT.

About the webkit browsers - can you explain a bit more what you mean exactly? :)

**Comment by xvello** [comment]
Heya @FreexD, thanks for your answer!

- Serious question, not a stab: is IE support still a desirable thing in 2022?
- It seems like you force the SVG font on webkit browsers, via the `@media screen and (-webkit-min-device-pixel-ratio:0)` media selector. Could you please tell me why such a rule exists, overriding the main `@font-face`?

Both of these overrides will make the patch more complex.

**Comment by FreexD** [comment]
True :) I guess IE was still a little bit of a thing in 2020 when icons started :) AFAIK Edge now runs IE compat mode and they're planning to get rid of IE entirely. @codecalm do we need IE support still? At worst whoever needs IE support can just use the EOT and redeclare the font-face to suit their needs.

As for -webkit-min-device-pixel-ratio I'm not 100% sure about the force - @codecalm could you clarify that?

**Comment by xvello** [comment]
Hello! I think the patch below should address the need I expressed, by adding the following variables:

- `$ti-font-src`, mirroring how `$bootstrap-icons-font-src` works. Users can override it to remove unneeded formats
- `$ti-legacy-compat-ie` and `$ti-legacy-compat-webkit` that default to true, but can be overridden to false to remove these compat hacks.

I unfortunately could not manage to rebuild everything with these template changes, so I could not open a PR. In the meantime, I transitioned by project to the SVG sprites, so I won't be needing that change anymore. I'll be closing this issue, but feel free to re-open if others express the same need.

```diff
diff --git a/.build/iconfont.scss b/.build/iconfont.scss
index c74e1a7e..4450bb4a 100644
--- a/.build/iconfont.scss
+++ b/.build/iconfont.scss
@@ -7,23 +7,31 @@ $ti-font-path: 'fonts' !default;
 $ti-font-display: null !default;
 $ti-prefix: 'ti' !default;
 
+$ti-font-src: url('#{$ti-font-path}/<%= fileName %>.eot?#iefix') format('embedded-opentype'),
+url('#{$ti-font-path}/<%= fileName %>.woff2') format('woff2'),
+url('#{$ti-font-path}/<%= fileName %>.woff') format('woff'),
+url('#{$ti-font-path}/<%= fileName %>.ttf') format('truetype'),
+url("#{$ti-font-path}/<%= fileName %>.svg\##{$ti-font-family}") format("svg")!default;
+$ti-legacy-compat-ie: true !default;
+$ti-legacy-compat-webkit: true !default;
+
 @font-face {
   font-family: $ti-font-family;
   font-style: normal;
   font-weight: 400;
   font-display: $ti-font-display;
-  src: url('#{$ti-font-path}/<%= fileName %>.eot');
-  src: url('#{$ti-font-path}/<%= fileName %>.eot?#iefix') format('embedded-opentype'),
-    url('#{$ti-font-path}/<%= fileName %>.woff2') format('woff2'),
-    url('#{$ti-font-path}/<%= fileName %>.woff') format('woff'),
-    url('#{$ti-font-path}/<%= fileName %>.ttf') format('truetype'),
-    url("#{$ti-font-path}/<%= fileName %>.svg\##{$ti-font-family}") format("svg");
+  @if $ti-legacy-compat-ie {
+    src: url('#{$ti-font-path}/<%= fileName %>.eot');
+  }
+  src: $ti-font-src;
 }
 
-@media screen and (-webkit-min-device-pixel-ratio:0) {
-  @font-face {
-    font-family: $ti-font-family;
-    src: url("#{$ti-font-path}/<%= fileName %>.svg\##{$ti-font-family}") format("svg");
+@if $ti-legacy-compat-webkit {
+  @media screen and (-webkit-min-device-pixel-ratio: 0) {
+    @font-face {
+      font-family: $ti-font-family;
+      src: url("#{$ti-font-path}/<%= fileName %>.svg\##{$ti-font-family}") format("svg");
+    }
   }
 }
 

```
