### ISSUE TITLE
build-iconfont/npm --install fails with npm error.

### ISSUE THREAD

**Issue by Nothorse** [tabler/tabler-icons#209]
I'm trying to build an iconfont with a stroke-width of 1, but I can't run "npm run build-iconfont". When I try to run npm --install I get the following error

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @tabler/icons@1.54.0
npm ERR! Found: rollup@2.28.2
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"2.28.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-uglify@6.0.4
npm ERR! node_modules/rollup-plugin-uglify
npm ERR!   dev rollup-plugin-uglify@"6.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/vagrant/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2022-03-01T15_19_26_731Z-debug-0.log
`

I'm not a node expert, so I'm clueless. is this a bug? Am I doing something wrong?

[eresolve-report.txt](https://github.com/tabler/tabler-icons/files/8162649/eresolve-report.txt)
.

**Comment by FreexD** [comment]
Hi @Nothorse! what is your npm & node version?

**Comment by ColinCampbell** [comment]
I'm getting a similar error on a fresh fork of the repo as of today.

```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @tabler/icons@1.60.0
npm ERR! Found: rollup@2.70.1
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"2.70.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@">=0.66.0 <2" from rollup-plugin-uglify@6.0.4
npm ERR! node_modules/rollup-plugin-uglify
npm ERR!   dev rollup-plugin-uglify@"6.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/colinc/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/colinc/.npm/_logs/2022-04-03T00_40_48_579Z-debug-0.log
```

Node is `v17.8.0` and nom is `8.5.5`

**Comment by Nothorse** [comment]
Node is v17.6.0, npm is 8.5.1

I found time to search around and the fix seems to be to remove rollup-plugin-uglify and only use terser. I've tried it and so far it works for generating fonts. I can't say anything about other tasks.

`From baa9500d46643ead4992e89e508ceca0b7c7d444 Mon Sep 17 00:00:00 2001
From: Nothorse <work@goldie.local>
Date: Mon, 4 Apr 2022 12:04:28 +0200
Subject: [PATCH 836/836] remove uglify

---
 package.json     | 1 -
 rollup.config.js | 4 ++--
 2 files changed, 2 insertions(+), 3 deletions(-)

diff --git a/package.json b/package.json
index 6ff93c3b..10e55b70 100644
--- a/package.json
+++ b/package.json
@@ -85,7 +85,6 @@
     "rollup-plugin-filesize": "9.1.2",
     "rollup-plugin-peer-deps-external": "2.2.4",
     "rollup-plugin-terser": "7.0.2",
-    "rollup-plugin-uglify": "6.0.4",
     "svg-outline-stroke": "1.3.0"
   },
   "release-it": {
diff --git a/rollup.config.js b/rollup.config.js
index 2b1b9845..a9f96cd4 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -4,7 +4,7 @@ import filesize from "rollup-plugin-filesize";
 import babel from "@rollup/plugin-babel";
 import external from "rollup-plugin-peer-deps-external";
 import { terser } from "rollup-plugin-terser";
-import { uglify } from "rollup-plugin-uglify";
+//import { uglify } from "rollup-plugin-uglify";
 import pkg from "./package.json";
 
 const input = "icons-react/index.js";
@@ -28,7 +28,7 @@ const minCjsPlugins = [
   external(),
   resolve(),
   commonjs(),
-  uglify(),
+  terser(),
   filesize(),
 ];
 
-- 
2.35.1

`

**Comment by FreexD** [comment]
@Nothorse nice workaround :) I guess that node 17 should not be supported with currently used packages/package versions. I think we should add `engines` field to `package.json` so that npm informs you whether the package is supported in your node version or not. Another step would be to add node 17 & higher support :) @Nothorse do you want to contribute a PR with a solution to this issue? :)

**Comment by Nothorse** [comment]
Sorry, I'm entirely clueless about node. I've attached the patch I used to get it working, which I basically found by googling furiously :)

So no, I can't offer anything beyond that little patch above. Sorry.
