### ISSUE TITLE
Game icon

### ISSUE THREAD

**Issue by Pra3t0r5** [tabler/tabler-icons#21]
I can see you have a dice there to symbolise Gaming, but i suggest a more common icon (or more variations) to include. A better aproach would be game controllers (joysticks) or the like.
Example:
![Screenshot from 2020-05-14 19-15-28](https://user-images.githubusercontent.com/38087682/81991331-64eeb080-9617-11ea-9094-afc2e521aa71.png)
(taken from [Ionic](https://ionicons.com/))

**Comment by codecalm** [comment]
see at `device-gamepad` icon :) 

<img width="159" alt="Screenshot 2020-05-30 at 14 27 55" src="https://user-images.githubusercontent.com/1282324/83328228-d4a0a480-a281-11ea-8b64-9e8e2fa563c4.png">

**Comment by Pra3t0r5** [comment]
Awesome, thank you very much!
