### ISSUE TITLE
[Icon Request] Min, Max, Avg

### ISSUE THREAD

**Issue by buddhaCode** [tabler/tabler-icons#211]
Hi there,
love this icon lib and tabler and using this a lot in a project. Thx dude!

I am looking for a minimum, maximum and average icon. To be honest, I have no clue how to visualize it. I have been looking in other icons libs like Font Awesome, as well. But they have no icon for this, too.

Best,
Arne

**Comment by devmount** [comment]
Maybe a bit too mathematical, but here is an idea of a possible visualization:

![image](https://user-images.githubusercontent.com/5441654/160767337-c109f0c9-9924-431e-9050-3e1361c0791a.png)

Of course this needs to be drawn properly. The first two icons would greatly fit with the existing `adjustments` icons.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.64.0 :)

**Comment by buddhaCode** [comment]
Oh that's great. Thank you guys!
