### ISSUE TITLE
Web tabler-icons.io is down

### ISSUE THREAD

**Issue by jozefrebjak** [tabler/tabler-icons#212]
@codecalm tabler-icons.io is down. We can't reach a page.

**Comment by codecalm** [comment]
@jozefrebjak there is status page: https://status.tabler.io/ - it looks like everything is okay :)

**Comment by jozefrebjak** [comment]
@codecalm I was unable for few seconds to reach a page. Maybe problem on my site. Btw status page looks really nice.
