### ISSUE TITLE
[Icon Request] Musical Instruments

### ISSUE THREAD

**Issue by rss-de** [tabler/tabler-icons#215]
Thanks Paweł for this ever extending awesome icon library. :)

I would be happy about icons for musical instruments, for example drums, guitar, keyboard, flute, etc.!

Thanks a lot!

**Comment by WinterSilence** [comment]
@bear2go draw icons

**Comment by SierraNB** [comment]
+1 for this. Here's what I can think of:

1. Electric guitar
2. Bass guitar
3. Acoustic guitar
4. Grand piano
5. Synth/Keyboard
6. Drumset
7. Saxophone
8. Trumpet
9. Trombone
10. Cello
11. Upright bass/Double bass
12. Violin
13. Tuba
14. Banjo
15. Organ

Although this is my western view on common instruments, for a global audience these instruments might be foreign to them, and they might question where the sitar, koto, pan flute or balalaika is, research will have to be done.

**Comment by WinterSilence** [comment]
@SierraNB 🥇 
> Electric guitar
> Bass guitar
> Acoustic guitar
> ...

it's 24x24 icon pack, how you planed drawing this?

**Comment by SierraNB** [comment]
I'm no artist but here's a 24x24 pixel art guitar and saxophone I drew https://imgur.com/a/vWVP9A7

**Comment by SierraNB** [comment]
Drawing the strings may be difficult, so distinction of the bass and electric guitars would be impossible, they might need to be combined

**Comment by shivavelingker** [comment]
I would love to echo having a guitar icon. Doesn't need to be overly detailed, but would _love_ to have a more relevant symbol beyond the general music symbol
