### ISSUE TITLE
[Icon Request] Laptop Off, Tablet Off

### ISSUE THREAD

**Issue by FrinkMan** [tabler/tabler-icons#216]
I'm wondering if icons like [this one](https://tabler-icons.io/i/device-desktop-off) would be possible for device-laptop and device-tablet?

**Comment by codecalm** [comment]
added in v1.58.0 :) 

https://github.com/tabler/tabler-icons/releases/tag/v1.58.0

![tabler-icons-1 58 0](https://user-images.githubusercontent.com/1282324/159771098-97f9fd9d-09ff-4f53-bbc6-e3ddd5384060.png)
