### ISSUE TITLE
[Icon Request] Adobe Suite Icons

### ISSUE THREAD

**Issue by kagiura** [tabler/tabler-icons#217]
Not sure how plausible this is with the multitude of Adobe programs and services, but having some would be nice if possible!

I sketched some up in Figma as an idea as well:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/58155530/160230267-e2b2841c-d7ea-4d27-bf06-310c1d82f641.png">

Thank you for this pack as well! Found them out through Iconify and I love them

**Comment by codecalm** [comment]
hi @yuuukun, thank you for help! can you share your Figma project? I can add those icons to Tabler :)

**Comment by yuuukun** [comment]
whoops,i was offline for a while! 

https://www.figma.com/file/dSlJnP6nNmF8wE4joEmDQW/Adobe-Icons-Concepts?node-id=0%3A1

I'm using it for a personal project of mine so if I find any other icons that could be useful I might open another issue, but for now I made these to try them out! Not sure if it fits the existing specifications but I hope at least its a starting point
