### ISSUE TITLE
[Typo] Thai Baht Currency

### ISSUE THREAD

**Issue by yuuukun** [tabler/tabler-icons#218]
(Sorry for double issue!)

The currency for the Kingdom of Thailand should be spelt "Baht" and not "Bath"! Its a minor mistake people make all the time so don't worry about that.

Here's an official document from the Thai govt (although its in Thai)
<img width="486" alt="image" src="https://user-images.githubusercontent.com/58155530/160231832-345d1396-aca0-430a-a959-6dc05347c2d0.png">
[Full version (Thai)](https://www.orst.go.th/pdfjs/web/viewer.html?file=/FILEROOM/CABROYINWEB/DRAWER004/GENERAL/DATA0000/00000699.PDF)

**Comment by codecalm** [comment]
thank you for that! Thai Bath is now fixed :)
