### ISSUE TITLE
Filled Variations

### ISSUE THREAD

**Issue by Pra3t0r5** [tabler/tabler-icons#22]
Multiple Strokes feature is awesome. My suggestion is to also add a filled icon option, to cover a wider range of usages.
Examples taken from [Ionic](https://ionicons.com/)
![Screenshot from 2020-05-14 19-21-48](https://user-images.githubusercontent.com/38087682/81991692-3d4c1800-9618-11ea-8aa9-17e1eca16415.png)![Screenshot from 2020-05-14 19-21-53](https://user-images.githubusercontent.com/38087682/81991695-3e7d4500-9618-11ea-9e77-2bb803602168.png)

**Comment by kjvdven** [comment]
I looked into replacing font-awesome with tabler-icons and I noticed I needed and sometimes preferred some filled icons.

- caret
- star
- rec
- play
- pause
- fast forward / backward

**Comment by grig0ry** [comment]
Removing the fill from caret icon instead of adding an alternative was a bad solution.

**Comment by itta611** [comment]
You can use `fill` css property to make icon filled.
```JSX
<IconStar style="fill: yellow;" />
```

**Comment by codecalm** [comment]
Added in v2! https://tabler-icons.io/?category=Filled

**Comment by MostafaRastegar** [comment]
if you used react icons and tailwind css:
`                <IconCircleFilled size={8} className="[&_path]:fill-gray-400" />`
