### ISSUE TITLE
[Icon Request] Grabbing

### ISSUE THREAD

**Issue by Andrew-web-coder** [tabler/tabler-icons#220]
Hi, I love your work! There are already multiple hand icons, but it is missing one that would indicate drag action. I just would like to replace CSS `cursor: grabbing` with SVG icon. Thanks!

**Comment by Andrew-web-coder** [comment]
I noticed that you added `hand-grab`. You are amazing! Thank you so much! :)

**Comment by codecalm** [comment]
@Andrew-web-coder  ❤️
