### ISSUE TITLE
`message-circle` and `message-circle-2` are identical

### ISSUE THREAD

**Issue by alexgleason** [tabler/tabler-icons#225]
Apart from the name, these two files are identical:

- https://github.com/tabler/tabler-icons/blob/master/icons/message-circle.svg
- https://github.com/tabler/tabler-icons/blob/master/icons/message-circle-2.svg

Is `message-circle-2` supposed to be *without the dots*? Because that's what I actually want.

**Comment by codecalm** [comment]
thank you for your help!
