### ISSUE TITLE
[Icon Request] Next.js / Svelte / Vue / Nuxt.js

### ISSUE THREAD

**Issue by yuuukun** [tabler/tabler-icons#229]
Like last time, went around looking and found nothing so here goes!
<img width="589" alt="image" src="https://user-images.githubusercontent.com/58155530/162825651-b8441a9b-e815-41a4-90ed-d03c0ebdafc2.png">
I also sketched out some ideas! Still unsure about Vue's though

https://www.figma.com/file/dSlJnP6nNmF8wE4joEmDQW/Adobe-Icons-Concepts?node-id=0%3A1

Thank you as always!

**Comment by codecalm** [comment]
awesome work! thank you very much! :) 

i've added it to https://github.com/tabler/tabler-icons/releases/tag/v1.64.0 :)
