### ISSUE TITLE
trees

### ISSUE THREAD

**Issue by eladeyal-intel** [tabler/tabler-icons#23]
May I humbly suggest that these do not look like trees? I thought these were ice cream bars and wondered who'd need such a specific icon).

![image](https://user-images.githubusercontent.com/20379005/83480018-e6ad5d80-a4a2-11ea-867b-80d957912cb4.png)

**Comment by eladeyal-intel** [comment]
https://www.google.com/search?q=TREES&tbm=isch&hl=iw&hl=iw&safe=active&safe=active&tbs=ic%3Agray%2Cisz%3Ai&rlz=1C1GCEB_enIL904IL905&ved=0CAMQpwVqFwoTCOCovrSP9OkCFQAAAAAdAAAAABAC&biw=1903&bih=1057

Many use a 'xmas tree/pine tree' (tall and spiky) or a citrus tree (cloud-like tree top)

**Comment by joedaniels** [comment]
I agree...

**Comment by lukjak** [comment]
I both use this icon and immediately considered it trees. I guess it depends on what you see more often...
To improve it, one could be a conifer-shaped.

**Comment by codecalm** [comment]
how about that?

![Screenshot 2020-10-11 at 14 16 04](https://user-images.githubusercontent.com/1282324/95678344-632c1780-0bcc-11eb-88db-ec5a412fdfd3.png)

**Comment by codecalm** [comment]
or that
![trees](https://user-images.githubusercontent.com/1282324/95678505-64aa0f80-0bcd-11eb-8d3e-49c4f71931b9.png)

**Comment by FreexD** [comment]
https://tabler-icons.io/i/trees
