### ISSUE TITLE
[Icon Request] Metronome 

### ISSUE THREAD

**Issue by SierraNB** [tabler/tabler-icons#236]
Example:
![](https://m.media-amazon.com/images/I/71nAHWZl2bL._AC_SX425_.jpg)
Thanks.

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.40.0 🙂 

<img src="https://github.com/tabler/tabler-icons/assets/1282324/527a23b9-2cae-4fd0-be5c-5ca7122fc9c4" width="584" alt="" />
