### ISSUE TITLE
[SUGGESTION] - Is there any options to show only new or by version icons ? 

### ISSUE THREAD

**Issue by nejcdev** [tabler/tabler-icons#238]
- Is there any options to show only new or by version icons ?

**Comment by Turk303** [comment]
on git hub : versions are listed under the "go to file" tab

per icons : image viewers such as "nomacs" [aka nomacs image lounge] has a number of user definable display view options enabling scroll through per image showing meta data in selectable info side panels or tiled multiple images with hover over pop up info & other means to speed up viewing/workflow.

Unsure if this is exactly what you require.

**Comment by FreexD** [comment]
@nejcdev On https://tabler-icons.io/ go to Changelog page: 
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/7117869/166106207-941300c6-59f4-4713-991e-3b84035dd37a.png">
Or simply search by version:
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/7117869/166106177-2441b2e0-a523-4563-8a51-b836e0dd4dbe.png">
Or use Latest category filter to show only new icons :) 
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/7117869/166106186-43267194-69e6-4a2b-bbed-8af63e47f8d1.png">
