### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by fl0wx** [tabler/tabler-icons#241]
Hey all,

is there currently a plan for supporting React18?

Thanks and regards
fl0wx

**Comment by whaaaley** [comment]
Same here. Or at least a way to install without the react dependency... I don't use the react components but I use react in my project.

**Comment by ilomon10** [comment]
Any updates?

**Comment by Kangarused** [comment]
I've tested by forcefully installing @tabler/icons into a React18 project using npm install --force and everything worked fine.

Presumably this would be resolved by updating the peerDependencies specification in the package.json to include 18.x

**Comment by Kangarused** [comment]
Also for anyone wanting a **hacky** solution, you can include a `.npmrc` file in your project with the `legacy-peer-deps=true` setting, it will cause all your npm installations to ignore peer dependencies.

I'll stress that this is a hacky solution, peer dependencies are often listed for a valid reason - using this hack means **you will no longer receive peer dependency warnings/errors for any packages you install**

**Comment by ilomon10** [comment]
I think its not a problem when you install with `npm 14`

**Comment by Disorrder** [comment]
it crashes Next.js app also 😒

**Comment by max-crcl** [comment]
Please, just add 

```json
"peerDependencies": {
    "react": "^16.x || 17.x || 18.x",
    "react-dom": "^16.x || 17.x || 18.x"
  },
```

to package.json. 

It already works when disabling the npm protections (--force), so I assume no problems.
It would help alot, thanks!

**Comment by fl0wx** [comment]
@codecalm , thanks :)
