### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by jappi00** [tabler/tabler-icons#254]
Hello together,

I am working on a svelte project and have used a small package to compile all SVGs to svelte components. Maybe it would be nice to provide them as well, directly in the source. The whole thing is fairly simple.

I am using the package svelvg like the following:
```js
import svelvg from 'svelvg'

svelvg.createLibrary("@tabler/icons/icons", { outDir: "src/components/icons"});
```

**Comment by codecalm** [comment]
added in v2 https://tabler.io/docs/icons/svelte :)
