### ISSUE TITLE
[Icon Request] Logic symbols (&)

### ISSUE THREAD

**Issue by OctopBP** [tabler/tabler-icons#255]
It would be nice to have logic symbols. At least `&` (`&&`) and `|` (`||`) symbols.

For `|` (`||`) there is `tallymark-1` and `tallymark-2`, so it is not so important, but `&` would be very useful.

And maybe logic gates like this:
![Gates](https://image.shutterstock.com/image-vector/digital-logic-gate-symbols-black-260nw-449422498.jpg)

Thank you :)

**Comment by codecalm** [comment]
i've added ampersand in https://github.com/tabler/tabler-icons/releases/tag/v1.73.0 :)

**Comment by codecalm** [comment]
logic symbols has ben added in https://github.com/tabler/tabler-icons/releases/tag/v1.74.0 :)
