### ISSUE TITLE
[Icon request] move icon

### ISSUE THREAD

**Issue by tomasMizera** [tabler/tabler-icons#257]
Hello, thanks for all your effort!

I would like to request icon "move", something similar to:

<img src="https://user-images.githubusercontent.com/22449698/177732291-609b464c-23d0-4ded-9ba7-09a6d0dbee08.png" width=300>

So far I rotate this zoom icon:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/22449698/177732738-9fb8ff0d-a6da-44cf-ac1f-a5467fcc1195.png">

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.73.0 :)
