### ISSUE TITLE
Kerning icon has typo in file name

### ISSUE THREAD

**Issue by bennetfabian** [tabler/tabler-icons#260]
The icon for kerning has a typo in its file name. Right now the file is named kering.svg instead of kerning.svg.

**Comment by codecalm** [comment]
done :)

**Comment by bennetfabian** [comment]
> done :) 

Is it really done? The icon name is still kering and therefore wrong, isn't it?

**Comment by justvanrossum** [comment]
The icon is still named "kering", and user "kering" as a tag as well. Suggest to reopen.

**Comment by bennetfabian** [comment]
@codecalm Could you reopen?
