### ISSUE TITLE
[Icon Request] poo

### ISSUE THREAD

**Issue by jankana** [tabler/tabler-icons#267]
The poo icon, just like the poo emoji has many uses. On top of my head I can think of an indicator for spam or a report button for spam.

Fontawesome has both simple and "with face" variants. I personally prefer it with face, because the funny character takes the "dirtiness" out of it somehow xD

fontawesome "happy" poo:
![image](https://user-images.githubusercontent.com/109215189/178968069-1cd15c89-b706-45e2-abd4-2b0a056a20be.png)

Of course it would be awesome if we can have both in Tabler icons :)

here's another example (angry):
![image](https://user-images.githubusercontent.com/109215189/178968757-7655fc62-bfc6-47f7-bbd2-366fa2a5b65c.png)

**Comment by wopian** [comment]
💩 got added today in 1.75.0 🎉 

https://github.com/tabler/tabler-icons/releases/tag/v1.75.0

**Comment by codecalm** [comment]
https://tabler-icons.io/i/poo :)
