### ISSUE TITLE
Importing svg icons into sketch goes wrong

### ISSUE THREAD

**Issue by kjvdven** [tabler/tabler-icons#27]
I imported all icons into sketch, and most of them don't have any issues. 

Brands
- Github
- Google
- Sketch

Border 
- bottom
- vertical
- horizontal
- inner
- left
- none
- outer
- radius
- top
- right

Sketch imported SVG's
![image](https://user-images.githubusercontent.com/306806/86400645-487f0400-bca9-11ea-8919-0ea3eec572dd.png)

Sketch imported PNG's
![image](https://user-images.githubusercontent.com/306806/86913531-17765780-c11f-11ea-8971-51ac6f67ac4f.png)

**Comment by codecalm** [comment]
fixed :) 

<img width="888" alt="Screenshot 2020-08-19 at 22 43 13" src="https://user-images.githubusercontent.com/1282324/90687629-67dbeb80-e26d-11ea-8f2e-d1bcc2631347.png">
