### ISSUE TITLE
Icon Request: Chalkboard

### ISSUE THREAD

**Issue by ShahriarKh** [tabler/tabler-icons#274]
### Discussed in https://github.com/tabler/tabler-icons/discussions/273

<div type='discussions-op-text'>

<sup>Originally posted by **ShahriarKh** July 29, 2022</sup>
This icon is really useful for learning platforms, schools, ...

Example from "boxicons":
![chalkboard-regular-24](https://user-images.githubusercontent.com/31452340/181808883-0419938b-a133-40f2-96be-4f6f4d06d3d6.png)
https://boxicons.com/?query=chalkboard
</div>

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v1.88.0 :)

**Comment by ShahriarKh** [comment]
thanks!
