### ISSUE TITLE
Official website shows different CDN than Github

### ISSUE THREAD

**Issue by jared-rice** [tabler/tabler-icons#284]
#265 Updated the CDN from `unpkg` to `jsdelivr`, however, the official website still shows the outdated `unpkg` cdn url when clicking the "Webfont" tab.

Example: 
![CleanShot 2022-08-11 at 10 06 45](https://user-images.githubusercontent.com/37887603/184153053-bde36e27-88b0-4676-aec0-951c8c29ea18.png)

https://tabler-icons.io/i/brand-tabler

**Comment by codecalm** [comment]
fixed :)
