### ISSUE TITLE
[BUG] Type 'number' is not assignable to type 'string'.

### ISSUE THREAD

**Issue by MariuzM** [tabler/tabler-icons#294]
Importing and setting icon prop like so `<IconSearch size={10} />` but on build i get error 

```
node_modules/.pnpm/@tabler+icons@1.84.0_biqbaboplfbrettd7655fr4n2y/node_modules/@tabler/icons/icons-react/index.d.ts:3:11 - error TS2430: Interface 'TablerIconProps' incorrectly extends interface 'SVGAttributes<SVGElement>'.
  Types of property 'stroke' are incompatible.
    Type 'string | number | undefined' is not assignable to type 'string | undefined'.
      Type 'number' is not assignable to type 'string'.

3 interface TablerIconProps extends SVGAttributes<SVGElement> { color?: string; size?: string | number; stroke?: string | number; }
            ~~~~~~~~~~~~~~~


Found 1 error in node_modules/.pnpm/@tabler+icons@1.84.0_biqbaboplfbrettd7655fr4n2y/node_modules/@tabler/icons/icons-react/index.d.ts:3
```

![Screen Shot 2022-08-20 at 19 53 06](https://user-images.githubusercontent.com/36937039/185747086-b6cef82d-a2a1-4db4-a537-12fc6b83bf66.jpg)

![Screen Shot 2022-08-20 at 19 55 32](https://user-images.githubusercontent.com/36937039/185747154-69e090b2-97fa-4615-965f-24495db9e9d3.jpg)

**Comment by juliarvalenti** [comment]
Currently updating Mantine and I'm receiving this error on `npm run build` due to `@mantine/rte`'s dependency on this package.
