### ISSUE TITLE
[Icon Request] Table tennis, Floor ball and Disc Golf

### ISSUE THREAD

**Issue by killawabbit** [tabler/tabler-icons#299]
I'm building an new web for the activity club I'm working at. We have a diverse range of activities in both sports and media. I love this icon pack and I would like to have the following icons to suggsted below:

Table tennis, probably a table tennis racket and ball similar to the cricket one.

Floor ball, a large sport in the nordic countries (in Sweden we call it innebandy and is hugely popular). Two suggestions here. One would be a floor ball and stick similar to the above. The second is the run icon with holding a stick and possibly a small ball in front of.

Disc golf, a frisbee derivate of golf very much on the rise here, but also an established sport globally. An Disc golf basket, a stick figure throwing a disc or a combination?

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.91.0 ;)
