### ISSUE TITLE
SPF +all mechanism should not be used at tabler-icons.io

### ISSUE THREAD

**Issue by dretva** [tabler/tabler-icons#305]
A quick dig command `dig tabler-icons.io TXT +short` outputs `"v=spf1 +all"`.

Page 54 of [RFC 7208](https://datatracker.ietf.org/doc/rfc7208/) shows this is an all-inclusive mechanism allowing all IP addresses to pass the SPF check. In simple terms, it means malicious actors could spam on behalf of your domain name and therefore [negatively affect domain reputation](https://knowledge.ondmarc.redsift.com/en/articles/1238318-what-is-the-all-mechanism-in-spf-and-should-i-use-it).

**Comment by codecalm** [comment]
fixed!
