### ISSUE TITLE
[Icon Request] Rocket Icon

### ISSUE THREAD

**Issue by ZebTheWizard** [tabler/tabler-icons#31]
It would be nice if there was a rocket icon. I like to use a rocket to signify that a button will launch something or falls into a game category.
Maybe something that looked like this.
![Image of Yaktocat](https://cdn4.vectorstock.com/i/thumb-large/19/43/rocket-icon-rocket-symbol-pictogram-isolated-icon-vector-23251943.jpg)

**Comment by codecalm** [comment]
@ZebTheWizard how about that? 

![Screenshot 2020-08-04 at 23 34 27](https://user-images.githubusercontent.com/1282324/89347444-13504200-d6ab-11ea-9dec-2f40a15fc58e.png)
