### ISSUE TITLE
[Icon Request] Solana

### ISSUE THREAD

**Issue by ramonfabrega** [tabler/tabler-icons#310]
Icon for cryptocurrency [Solana](https://solana.com/)

![solana-logo](https://user-images.githubusercontent.com/6278111/189237427-07161a32-4b7a-491f-96af-890f3556e0be.png)

<img width="1440" alt="Screen Shot 2022-09-08 at 5 30 21 PM" src="https://user-images.githubusercontent.com/6278111/189237279-eab4e6bf-c4c1-4dea-9b5f-42792b713e70.png">

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.96.0 :)
