### ISSUE TITLE
Incorrect icon for thumb-up 

### ISSUE THREAD

**Issue by MobinS** [tabler/tabler-icons#312]
title, also no thumb-up-off icon

<a href="https://ibb.co/f2XMHb9"><img src="https://i.ibb.co/s2gjqhC/Screenshot-1837.png" alt="Screenshot-1837" border="0"></a>

**Comment by codecalm** [comment]
yeah, sure. i’ll fix it soon

**Comment by codecalm** [comment]
fixed :)
