### ISSUE TITLE
[Icon Request] Caption

### ISSUE THREAD

**Issue by hylickipiotr** [tabler/tabler-icons#316]
It would be great to have a caption icon like in Notion 

![Zrzut ekranu 2022-09-13 o 11 04 22](https://user-images.githubusercontent.com/7335471/189860044-2424976b-b461-48db-aa61-a9cbb26bed59.png)

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.96.0 :)
