### ISSUE TITLE
Explicit UI to set color as “currentColor” on website

### ISSUE THREAD

**Issue by cbirdsong** [tabler/tabler-icons#32]
It would be ideal if you could set the copied icon color to `currentColor`. This is an ideal default, since it then inherits the color from its context in a page. Some UI tweaks that would accomplish this:

- adding an “x” button to the color field that clears it, setting the icons to `currentColor` and showing a placeholder in the field of `currentColor` or maybe `inherit`
- making the “reset” button clear the color field
- adding an “inherit” button to the color bar

I had also thought of some UI tweaks that would help communicate what emptying out the color field does:

- making the default icon color a less neutral color (perhaps purple, to match the button?)
- making the icon labels bold, so you can see that the icon color matches when it’s set to `currentColor`.

**Comment by codecalm** [comment]
Sorry @cbirdsong, but tablericons.com is not related to our project.
