### ISSUE TITLE
[Icon request] Zulip

### ISSUE THREAD

**Issue by skorokithakis** [tabler/tabler-icons#322]
Thanks for making Tabler! I use it for [Phantasmagoria](https://phantasmagoria.stavros.io) and love it!

I'd like to request the addition of the Zulip logo as an icon:

![](https://blog.zulip.com/content/images/2020/07/zulip-logo-gradient.png)

Thanks!

**Comment by codecalm** [comment]
done :) https://tabler-icons.io/i/brand-zulip

**Comment by skorokithakis** [comment]
Ahh you're amazing, thank you!
