### ISSUE TITLE
Pasting HTML code gives different results than pasting SVG.

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler-icons#330]
As an example, I'll use this icon: https://tabler-icons.io/i/plus

This is the template I used:

```html
<button class="btn btn-primary">
<!-- here goes the code -->
Example button
</button>
```

Code:
```html
<i class="ti ti-plus"></i>
```
Result:
![obraz](https://user-images.githubusercontent.com/210980/194162153-5d1b3764-aa13-4d46-81ea-98dc184054e3.png)

Code:
```svg
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-plus" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
   <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
   <line x1="12" y1="5" x2="12" y2="19"></line>
   <line x1="5" y1="12" x2="19" y2="12"></line>
</svg>
```
Result:
![obraz](https://user-images.githubusercontent.com/210980/194162291-9cb4133a-3c86-4e80-b854-fabf350b7bf2.png)

Is it possible to have the same results with webfont/CSS as with SVG?

**Comment by codecalm** [comment]
@dekoza thy to add `icon` class to `<i>` element

**Comment by dekoza** [comment]
Perfection :ok_hand:

**Comment by dekoza** [comment]
But in this case, please add `icon` to the class in the code :laughing:

**Comment by dekoza** [comment]
The same problem is with icons on Tabs. This time adding `icon` class does not help.

**Comment by dekoza** [comment]
<img width="80" alt="obraz" src="https://user-images.githubusercontent.com/210980/194643644-09f5ab04-b595-4d10-b198-3d88081ff5b1.png">

**Comment by dekoza** [comment]
I needed to add `me-2` class. There has to be a better way 😉
