### ISSUE TITLE
[Icon Request] Adult content

### ISSUE THREAD

**Issue by nicodemuz** [tabler/tabler-icons#332]
I'm aware that there is an "E" icon for explicit content. However, I'm afraid that this icon is not internationally recognized to be same as adult content. Perhaps we could have an icon with a girl pole dancing, or the number "18" with a forbidden icon around it?

**Comment by codecalm** [comment]
how about https://tabler-icons.io/i/rating-18-plus ? 

![rating-18-plus](https://user-images.githubusercontent.com/1282324/194510840-d06f67a4-406c-42b1-9659-a1e88941a8f7.png)

**Comment by nicodemuz** [comment]
@codecalm Awesome!! Many thanks! :)

**Comment by nicodemuz** [comment]
@codecalm should we add a tag "adult" for this icon as well?
