### ISSUE TITLE
[Icon request] Chess pieces

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler-icons#334]
Icons for chess pieces would be a great addition. Outlined and filled versions can dub as black and white.

**Comment by codecalm** [comment]
@dekoza what do you think?

![Screenshot 2022-10-21 at 20 35 04](https://user-images.githubusercontent.com/1282324/197266096-fd4166cd-c691-4467-a278-673dc51bf5e3.png)

**Comment by dekoza** [comment]
Very elegant

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.107.0 :)
