### ISSUE TITLE
[Icon request] Board games

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler-icons#335]
Icons characteristic for popular board/card games would be a great add.

- [Chess](https://github.com/tabler/tabler-icons/issues/334)
- Go
- Monopoly (the mascot guy)
- Poker chip
- Carcassonne (characteristic meeple shape)
- etc.

**Comment by codecalm** [comment]
first part has been added in https://github.com/tabler/tabler-icons/releases/tag/v1.102.0 :) 
![tabler-icons-1 102 0@2x](https://user-images.githubusercontent.com/1282324/194867081-41cd4ad8-0453-401f-a033-47427c3d60ca.png)
