### ISSUE TITLE
Icon sugguestion grip dots or six dots

### ISSUE THREAD

**Issue by RedFour** [tabler/tabler-icons#336]
Please add dots similar to these https://fontawesome.com/search?q=grip%20dots&o=r

**Comment by codecalm** [comment]
those icons already exists :)

https://tabler-icons.io/i/grip-vertical
https://tabler-icons.io/i/grip-horizontal 

![grip-horizontal](https://user-images.githubusercontent.com/1282324/196218187-bdb547b6-1cf1-4486-8334-94dd466e44cf.png) ![grip-vertical](https://user-images.githubusercontent.com/1282324/196218196-ee66d06a-b2e9-4c12-a69e-cbaed87804c9.png)

**Comment by RedFour** [comment]
That's great. I suggest adding the "dots" as a tag for these icons because they don't show up with other dots icons.

**Comment by codecalm** [comment]
I've added, will be released in next version :)
