### ISSUE TITLE
[icon request] Icons for timer actions - start, stop, pause, reset, etc.

### ISSUE THREAD

**Issue by dekoza** [tabler/tabler-icons#337]
I need icons that represent actions that can be taken with a timer - start, stop, pause, reset, etc. Might be `clock` with `player-play` etc. icons added in corner

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.105.0 :) 

![tabler-icons-1 105 0](https://user-images.githubusercontent.com/1282324/196275994-8a6222a0-890c-4716-8cf6-92bdb186892d.png)
