### ISSUE TITLE
Cylinder Icon

### ISSUE THREAD

**Issue by prateek332** [tabler/tabler-icons#339]
Please add a cylinder shape icon 🙏🏻
_because, for some reason, I use it a lot 😅_

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v1.105.0 :) 

![tabler-icons-1 105 0](https://user-images.githubusercontent.com/1282324/196275994-8a6222a0-890c-4716-8cf6-92bdb186892d.png)
