### ISSUE TITLE
React components

### ISSUE THREAD

**Issue by amille14** [tabler/tabler-icons#34]
It would be really great to get an official react package for these icons, something like [react-feather](https://github.com/feathericons/react-feather).

**Comment by konradkalemba** [comment]
I actually have created a wrapper for icons for React. Although it isn't official I think you can give it a go. It's available [here](https://github.com/konradkalemba/tabler-icons-react). You can find a preview website there as well. PS. Any contributions are welcome. :)

**Comment by amille14** [comment]
@konradkalemba oh cool, I had found your package earlier but noticed it was out of date and didn't include quite a few of the newer icons. Looks like you just updated it though, which is awesome! Has the npm package been updated as well? Thanks!

**Comment by konradkalemba** [comment]
@amille14 Oh yeah, it hadn't been updated for quite some time. And regarding the npm package - yes, it has been updated as well.

**Comment by codecalm** [comment]
done :)
