### ISSUE TITLE
Typo in footer: "web site" should be "website"

### ISSUE THREAD

**Issue by Styxxy** [tabler/tabler-icons#35]
Typo in the footer, "web site" should be "website".

![Screenshot_20200716-005631~2](https://user-images.githubusercontent.com/1635825/87608205-8cd5bf80-c6ff-11ea-8746-969738deba9f.png)

**Comment by codecalm** [comment]
sorry, but tablericons.com are not connected to this repo. Its private site with preview of tabler-icons
