### ISSUE TITLE
Support Tree Shaking / Modularized Imports (React)

### ISSUE THREAD

**Issue by mgreenw** [tabler/tabler-icons#359]
Currently, the React build produces a single `index.cjs.js` / `index.esm.js` file including all icons. This is fine for some use cases but can cause bundle bloat / dev server slowness. It would be awesome if each icon was additionally put in its own file so they can be tree shaken effectively by a bundler. This would also allow something like Next.js to use  the [`modularizeImports` feature](https://nextjs.org/docs/advanced-features/compiler#modularize-imports) to not bundle every single icon in both the development and production build.

Example:
```json
"@tabler/icons": {
  "transform": "@tabler/icons/{{member}}"
}
```

**Comment by AlonMiz** [comment]
That's pretty important

**Comment by weimin1992** [comment]
I hope this feature too! This package's size shows below:
![image](https://user-images.githubusercontent.com/16208956/202073979-7b6472ab-2dc0-4f66-9334-6f756bf96dfe.png)

**Comment by m1911star** [comment]
Looking forward to seeing progress too

**Comment by codecalm** [comment]
I'm working on it here: https://github.com/tabler/tabler-icons/pull/378 :)

**Comment by mgreenw** [comment]
You're awesome @codecalm!

**Comment by markitosgv** [comment]
thanks @codecalm , what's the best option now using v2 on next for decrease bundle size?

**Comment by anthonyalayo** [comment]
Much needed, thank you!

**Comment by anthonyalayo** [comment]
@codecalm after testing out v2, it looks like typescript has issues with it? I found an associated issue here:
https://github.com/tabler/tabler-icons/issues/424

Would it be possible to throw the fix into the v2 branch for testing?

**Comment by markitosgv** [comment]
Is it possible to use with modularize imports from next? I'm using 2.0.0-beta from react-icons but it seems I cannot remove Icon prefix from member

```
import { Icon24Hours } from '@tabler/icons-react'
```

This is the route for Icon:

```
'@tabler/icons-react/dist/esm/icons/24-hours'
```

Is it possible to transform? I cannot remove (Icon)24-hours
```


        '@tabler/icons-react': {
            transform:
                '@tabler/icons-react/dist/esm/icons/{{ kebabCase member }}',
        },
```

Thanks!

**Comment by codecalm** [comment]
@markitosgv check `@tabler/icons-react` package :)

**Comment by anthonyalayo** [comment]
Thank you @codecalm ! I will give it a try too

**Comment by anthonyalayo** [comment]
Thank you for the hard work on that huge release @codecalm !

Unfortunately, it didn't work. I took a look at the package release, and I can see why.

The naming is not consistent between the exported value and the file itself:
```
export { default as IconMicrophone } from './icons/microphone.js';
```

And so a configuration like this will just point to a non-existent file:
```
  modularizeImports: {
    '@tabler/icons-react': {
      transform: '@tabler/icons-react/{{member}}',
    },
  },
```

`@mui/material-icons` made the names consistent, and that's why it worked over there. I don't yet know if there is more complicated regex I can do here (like remove the prefix Icon and lowercase). Can anyone else chime in?

**Comment by codecalm** [comment]
so, if I ranamed icons from `microphone.js` to `Microphone.js` will be okay?

**Comment by anthonyalayo** [comment]
@codecalm we can get around the casing with `{{ kebabCase member }}` but we can't get around the prefix `Icon` unfortunately

**Comment by codecalm** [comment]
so it should be `IconMicrophone.js`?

**Comment by anthonyalayo** [comment]
@codecalm exactly, same as the import. But before you put any work in, I think I found a workaround, they do support regex:
https://nextjs.org/docs/advanced-features/compiler#handlebars-variables-and-helper-functions

Let me attempt that right now and follow up

**Comment by codecalm** [comment]
yeah, I read this article and regex section and I think that will be problem with `IconName` convertion to `icon-name`

**Comment by anthonyalayo** [comment]
@codecalm agreed, I gave it my best shot but unfortunately I think there's nothing we can do without a rename. 

- I looked into the regex side, but it only applies to the import itself and not the members.
- I looked into other helpers, and I can't find anything like `substring` that could help make the naming line up
- Did a quick grep inside next.js, didn't see anything there either

**Comment by anthonyalayo** [comment]
Also just to clarify for this ticket, the issue isn't tree shaking, but of the import tree. Webpack needs to traverse the entire import tree regardless of tree shaking (which happens during minification). This slows down the build process whether you are performing a dev or prod build, but it creates noticeable performance problems in dev when they all get loaded in memory.

I filled a ticket on @mui for the same problem: https://github.com/mui/material-ui/issues/35840

**Comment by markitosgv** [comment]
> so it should be `IconMicrophone.js`?
> 
>  

Yes it could be icon-xxx or IconXxx but we need Icon prefix for nextjs transformation work . And I think is more consistent naming 

Thanks

**Comment by anthonyalayo** [comment]
@codecalm would this be considered a `2.1.X`, or a `2.0.X`?

**Comment by codecalm** [comment]
@anthonyalayo 2.0.1

**Comment by codecalm** [comment]
@anthonyalayo  I've opened PR: https://github.com/tabler/tabler-icons/pull/468/files 

what do you think? do I need add something to `package.json`?

**Comment by markitosgv** [comment]
> @anthonyalayo I've opened PR: https://github.com/tabler/tabler-icons/pull/468/files
> 
> what do you think? do I need add something to `package.json`?

I think it's ok! new names for files will be IconHome.js ?

**Comment by codecalm** [comment]
yes, exactly

**Comment by anthonyalayo** [comment]
@codecalm i'll try it out right now locally

**Comment by anthonyalayo** [comment]
@codecalm i'm struggling to get the build going with ruby (osx compile issues). If the outputted files are the same name as the variables, we're good to go

**Comment by codecalm** [comment]
I've compiled it and everything looks good :)

**Comment by anthonyalayo** [comment]
@codecalm i'm ready to test whenever the new version gets released on npm

**Comment by codecalm** [comment]
I'm testing new build and I'll release it as soon as possible. 

btw, new version will have number `2.1.0`, because there is a lot of improvemnts and new icons

**Comment by anthonyalayo** [comment]
Added it to a random project I was working on. 

Before:
```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 7.2s (5205 modules)
wait  - compiling /samplers/auction (client and server)...
event - compiled client and server successfully in 731 ms (5208 modules)
```

Adding these to my `next.config.js`:
```
  modularizeImports: {
    '@tabler/icons-react': {
      transform: '@tabler/icons-react/dist/esm/icons/{{member}}',
    },
  },
  transpilePackages: ['@tabler/icons-react'],
```

After:
```
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 6.5s (2007 modules)
wait  - compiling /samplers/auction (client and server)...
event - compiled client and server successfully in 192 ms (2010 modules)
```

Looks fantastic, thank you @codecalm ! I believe I had to add the project to `transpilePackages` as well since Next.js server code doesn't support ESM yet.

**Comment by anthonyalayo** [comment]
@codecalm, I was looking into the necessity of `transpilePackages: ['@tabler/icons-react']` by comparing it with `@mui/icons-material` which doesn't require it.

The magic is that `@mui/icons-material` is not bundling their CJS (require) code. Is there a reason `@tabler/icons-react` CJS is bundled? If the expected consumer of that flavor is other UI frameworks, then not bundling it would actually be better.

![image](https://user-images.githubusercontent.com/17555572/214737380-f4a262b9-2c47-4b10-8505-466aaeb15058.png)

![image](https://user-images.githubusercontent.com/17555572/214737120-14089187-ae0f-4aa4-8562-782d4e4fefe6.png)

**Comment by markitosgv** [comment]
To me @anthonyalayo it works without transpilePackages option, using nextjs 13.1.3. Doing a webpack analyzer in dev environment seems that only a few icons that I use are loading.

**Comment by anthonyalayo** [comment]
@markitosgv its definitely working with only loading a few icons, but the no transpile part sounds odd. Are you running with `type="module"`?

**Comment by anthonyalayo** [comment]
I'm not sure what tricks @markitosgv did, but it's definitely not working without `transpilePackages`. I just cloned a fresh Next.js project and it fails in the same way:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/17555572/214937478-9dad27f7-e0fe-45be-9228-b32e99e8e261.png">

I'll file a follow up ticket @codecalm since it's definitely considered another feature.

**Comment by markitosgv** [comment]
I'm using a monorepo with turborepo, I don't know if it's something with that

**Comment by anthonyalayo** [comment]
@markitosgv most likely something there is performing the same process, you can reproduce it with a vanilla app like I did above.

**Comment by markitosgv** [comment]
@anthonyalayo I've got a UI package with tabler icons dependency too, and this UI package in my monorepo is using transpilePackages option in next.config so I think is the reason that works for me

**Comment by codecalm** [comment]
@markitosgv @anthonyalayo will there be any more changes needed in the tabler icons code to improve the process?

**Comment by matthewoates** [comment]
> Is it possible to use with modularize imports from next? I'm using 2.0.0-beta from react-icons but it seems I cannot remove Icon prefix from member
> 
> ```
> import { Icon24Hours } from '@tabler/icons-react'
> ```
> 
> This is the route for Icon:
> 
> ```
> '@tabler/icons-react/dist/esm/icons/24-hours'
> ```
> 
> Is it possible to transform? I cannot remove (Icon)24-hours
> 
> ```
> 
> 
>         '@tabler/icons-react': {
>             transform:
>                 '@tabler/icons-react/dist/esm/icons/{{ kebabCase member }}',
>         },
> ```
> 
> Thanks!

I don't think you want to use kebab-case here. This worked for me:
```js
'@tabler/icons-react': {
    transform: '@tabler/icons-react/dist/esm/icons/{{ camelCase member }}'
},
```
