### ISSUE TITLE
Mobile view: only 1 column, try get 2nd (should be space?)

### ISSUE THREAD

**Issue by Styxxy** [tabler/tabler-icons#36]
On the mobile view the list of icons is now only one column on my phone. It seems there should be enough space for at least a second column.

![Screenshot_20200716-005947~2](https://user-images.githubusercontent.com/1635825/87608382-184f5080-c700-11ea-976d-201b9d35f315.png)

**Comment by codecalm** [comment]
sorry, but tablericons.com are not connected to this repo. Its private site with preview of tabler-icons
