### ISSUE TITLE
Can user upload their own SVG?

### ISSUE THREAD

**Issue by SketchySketch** [tabler/tabler-icons#37]
Not everyone has a GitHub account - and not everyone wants one. If they want to upload a good SVG picture, they'll have to create a Pull Request. So I suggest that there should be somewhere *inside the website* to upload images. Maybe you can use a database to store all the files? That'll be easier to add new files and also easier for others to implement this project.

**Comment by jrlanglois** [comment]
>  Maybe you can use a database to store all the files?

Sounds to me like that could be grounds for copyright issues.

**Comment by codecalm** [comment]
We don't foresee this possibility at the moment
