### ISSUE TITLE
Add https://tablericons.com to the repo description

### ISSUE THREAD

**Issue by lostdesign** [tabler/tabler-icons#38]
Perhaps it makes sense to link https://tablericons.com in the project description which appears above or besides the repo depending on what design you are on.

**Comment by codecalm** [comment]
sorry, but tablericons.com are not connected to this repo. Its private site with preview of tabler-icons

**Comment by lostdesign** [comment]
Ohh okay - well wouldn't it make sense to get in touch with them? I have found about it on [IndieHackers](https://www.indiehackers.com/post/my-crazy-launch-32-000-visitors-no-1-on-several-platforms-c702a5e59a)

Couldn't you both benefit from that then?
