### ISSUE TITLE
Icon Request: GraphQL

### ISSUE THREAD

**Issue by magahl** [tabler/tabler-icons#384]
Hello and thanks for an awesome library! I wanna kindly request an icon of the GraphQL logo. 

https://en.wikipedia.org/wiki/GraphQL

**Comment by codecalm** [comment]
GraphQL icon already exists: https://tabler-icons.io/i/brand-graphql

![brand-graphql](https://user-images.githubusercontent.com/1282324/203656510-9261af17-a379-494c-ad7c-3e0ecf65bee4.png)
