### ISSUE TITLE
[Icon request] Symfony brand

### ISSUE THREAD

**Issue by garak** [tabler/tabler-icons#394]
See https://symfony.com/what-is-symfony for a general introduction and https://symfony.com/logo for specific information about the logo.

**Comment by proyb6** [comment]
From the current symfony look, it could a problem to scale down to small SVG which could be the reason why some popular brands have simplify their shape so that it will be easier to identify.

**Comment by garak** [comment]
I don't know if this can help (I'm not really an expert in the SVG field), but this is the code used by Symfony itself: https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Icon/symfony.svg

By the way, Symfony uses Tabler icons, as you can see in https://github.com/symfony/symfony/blob/6.3/src/Symfony/Bundle/WebProfilerBundle/Resources/views/Icon/LICENSE.txt

**Comment by codecalm** [comment]
I've added Symfony icon :) https://tabler-icons.io/i/brand-symfony 

![brand-symfony](https://user-images.githubusercontent.com/1282324/205493251-7afec538-273b-447f-ae60-89a9e1403f86.png)

**Comment by garak** [comment]
Thank you!
