### ISSUE TITLE
[Language] Chinese and A character

### ISSUE THREAD

**Issue by proyb6** [tabler/tabler-icons#396]
Suggest adding Chinese and A character.

Hero Icon
```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 21l5.25-11.25L21 21m-9-3h7.5M3 5.621a48.474 48.474 0 016-.371m0 0c1.12 0 2.233.038 3.334.114M9 5.25V3m3.334 2.364C11.176 10.658 7.69 15.08 3 17.502m9.334-12.138c.896.061 1.785.147 2.666.257m-4.589 8.495a18.023 18.023 0 01-3.827-5.802" />
</svg>
```

**Comment by codecalm** [comment]
@proyb6 it already exists: https://tabler-icons.io/i/language

![language](https://user-images.githubusercontent.com/1282324/205344083-f64f527e-b147-4a53-b3a6-33f0a407f4c1.png)

**Comment by proyb6** [comment]
I see,

丈 mean height 

The stroke on top is in the center.
https://fontawesome.com/icons/language?s=thin&f=classic
