### ISSUE TITLE
[Icon Request] Public/Private icon pair

### ISSUE THREAD

**Issue by rickghome** [tabler/tabler-icons#399]
Thanks again for this fantastic icon set!  Would you please consider adding a pair of icons representing public/private status? Lock/unlock, share/don't share don't quite capture this concept. 

proszę i dziękuję

**Comment by BG-Software-BG** [comment]
Maybe https://tabler.io/icons/icon/eye and https://tabler.io/icons/icon/eye-off can be used fot that?
