### ISSUE TITLE
Incorrect view in in vector editing programs

### ISSUE THREAD

**Issue by itsgrafik** [tabler/tabler-icons#4]
As a designer, I intend to use the icons as I quite like the style. But they are inaccurately rendered in pretty much any software I opened them with (Adobe Illustrator, Sketch, even IconJar).

**Comment by codecalm** [comment]
thank you for issue, I'll check it

**Comment by codecalm** [comment]
@itsgrafik I fixed all icons, can you try now?

**Comment by itsgrafik** [comment]
Sure. I imported the entire set into IconJar, and they all look good. I also opened a bunch of random icons across Illustrator, Sketch, Figma... no issues. Thank you for the quick fix.
