### ISSUE TITLE
Icons request

### ISSUE THREAD

**Issue by pixexid** [tabler/tabler-icons#402]
Hi, beautiful icons. 
It's possible to add:
Portrait Image format 2:3
Landscape Image format 3:2
360 panorama image #

**Comment by codecalm** [comment]
you can use https://tabler-icons.io/i/360-view or https://tabler-icons.io/i/panorama-horizontal for panorama
vertical panorama is also available: https://tabler-icons.io/i/panorama-vertical

**Comment by pixexid** [comment]
Great thanks, I pretend to use the icons for a filter, where user can click to display, square images (I can use the image icon), portrait images, landscape images, also I share full 360 images. (I can use your recommendation)

**Comment by peleteiro** [comment]
+1 for Portrait and Landscape

Like:

<img width="72" alt="image" src="https://user-images.githubusercontent.com/822/220368831-eca52cb7-5678-4f9d-9aee-c4e8c5a283b6.png">

and

<img width="66" alt="image" src="https://user-images.githubusercontent.com/822/220368903-e042adaf-a986-434b-b5e2-96414b84d123.png">

**Comment by codecalm** [comment]
https://tabler-icons.io/i/rectangle-vertical
https://tabler-icons.io/i/rectangle :)

**Comment by pixexid** [comment]
Thank's

**Comment by peleteiro** [comment]
Thank you!!!
