### ISSUE TITLE
font-folder missing in current (v1.115.0) release

### ISSUE THREAD

**Issue by kozi** [tabler/tabler-icons#403]
Missing folder `node_modules\@tabler\icons\iconfont\fonts`

In the previous release (**v1.114.0**) the folder exists.

**Comment by sp1tz** [comment]
Yeah, this is still an issue in `1.116.0`. This is a breaking change. FWIW, I pull in the icons via a CDN, and was just grabbing the latest version. Surely I'm not the only one. I had to revert to explicitly fetch `1.114.0`, in order to restore.

**Comment by codecalm** [comment]
yes, sure. Font is not generated properly

**Comment by codecalm** [comment]
I've created v1.116.1 release with fix :) no everything should be okay :)

**Comment by sp1tz** [comment]
Confirmed. Thanks for the quick fix.
