### ISSUE TITLE
[Icon Request] Udemy

### ISSUE THREAD

**Issue by mikajed** [tabler/tabler-icons#405]
Hello there, first of all I want to thank you for this awesome project! 

And second I wanted to ask if it would be possible to add the Udemy logo?

Greetings and thanks again!

// Edit: you can ignore this request, I found the "school" icon on your website and it fits the best now.

**Comment by codecalm** [comment]
Udemy logo is a good icon to do

**Comment by mikajed** [comment]
> Udemy logo is a good icon to do

Oh thanks :)
