### ISSUE TITLE
Discord icon update

### ISSUE THREAD

**Issue by SamKingDev** [tabler/tabler-icons#407]
Discord have changed their icon since it was added to tabler which now makes tabler out of date.

Not sure if you want to update but it would be greatly appreciated if you could.

Tabler Icon
![image](https://user-images.githubusercontent.com/22797936/207445999-387fbfa7-0b34-4f71-8b55-d129d37adaaf.png)

Old vs New discord layout

![image](https://user-images.githubusercontent.com/22797936/207446055-ae17e234-80bc-4bc6-9471-5609f8311c2e.png)

**Comment by codecalm** [comment]
thank you, I'll fix it :)

**Comment by itzTheMeow** [comment]
@codecalm is there a status on this

**Comment by codecalm** [comment]
done! :)
