### ISSUE TITLE
box-seam and package icons look the same; also, open-box icon?

### ISSUE THREAD

**Issue by mholt** [tabler/tabler-icons#417]
Icons [f561](https://tabler-icons.io/i/box-seam) and [eaff](https://tabler-icons.io/i/package) look identical to me. Not sure if that was intentional, just wanted to point that out :)

Also, could we get an icon of an open box/package?

Thanks for Tabler, loving all it has to offer!

**Comment by codecalm** [comment]
yeah, there are already so many of these icons that sometimes I can't remember which one is made and which is not 😂

**Comment by BG-Software-BG** [comment]
[box-seam](https://tabler.io/icons/icon/box-seam) icon will be removed in v3.

**Comment by BG-Software-BG** [comment]
box-seam icon has been removed in v3. [package](https://tabler.io/icons/icon/package) icon should be used.
