### ISSUE TITLE
Add transport control icons

### ISSUE THREAD

**Issue by jrlanglois** [tabler/tabler-icons#42]
Pretty standard emojis/icons used in many things.

- 🔀 Shuffle Tracks Button
- 🔁 Repeat Button
- 🔂 Repeat Single Button
- ▶ Play Button
- ⏩ Fast-Forward Button
- ⏭ Next Track Button
- ⏯ Play or Pause Button
- ◀ Reverse Button
- ⏪ Fast Reverse Button
- ⏮ Last Track Button
- 🔼 Upwards Button
- ⏫ Fast Up Button
- 🔽 Downwards Button
- ⏬ Fast Down Button
- ⏸ Pause Button
- ⏹ Stop Button
- ⏺ Record Button
- ⏏ Eject Button

**Comment by codecalm** [comment]
@jrlanglois :)

![Screenshot 2020-09-03 at 23 28 16](https://user-images.githubusercontent.com/1282324/92175625-3c482c00-ee3d-11ea-848d-71563cc6558f.png)
