### ISSUE TITLE
Right tabler icon

### ISSUE THREAD

**Issue by 0xflotus** [tabler/tabler-icons#426]
If I search for the `brand-tabler` in the iconset, I found this:

<img width="613" alt="Bildschirmfoto 2023-01-04 um 14 18 28" src="https://user-images.githubusercontent.com/26602940/210563781-894360bb-213b-4b35-b531-05ba78535954.png">

But this differs to the icon in the header:

<img width="210" alt="Bildschirmfoto 2023-01-04 um 14 18 33" src="https://user-images.githubusercontent.com/26602940/210563840-989a1ae0-1b53-4d6f-be22-7c105a2ae86b.png">

Is this correct? Or is it a different icon for Tabler Icons?

**Comment by codecalm** [comment]
command line it's official tabler logo, the pen is logo of tabler-icons
