### ISSUE TITLE
[Icon Request] coin-hryvnia

### ISSUE THREAD

**Issue by 0xflotus** [tabler/tabler-icons#431]
In the icon set are some coin icons like `coin-euro` and `coin-pound`. 
Please add also `coin-hryvnia`. 

Hryvnia is the currency of the Ukraine.

**Comment by codecalm** [comment]
https://tabler-icons.io/i/currency-hryvnia already exists

**Comment by 0xflotus** [comment]
Yeah, but there is also a https://tabler-icons.io/i/coin-euro and a https://tabler-icons.io/i/currency-euro, so there is a https://tabler-icons.io/i/currency-hryvnia but no `coin-hryvnia`

**Comment by codecalm** [comment]
in coins are most popular currencies in the world, hryvnia unfortunately is not so popular

as a second argument its impossible to representant hryvnia in 10x10px circle
