### ISSUE TITLE
[Icon Request] rust-brand

### ISSUE THREAD

**Issue by 0xflotus** [tabler/tabler-icons#437]
Please add an icon for the [rust programming language](https://www.rust-lang.org/).

<img width="81" alt="Bildschirmfoto 2023-01-04 um 15 26 31" src="https://user-images.githubusercontent.com/26602940/210576475-679f2ec3-3f87-481e-a524-9e5509fe63fd.png">

**Comment by paralin** [comment]
Brand icons like this one are the main thing I need to switch fully from fortawesome! Thanks :)

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
