### ISSUE TITLE
Request: More brand icons

### ISSUE THREAD

**Issue by jrlanglois** [tabler/tabler-icons#44]
Few more suggestions:
- YouTube
- Twitch
- Firefox
- Tumblr
- DeviantArt
- Reddit
- SoundCloud
- LinkedIn
- Microsoft
- Windows
- WhatsApp
  - See Issue https://github.com/tabler/tabler-icons/issues/47
- Steam
  - See Issue https://github.com/tabler/tabler-icons/issues/33
- Messenger
  - See Issue https://github.com/tabler/tabler-icons/issues/53
- Mozilla
- Edge
- Internet Explorer
- Discord

Issues that are related:
- https://github.com/tabler/tabler-icons/issues/19

**Comment by codecalm** [comment]
WhatsApp, Messenger icons will be added with next release! :)

**Comment by reini-1** [comment]
- Mozilla

**Comment by lukjak** [comment]
- Python programming language

**Comment by codecalm** [comment]
done :) 

![tabler-icons-1 23 0](https://user-images.githubusercontent.com/1282324/93829602-4a37e280-fc6e-11ea-92bd-68cdce94e51f.png)
