### ISSUE TITLE
How can i use tablericons in my react project?

### ISSUE THREAD

**Issue by candrescastel** [tabler/tabler-icons#45]
I already installed but how can i use it?

**Comment by ivanov-v** [comment]
@candrescastel Hi. https://github.com/tabler/tabler-icons#usage

**Comment by candrescastel** [comment]
Hi thanks for your response, but what I need is to reference the icons from node_modules to my component. Could you help me? I'm new to react :)

**Comment by CrispyBacon1999** [comment]
I made a small component that does the job pretty well using the icon font.

```jsx
import React from "react";
import "tabler-icons/iconfont/tabler-icons.min.css";

export function Icon(props) {
  const classList = "ti ti-" + props.children;
  return <i className={classList}></i>;
}
```

Usage:
```jsx
<Icon>brand-github</Icon>
```

**Comment by FreexD** [comment]
@candrescastel `tabler-icons` just shipped wrappers for it's SVGs in React (with type declarations for Typescript) - check out https://github.com/tabler/tabler-icons#react for usage reference. We'll be adding even more usage examples soon! :)
