### ISSUE TITLE
[Icon Request] More icons representing file extensions

### ISSUE THREAD

**Issue by deme3** [tabler/tabler-icons#459]
Extensions icons like the already present BMP, PNG, SVG, JPG, GIF, ZIP, TXT, TeX:

* CSV
* PDF
* JSON
* SQL

**Comment by 0xflotus** [comment]
`csv` was added in [v2.5.0](https://github.com/tabler/tabler-icons/releases/tag/v2.5.0)

**Comment by 0xflotus** [comment]
`pdf` was added in [v2.6.0](https://github.com/tabler/tabler-icons/releases/tag/v2.6.0)

**Comment by BG-Software-BG** [comment]
[JSON](https://tabler.io/icons/icon/json) and [SQL](https://tabler.io/icons/icon/sql) added in v2.7
