### ISSUE TITLE
Icon request for different exercise activities

### ISSUE THREAD

**Issue by Ramarc** [tabler/tabler-icons#46]
The bike and some sports icons are great. Please consider adding more icons for exercise like walking, running, swimming, hiking, etc. Fantastic icons, keep up the great work!

**Comment by codecalm** [comment]
@Ramarc how about that?

<img width="605" alt="Screenshot 2020-08-19 at 23 56 03" src="https://user-images.githubusercontent.com/1282324/90693705-95c62d80-e277-11ea-8239-a021151e4301.png">

**Comment by Ramarc** [comment]
Those look awesome! Thank you!
