### ISSUE TITLE
Release 2.0.0 not working anymore in NextJS

### ISSUE THREAD

**Issue by gfazioli** [tabler/tabler-icons#464]
Hello, 
I tried to updated the `@tabler/icon` packages from `1.119.0` to `2.0.0`
After that, my NextJS app stopped to working fine, I got something like below
<img width="943" alt="image" src="https://user-images.githubusercontent.com/432181/214271924-53c48f4a-e2b0-4498-b164-af3e28dab9c6.png">

in short, the SVG text instead of the icon.

In addition to that, I got an issue on `size` props as well
<img width="625" alt="image" src="https://user-images.githubusercontent.com/432181/214272671-94633213-f06f-40d9-8529-ec7e0c836630.png">

<img width="961" alt="image" src="https://user-images.githubusercontent.com/432181/214272738-8a1ccde8-9baf-45ec-9053-8b5e569bc3b3.png">

JFYI, I'm using 

```
dependencies:
@emotion/react 11.10.5         @mantine/form 5.10.1           @mantine/prism 5.10.1          cookies-next 2.1.1             mantine-datatable 1.7.35       react-dom 18.2.0
@emotion/server 11.10.0        @mantine/hooks 5.10.1          @mantine/spotlight 5.10.1      dayjs 1.11.7                   md5 2.3.0                      react-fast-compare 3.2.0
@mantine/carousel 5.10.1       @mantine/modals 5.10.1         @mantine/utils 5.10.1          embla-carousel-autoplay 7.0.9  next 12.3.1                    recharts 2.3.2
@mantine/core 5.10.1           @mantine/next 5.10.1           @react-pdf/renderer 3.0.2      embla-carousel-react 7.0.9     next-auth 4.15.1               sharp 0.31.2
@mantine/dates 5.10.1          @mantine/notifications 5.10.1  @tabler/icons 2.0.0            framer-motion 7.10.0           next-pwa 5.6.0                 swr 1.3.0
@mantine/dropzone 5.10.1       @mantine/nprogress 5.10.1      axios 1.1.3                    http-proxy 1.18.1              react 18.2.0

devDependencies:
@types/http-proxy 1.17.9
@types/md5 2.3.2
@types/node 18.7.16
@types/react 18.0.21
@types/react-dom 18.0.6
eslint 8.32.0
eslint-config-next 12.3.1
prettier 2.8.3
typescript 4.8.4
```

Any clue or suggestions?

Thx

**Comment by codecalm** [comment]
in version 2.0 you should use `@tabler/icons-react` package :)

**Comment by gfazioli** [comment]
@codecalm ohoh, thank you, trying 👍

**Comment by codecalm** [comment]
@gfazioli is everything okay?

**Comment by adamdrake210** [comment]
> in version 2.0 you should use `@tabler/icons-react` package :)

Maybe the docs could be updated. On github it is showing this:
<img width="869" alt="image" src="https://user-images.githubusercontent.com/6083945/214887773-5a687859-107c-4059-b67f-3f10be66ff16.png">
Import is still from '@tabler/icons'

**Comment by codecalm** [comment]
done
