### ISSUE TITLE
Issues with peer dependencies found, missing peer prop-types@^15.7.2

### ISSUE THREAD

**Issue by fahmiidris-labs** [tabler/tabler-icons#465]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/85909352/214501462-cdcf4a92-64b2-419f-9a6d-eca9ea7dbffd.png">

I want to install tabler icons for react using pnpm, but I get this warning.

**Comment by codecalm** [comment]
should be fixed in `2.1.0` :)
