### ISSUE TITLE
error for render in react, what am I doing wrong

### ISSUE THREAD

**Issue by AiorNerok** [tabler/tabler-icons#466]
![image](https://user-images.githubusercontent.com/90855034/214511093-4427e5a0-41ae-4e07-b090-8ba614e60cad.png)
![image](https://user-images.githubusercontent.com/90855034/214511173-a0621df0-289d-41ad-be14-c444d997a922.png)
![image](https://user-images.githubusercontent.com/90855034/214511413-0485fcf6-c47b-4c94-b939-8c6ae393660e.png)

![image](https://user-images.githubusercontent.com/90855034/214511627-a69974f4-afb0-4eba-ba39-8e39a1489241.png)

**Comment by codecalm** [comment]
in v2 you should use @tabler/icons-react package :)

**Comment by AiorNerok** [comment]
thx
