### ISSUE TITLE
`@tabler/icons-react` Stroke prop no longer works after 2.0 update

### ISSUE THREAD

**Issue by rtivital** [tabler/tabler-icons#467]
After update to 2.0, `stroke` prop no longer works:

1. Types do not include explicit `stroke` prop anymore – it can only be string (native svg element props)

```tsx
export interface TablerIconsProps extends Partial<React.SVGProps<SVGSVGElement>> {
    size?: string | number
    // stroke is missing
}
```

2. `stroke` prop does not work even if set as string:

```tsx
// Will show ts error
<IconCalendar size={14} stroke={1.5} />

// Icon will not be visible
<IconCalendar size={14} stroke="1.5px" />
```

**Comment by codecalm** [comment]
@rtivital I've unified props of Icon component with SVG props, so you should `strokeWidth` property instead of `stroke`. 

although now I'm thinking of creating a `stroke` prop to make it more compatible with v1 🤔

**Comment by codecalm** [comment]
yeah, you're right. I'll add `stroke` props to maintain backward compatibility. I'll release `2.0.1` soon

**Comment by rtivital** [comment]
Sounds great, thanks!

**Comment by codecalm** [comment]
@rtivital I've create PR for this change: https://github.com/tabler/tabler-icons/pull/470

**Comment by codecalm** [comment]
@rtivital in `v2.1.0` everything should be fixed :)

**Comment by dchest** [comment]
Unfortunately, now there's a confusing between SVG props `stroke` (which is color) and tabler stroke. I thought v2 made this breaking change intentionally to be compatible with SVG props.
