### ISSUE TITLE
Icon position and size changed with version 2

### ISSUE THREAD

**Issue by martinrademacher** [tabler/tabler-icons#473]
I'm using the tabler webfont (ttf) in an app.
Since I updated to version 2.1.2 the icon sizes and position changed. Is this something I can change or how could this happen? 

old Version
![image](https://user-images.githubusercontent.com/5676050/215078337-6587a546-7209-4989-b8cc-6c688e1d4a71.png)

new
![image](https://user-images.githubusercontent.com/5676050/215083531-13da74ba-4ca4-441d-a532-0b88f0baeeaf.png)

**Comment by codecalm** [comment]
it's definetly bug, I'll check it

**Comment by macCesar** [comment]
Just noticed the same thing!

I hope it can be fixed!

**Comment by rickghome** [comment]
I'm seeing the same thing, and it's really impacted my layout. I'm going back to version 1.x until we find a solution.  Fiddling with styles doesn't seem to correct the issue.

**Comment by DrkAlien** [comment]
I did update my entire project, the icons indeed have a way smaller size and they simply do not fit anymore. Looking forward to see them fixed. Thanks.

**Comment by codecalm** [comment]
I've fixed it, should be better in next release! :)
