### ISSUE TITLE
[Feature Request] Icon spin property

### ISSUE THREAD

**Issue by nonam4** [tabler/tabler-icons#474]
Would be nice to have a native prop for making some icons spin  like a loading indicator.

As I'm using React I'll use it as an example:

```
import { IconLoader2 } from '@tabler/icons-react'

return (
   ....
   < IconLoader2
       size={24}
       spin // or maybe spin={ true }
   /> 
   ....
)
```

This will make the icon spin indefinitely

**Comment by codecalm** [comment]
Hi Luiz, unfortunately Tabler Icons provide only SVG files, without any CSS and it's impossible to animate icons without CSS :(
