### ISSUE TITLE
[Request] Icon representing counting or a specific count of X

### ISSUE THREAD

**Issue by nicovoehringer** [tabler/tabler-icons#48]
An icon that represents counting up or down or the number/count of something would be a good addition to the existing catalogue of icons.
I suggest as an icon [tally marks](https://en.wikipedia.org/wiki/Tally_marks) with four vertical strokes and one diagonal stroke. These are quite easy to create and represent counting in many parts of the world.

**Comment by anserwaseem** [comment]
@nicovoehringer would it be a GIF or an icon, if the counting up/down feature is implemented?

**Comment by nicovoehringer** [comment]
@anserwaseem My first thought was a single static icon that shows tally marks with four vertical and one diagonal strokes.
Basically exactly the same as [this image](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Tally_marks-Five-bar_Gate.svg/1160px-Tally_marks-Five-bar_Gate.svg.png) shows, only of course in the style of the icon pack.

To better represent the act of counting, I find that several static icons, rather than a dynamic GIF, fit better into the design of the already present icons. It shouldn’t be a problem to convert the mentioned tally marks for one to four also into static icons.
And if you want to display "counting" dynamically in a project, you can animate the five static icons.

The only question is whether it is necessary to add all five icons. Or whether a single one (with five strokes) fits better into the whole pack. Then you do not have the option to show the counting dynamically, but the selection in the icon pack is not so overloaded/bloated.

**Comment by anserwaseem** [comment]
@nicovoehringer Yes, you are right. I think five different static icons showing tally marks, from the count of 1 to 5 will be more useful especially when displaying using animation/s.

**Comment by codecalm** [comment]
how about that?

![Screenshot 2020-08-04 at 23 04 45](https://user-images.githubusercontent.com/1282324/89344896-e7cb5880-d6a6-11ea-8a1f-b83c296a63cc.png)

**Comment by nicovoehringer** [comment]
Yeah. This is how I imagined it.
That concludes the issue for me. Thanks.
