### ISSUE TITLE
@tabler/icons in react displaying as svg code instead of the icon image.

### ISSUE THREAD

**Issue by kitavidavis** [tabler/tabler-icons#486]
I have been working well with @tabler/icons until recently when I discovered that any icon does not render as it used to be. Instead of rendering the image graphic(from the svg code), it renders the svg code.

**Comment by bardsol** [comment]
This has all ready been answered here:
https://github.com/tabler/tabler-icons/issues/464#issuecomment-1401729431

**Comment by kitavidavis** [comment]
Thank you @bardsol
