### ISSUE TITLE
[Icon Request] Golang logo

### ISSUE THREAD

**Issue by DamascenoV** [tabler/tabler-icons#487]
Please add an icon for Golang.
[https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg](url)

**Comment by kicaj** [comment]
@DamascenoV Something is incorrect in your link

**Comment by DamascenoV** [comment]
@kicaj Sorry, here is the link:
[link](https://raw.githubusercontent.com/devicons/devicon/master/icons/go/go-original-wordmark.svg)

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.5.0 :)
