### ISSUE TITLE
[Feature Request] allow group icons

### ISSUE THREAD

**Issue by 94noni** [tabler/tabler-icons#488]
Hi,

First thx for such icons sets.

Just creating an issue to see if [such feature ](https://semantic-ui.com/elements/icon.html#/definition) (see `Groups` on the page) can be added to this library.

Feel free to close the issue if you found this irrelevant,

Many thanks cheers!

**Comment by MrAmericanMike** [comment]
Nice idea. I guess also, it could be achieved with just a bit of css, but been a feature would be really handy.

For example, no svelte I did this and it works:

```html
<span>
	<IconRobot class="ontop" size={42} stroke={1.25} />
	<IconHeart class="ontop" size={42} stroke={1.25} />
</span>

<style>
	span {
		position: relative;
		width: 42px;
		height: 42px;
	}
	:global(.ontop) {
		position: absolute;
	}
</style>
```

But yes having support for Groups and Corner Icons out of the box sounds interesting.
