### ISSUE TITLE
[DOCS FIX] Outdated icon example in the 'How to use' section on the README

### ISSUE THREAD

**Issue by gabrielforster** [tabler/tabler-icons#489]
The Icon example is using a different prop from the prop list table. It can be found [here](https://github.com/tabler/tabler-icons/blob/3eddd63c33b7171d334186c8829fdc36efaa348c/packages/icons-svelte/README.md?plain=1#L65)

The actual prop is **stroke**, and the example is using **strokeWidth**

**Comment by MrAmericanMike** [comment]
Ohh I just created 2 PRs related to fixing that also.

https://github.com/tabler/tabler-icons/pull/490
https://github.com/tabler/tabler-icons/pull/491

I believe those example did match the other library that had support for Svelte, but now it's moved into this main project.

**Comment by gabrielforster** [comment]
That's awesome! Thanks!
