### ISSUE TITLE
[Bug] IconInfoCircleFilled throws an error in browser console `Wrong property "stroke-width"`

### ISSUE THREAD

**Issue by Lukasz-pluszczewski** [tabler/tabler-icons#492]
When using IconInfoCircleFilled in Chrome, while icon do show up correctly it seems, Chrome shows the error in console:
```
Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
```

Here is the example code to reproduce the issue: https://stackblitz.com/edit/vitejs-vite-oa3nlq?file=src/App.tsx

EDIT: I've verified the issue only in `@tabler/icons-react` not sure if the stroke-width is also used in that icon in other packages.

**Comment by codecalm** [comment]
yeah, in nevest version I've started use `stroke-width` in path, it's bug. I'll fix it soon! :)

**Comment by codecalm** [comment]
I've fixed it, I'll release it soon! :) thank you @Lukasz-pluszczewski for issue
