### ISSUE TITLE
[Icon Request] List tree

### ISSUE THREAD

**Issue by kicaj** [tabler/tabler-icons#497]
We have list icons like:
- "list"
- "menu-2"

but there is no any icon list tree, like:
- "list-tree": 
![image](https://user-images.githubusercontent.com/3750725/217078150-df8c8598-c33d-4ca6-a69a-1c2f9be363b5.png)
- "menu-deep": 
![image](https://user-images.githubusercontent.com/3750725/217078507-60ea8055-8ef4-45f9-92db-b9520c6c671c.png)

BTW icon "menu-2" may also had tag "list"

**Comment by kicaj** [comment]
```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-list-tree" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M9 6l11 0"/>
  <path d="M12 12l8 0"/>
  <path d="M15 18l5 0"/>
  <path d="M5 6l0 .01"/>
  <path d="M8 12l0 .01"/>
  <path d="M11 18l0 .01"/>
</svg>
```
and
```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-menu-deep" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M4 6l16 0"/>
  <path d="M7 12l13 0"/>
  <path d="M10 18l10 0"/>
</svg>
```

**Comment by ilyasmez** [comment]
I also need a tree structure/list icon.

The icons above look more like "left aligned text/list", I think we need a line between the item to make it look more like a tree.

Examples:
<img src="https://www.iconbolt.com/iconsets/clarity-solid/tree-view.svg" width="64" />
<img src="https://usefulicons.com/uploads/icons/202004/2710/ff7a4ed4b50f.png" width="64" />

@codecalm could you please look into this? 🙏

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.24.0 🙂 

![](https://github.com/tabler/tabler-icons/assets/1282324/9364cd66-3445-4631-8b13-5de6160828df)
