### ISSUE TITLE
[Icon Request] Wave without arrows

### ISSUE THREAD

**Issue by robertvanhoesel** [tabler/tabler-icons#499]
We have https://tabler-icons.io/i/arrow-wave-left-down and other variations which are great for indication a trend direction. I'd love the same wave without arrow heads to indicate 'normal' / unchanged trendlines.

**Comment by codecalm** [comment]
how about tilde: https://tabler-icons.io/i/tilde ?

**Comment by robertvanhoesel** [comment]
Perfect, I couldn't find that one yet!
