### ISSUE TITLE
[Icon Request] Share icon

### ISSUE THREAD

**Issue by 1aron** [tabler/tabler-icons#505]
I can always find the Icon I want in Tabler, but I don’t get the expected results when searching for the "share" Icon 😂

<img width="945" alt="Screenshot 2023-02-09 at 8 34 21 PM" src="https://user-images.githubusercontent.com/33840671/217814265-d6c2b226-392c-4133-9c0b-1d852b2a8ec6.png">

Apple share icon

![image](https://user-images.githubusercontent.com/33840671/217814236-f6fcdd33-ed1b-4693-bd95-55f70c40e892.png)

**Comment by 1aron** [comment]
> I believe there is share icon https://tabler-icons.io/i/share

Oops! I'm spoiled by Apple.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.5.0 :)
