### ISSUE TITLE
[Icon Request] Up/Down Arrows/Chevrons

### ISSUE THREAD

**Issue by piotrkulpinski** [tabler/tabler-icons#506]
That would be very useful for custom select inputs and all kinds of switchers.
<img width="55" alt="CleanShot 2023-02-10 at 09 15 16" src="https://user-images.githubusercontent.com/358412/218038288-d75a85ee-9f61-483c-85b4-8da591b1db3d.png">

**Comment by codewithkyle** [comment]
How would this be different than the existing [Selector](https://tabler-icons.io/i/selector) icon?

**Comment by piotrkulpinski** [comment]
Sorry! Couldn't find it anywhere. That's exactly what I meant, thanks.
