### ISSUE TITLE
Icon has wrong width

### ISSUE THREAD

**Issue by JohnAxae** [tabler/tabler-icons#507]
I changed icons from svg to the latest webfont (2.3.0) and I see that the width of the icons is wrong, it makes it look a little out of place. 
Tested this in chromium-based browsers (chrome, brave, edge) and in firefox with same results.

How it looks now:
![image](https://user-images.githubusercontent.com/4102398/218407311-4381c8e2-559b-4079-9f1b-68d74fa01b00.png)
![image](https://user-images.githubusercontent.com/4102398/218407392-c9cb4113-66dd-4b21-ab27-51ce8859fc78.png)

How it should look:
![image](https://user-images.githubusercontent.com/4102398/218409329-94fdc140-35c5-4a4f-930c-bc9c9a1dbd24.png)

**Comment by kicaj** [comment]
I confirm also.

**Comment by wen-gang** [comment]
<img width="261" alt="QQ20230214-101952@2x" src="https://user-images.githubusercontent.com/24801605/218622155-de2fb3b4-7eda-4059-84b7-a4c18de4f915.png">
The same problem.

**Comment by spburden** [comment]
Same problem!

**Comment by idcom-jakub-soboczynski** [comment]
Yes I have same problem 😥

**Comment by idcom-jakub-soboczynski** [comment]
@codecalm any updates?

**Comment by timbogdanov** [comment]
same problem! please fix!

**Comment by codecalm** [comment]
@idcom-jakub-soboczynski I'm working on it :)

**Comment by codecalm** [comment]
@JohnAxae, @kicaj, @wen-gang, @timbogdanov, @idcom-jakub-soboczynski, @spburden I found problem! :)

I'll release next version it in one hour

**Comment by codecalm** [comment]
released in 2.5.0 - now all icons has perfect width :)

![Screenshot 2023-02-23 at 01 12 34](https://user-images.githubusercontent.com/1282324/220793120-fc1e0754-64ae-49a3-bc74-7eee145dd287.png)

**Comment by kicaj** [comment]
I confirm, thanks!

**Comment by wen-gang** [comment]
Thanks!

**Comment by timbogdanov** [comment]
Thank you! @codecalm
