### ISSUE TITLE
[Icon Request] `signal-2g` Icon

### ISSUE THREAD

**Issue by 0xflotus** [tabler/tabler-icons#509]
Please consider to add a `signal-2g` Icon to the tabler icon set. While there is a `signal-3g`, `signal-4g` and `signal-5g` currently in the set and many many smartphones currently support the 2G standard, it would be very helpful for some apps, to use this icon to show some low bitrate connections

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.5.0 :)
