### ISSUE TITLE
Gatsby problem 

### ISSUE THREAD

**Issue by mouayed-keziz** [tabler/tabler-icons#511]
so im using gatsby js with mantine ui, after installing tabler-icons, i tried running the local development server and it didnt work (there is an issues with the package ive added (tabler-icons), and when i remove it everything goes ok as it was,

this was the error from the terminal
` ERROR  UNKNOWN

Module not found: Error: Package path . is not exported from package C:\Users\mouayed\Desktop\my-gatsby-site\node_modules\@tabler\icons (see  
exports field in C:\Users\mouayed\Desktop\my-gatsby-site\node_modules\@tabler\icons\package.json)

  ModuleNotFoundError: Module not found: Error: Package path . is not exported from package C:\Users\mouayed\Desktop\my-gatsby-site\node_modul  es\@tabler\icons (see exports field in C:\Users\mouayed\Desktop\my-gatsby-site\node_modules\@tabler\icons\package.json)

  - Compilation.js:2016 
    [my-gatsby-site]/[webpack]/lib/Compilation.js:2016:28

  - NormalModuleFactory.js:798 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:798:13

  - NormalModuleFactory.js:270 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:270:22

  - NormalModuleFactory.js:434 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:434:22

  - NormalModuleFactory.js:116 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:116:11

  - NormalModuleFactory.js:670 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:670:25

  - NormalModuleFactory.js:855 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:855:8

  - NormalModuleFactory.js:975 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:975:5

  - async.js:6883 
    [my-gatsby-site]/[neo-async]/async.js:6883:13

  - NormalModuleFactory.js:958 
    [my-gatsby-site]/[webpack]/lib/NormalModuleFactory.js:958:45

  - Resolver.js:312 finishWithoutResolve
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:312:11

  - Resolver.js:386 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:386:15

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - DescriptionFilePlugin.js:87 
    [my-gatsby-site]/[enhanced-resolve]/lib/DescriptionFilePlugin.js:87:43

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - DescriptionFilePlugin.js:87 
    [my-gatsby-site]/[enhanced-resolve]/lib/DescriptionFilePlugin.js:87:43

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - Resolver.js:435 
    [my-gatsby-site]/[enhanced-resolve]/lib/Resolver.js:435:5

  - DirectoryExistsPlugin.js:41 
    [my-gatsby-site]/[enhanced-resolve]/lib/DirectoryExistsPlugin.js:41:15

  - task_queues:81 processTicksAndRejections
    node:internal/process/task_queues:81:21

not finished Building development bundle - 34.154s`

**Comment by kicaj** [comment]
Show file where you are loading tabler-icons.

**Comment by wnederhof** [comment]
Can confirm with Next.js. Not sure what has changed, but downgrading to 2.2.0 fixes the issue.

**Comment by codecalm** [comment]
@SyntaxJoker look at this please

**Comment by SyntaxJoker** [comment]
This error can occur if you have something wrong in icon import
in case of gatsby you can use `@tabler/icons-react` package and import icon like in the docs example:
https://tabler.io/docs/icons/react
