### ISSUE TITLE
FR: Tabler site - copy icons as symbol

### ISSUE THREAD

**Issue by yoyurec** [tabler/tabler-icons#516]
![image](https://user-images.githubusercontent.com/137919/219530095-70bd7706-bf84-4505-84c6-546541f97068.png)

Add the possibility copy HTML char, not just hex code / class name / SVG:
`&#x[HEX-HERE];`

**Comment by codecalm** [comment]
done! ❤️ 

thank you for idea! :)

**Comment by yoyurec** [comment]
awesome!

**Comment by yoyurec** [comment]
hm... good, but not perfect....

Nerd fonts doing coping not just code, bur "real symbol/glyoh" https://www.nerdfonts.com/cheat-sheet via pseudoelement `content: "\xxxx"` value

```js
...
        textToCopy = window
          .getComputedStyle(document.querySelector(`.${parent.parentNode.querySelector('.class-name').innerText}`), ':before')
          .getPropertyValue('content')
          .replace(/"/g, '');
...
```
![image](https://user-images.githubusercontent.com/137919/220911585-c18d26bb-16a1-4940-ace7-677a92ec3f39.png)

would be better to add tag `i.ti.ti-[name]` with icon and its CSS... so it will have `content` from which JS can copy "symbol"

is there repo for Tabler site, so i can create PR? )

BTW, `content `value needs leading backslash `\`
![image](https://user-images.githubusercontent.com/137919/220915745-714834d0-f9f5-4f81-95ba-b23b8bdcc194.png)
