### ISSUE TITLE
'Failed to resolve entry for package "@tabler/icons". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "@tabler/icons"  package

### ISSUE THREAD

**Issue by AdamJSoftware** [tabler/tabler-icons#519]
I seem to have this issue when using vite-react-swc.

No matter what I do, I cannot start my vite site because I keep getting this error. And it seems to only be an issue with this package.

**Comment by kevinschaich** [comment]
If you're using react:

```bash
yarn remove @tabler/icons
yarn add @tabler/icons-react
```

Usage:

```typescript
import { Icon24Hours } from '@tabler/icons-react';
```

**Comment by codecalm** [comment]
@AdamJSoftware in v2 React version of Tabler Icons has been moved to `@tabler/icons-react` package :)
