### ISSUE TITLE
Web fonts are having a width issue starting v2.3.0 !!!

### ISSUE THREAD

**Issue by artknight** [tabler/tabler-icons#520]
I just upgraded to v2.4.0 and I see all of my icons shifted to the left. It seems v2.4.0 and v2.3.0 have an issue with the actual web fonts!!!

Effected versions --> v2.4.0 and v2.3.0 (Attaching a screenshot.)
<img width="477" alt="tabler-icons-with-v2 4 0" src="https://user-images.githubusercontent.com/157762/219796791-653899c6-d795-442f-81eb-78df4acd4cdf.png">

I noticed that the CSS did not change (other than the addition of new icons), but the web fonts have. So, I started replacing the actual web fonts ( tabler-icons.eot, ttf, etc... ) with prior versions, and they seem good with v2.2.0 (Attaching a screenshot.)
<img width="496" alt="tabler-icons-with-v2 2 0" src="https://user-images.githubusercontent.com/157762/219796826-bc8d8b3e-a6a5-4108-ab15-ab6cfcee7a83.png">

Please fix this at your soonest :)
Art

**Comment by codecalm** [comment]
duplicate #473

**Comment by artknight** [comment]
@codecalm why are you closing this or/and the related ticket .. as this issue is NOT fixed!

**Comment by codecalm** [comment]
don't be rude, this issue are duplicate of https://github.com/tabler/tabler-icons/issues/473

**Comment by artknight** [comment]
@codecalm I apologize if I offended you. Please forgive me for asking but I saw that you had closed the other ticket ([#507](https://github.com/tabler/tabler-icons/issues/507)) and you closed this one, but the issue not yet fixed.
