### ISSUE TITLE
Filled icons are not in the Icon font css

### ISSUE THREAD

**Issue by mauriciabad** [tabler/tabler-icons#528]
Hi, I'm using the CDN, as explained in [this section of the readme](https://github.com/tabler/tabler-icons/tree/44ecd5a89fb642219da3f7262c1d0ce403c4d9c7#iconfont). 

But the filled icons are missing, specifically I'm trying to use [`heart-filled`](https://tabler-icons.io/i/heart-filled).

I performed a search on the `.css`, and the icon is not there.
https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/tabler-icons.min.css

![screenshot](https://user-images.githubusercontent.com/12821361/220802872-d79acb27-6aaf-437c-a193-d9cbbf9e34c5.png)

**Comment by codecalm** [comment]
use @tabler/icons-webfont package

**Comment by muava12** [comment]
how to write code to import this icon font in main.js in vue? sorry basic question i'm a noob
