### ISSUE TITLE
Unable to import @tabler/icons-webfont@2 tabler-icons.css

### ISSUE THREAD

**Issue by mjchang** [tabler/tabler-icons#533]
When importing `@tabler/icons-webfont/tabler-icons.css` fails, I get this error message
```
Field 'browser' doesn't contain a valid alias configuration
/Users/chang/project/node_modules/@tabler/icons-webfont/icons/tabler-icons.css doesn't exist
```

This seems to stem from the fact that @tabler/icons-webfont is remapping the root folder to the `icon` in the `exports` field: https://github.com/tabler/tabler-icons/blob/master/packages/icons-webfont/package.json#L35-L39. If I change my import to `@tabler/icons-webfont/../tabler-icons.css`, it now works.

Is this expected? Is the exports property incorrect? Is the build process not adding the `icons` folder as expected?

**Comment by SyntaxJoker** [comment]
We have couple of  issues with current building process and we will significantly change the way the library is built soon fixing this issue as well

**Comment by codecalm** [comment]
will be fixed in newest package! :)

**Comment by codecalm** [comment]
fixed in https://github.com/tabler/tabler-icons/releases/tag/v2.17.0 🚀
