### ISSUE TITLE
Typescript error: '{ size: number; color: string; }' is not assignable to type 'IntrinsicAttributes'.

### ISSUE THREAD

**Issue by Ridermansb** [tabler/tabler-icons#534]
`tsc` getting errors on property `size`

I'm using npm workspaces with the following structure:

![image](https://user-images.githubusercontent.com/725337/220866046-4475933a-a16d-46b8-af16-58740eb7c52e.png)

In my **root folder**, I have the `package.json` defined as 

```json
// ...
"workspaces": [
    "packages/ui",
    "packages/crawler",
    "packages/functions"
],
"devDependencies": {
    "@types/node": "^18.14.0",
    "@typescript-eslint/eslint-plugin": "^5.53.0",
    "@typescript-eslint/parser": "^5.53.0",
    "eslint": "^8.34.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-import-resolver-typescript": "^3.5.3",
    "eslint-plugin-import": "^2.27.5",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-unicorn": "^45.0.2",
    "typescript": "^4.9.5",
}
```

and then `tsconfig.json`

```json
{
  "compilerOptions": {
    "incremental": true,
    "outDir": "./dist",
    "baseUrl": ".",
    "moduleResolution": "Node",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictNullChecks": true,
    "target": "es2017",
    "composite": true
  },
  "references": [
    {
      "path": "packages/ui"
    },
    {
      "path": "packages/crawler"
    },
    {
      "path": "packages/functions"
    }
  ],
  "exclude": ["node_modules", "dist", "lib", "*.d.ts"]
}
```

On `packages/ui` folder, I have the `tsconfig.json` file as following

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": ".",
    "outDir": "dist",
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": false,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "module": "ES2020",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "strictFunctionTypes": false,
    "target": "ESNext",
    "typeRoots": ["./@types", "../../node_modules/@types", "./src/environment.d.ts"],
    "types": ["react", "react-dom", "vitest/importMeta", "vite/client", "vitest/globals"],
    "useDefineForClassFields": true
  },
  "include": ["src", "src/setup-tests.ts", "src/global.d.ts"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
```

## Error

`npm run build` (same as `"build": "tsc && vite build",`) on  `packages/ui` is getting 

```
TS2322: Type '{ size: number; color: string; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'size' does not exist on type 'IntrinsicAttributes'.

36             <IconCaretDown size={18} color="grey" />
```
![image](https://user-images.githubusercontent.com/725337/220865310-19d9ba08-af51-4873-a3cb-c283f08e9bc0.png)

not sure if is related to the issue https://github.com/tabler/tabler-icons/issues/180 but as you can see, I added `"skipLibCheck": true` on `tsconfig.json` root file

**Comment by fme29** [comment]
hi, i've the same issue using a header in a basic app.
just creat react app with typescript template and copy/paste mantine header example code in app.tsx. all needed modules are correctly installed.
any idea ?

**Comment by fme29** [comment]
solved using @tabler/icons-react, removing @tabler/icons and fixing import in tablers examples.

**Comment by SyntaxJoker** [comment]
Here are the docs:
https://tabler.io/docs/icons/react
pick framework you are using and import icon like in the examples, it should work without errors

**Comment by SergeyKopytov1205** [comment]
add the svg.d.ts file that contains

declare module '*.svg' {
  import React from 'react';
  import {SvgProps} from 'react-native-svg';
  const content: React.FC<SvgProps>;
  export default content;
}
