### ISSUE TITLE
[Icon Request] jQuery

### ISSUE THREAD

**Issue by renbaoshuo** [tabler/tabler-icons#538]
![](https://upload.wikimedia.org/wikipedia/commons/f/fd/JQuery-Logo.svg)

https://commons.wikimedia.org/wiki/File:JQuery-Logo.svg

**Comment by renbaoshuo** [comment]
The icon from simple-icons for reference:

![Snipaste_2023-04-27_07-15-44](https://user-images.githubusercontent.com/47095648/234722329-7cc898d7-0578-4f41-8ef7-f477f50b3d34.png)


https://simpleicons.org/?q=jquery

**Comment by sovetski** [comment]
any update please? the issue is closed without any solution
