### ISSUE TITLE
Thin webfont

### ISSUE THREAD

**Issue by martinrademacher** [tabler/tabler-icons#542]
Hello,
this is more a question than an issue. I would love to use the icons as webfont (.ttf) but with a thiner stroke with.
I can download all icons as SVG with stroke width 1. But if I want to convert the svg to a webfonts strokes are not supported. How do you convert them to fills? Do you have a kind of batch process or is it a manual process you are doing once for each icon?
Would it be easy for you to a export tabler-icons-thin.ttf?

**Comment by codecalm** [comment]
In future I want to generate thin and medium stroke webfonts too :)
