### ISSUE TITLE
Add Loading tag to Loaders

### ISSUE THREAD

**Issue by aMySour** [tabler/tabler-icons#544]
I was looking for some loading icons, and typing in "Loading" into the tabler-icons.io search box, returning nothing.

I assumed there weren't any loading icons, so I resorted to searching for circle and arc icons.

I only realized after a while that they were called "Loaders". In my opinion, it'd be great to have loading tags on them to easily find them :)

**Comment by codecalm** [comment]
i'll add it soon! :)
