### ISSUE TITLE
Eye closed

### ISSUE THREAD

**Issue by nilshoerrmann** [tabler/tabler-icons#546]
Thanks for this great icon set!

In addition to `eye-off`, it would be nice to have an "eye closed" icon. Something that can be used to highlight hidden layers in a tree similar to what apps like Figma do:

![Bildschirmfoto am 2023-02-28 um 12 53 06](https://user-images.githubusercontent.com/25466/221847209-45aa996f-2f02-4f73-9183-4b527138e085.png)

**Comment by codecalm** [comment]
![Screenshot 2023-03-07 at 21 48 26](https://user-images.githubusercontent.com/1282324/223548971-88bd3694-add2-4de7-9a43-4acd17c7fdab.png)

**Comment by codecalm** [comment]
added! :)

**Comment by nilshoerrmann** [comment]
Thank you!
