### ISSUE TITLE
Copy icon as glyph, more

### ISSUE THREAD

**Issue by yoyurec** [tabler/tabler-icons#548]
Nerd fonts doing coping not just code, bur "real symbol/glyph" https://www.nerdfonts.com/cheat-sheet via pseudoelement `content: "\xxxx"` value

```js
...
        textToCopy = window
          .getComputedStyle(document.querySelector(`.${parent.parentNode.querySelector('.class-name').innerText}`), ':before')
          .getPropertyValue('content')
          .replace(/"/g, '');
...
```
![image](https://user-images.githubusercontent.com/137919/220911585-c18d26bb-16a1-4940-ace7-677a92ec3f39.png)

would be better to add tag `i.ti.ti-[name]` with icon and its CSS... so it will have `content` from which JS can copy "symbol"

is there repo for Tabler site, so i can create PR? )

BTW, `content `value needs leading backslash `\`
![image](https://user-images.githubusercontent.com/137919/220915745-714834d0-f9f5-4f81-95ba-b23b8bdcc194.png)

_Originally posted by @yoyurec in https://github.com/tabler/tabler-icons/issues/516#issuecomment-1441758557_

**Comment by yoyurec** [comment]
@codecalm can i help somehow with this?

**Comment by codecalm** [comment]
I've changed content property on tabler-icons.io :)
