### ISSUE TITLE
Request: Crunchbase for Tabler Icons

### ISSUE THREAD

**Issue by adamkranitz** [tabler/tabler-icons#549]
Hey Tabler Team, is a Crunchbase icon on the roadmap? I'd love to be able to use a Crunchbase icon in Linktree. Thanks in advance.

**Comment by codecalm** [comment]
added! :)

**Comment by adamkranitz** [comment]
@codecalm Thank you. I don't see it yet in the Linktree search bar, but that may be on the Linktree side.

![Screenshot 2023-03-07 at 4 07 26 PM](https://user-images.githubusercontent.com/46003230/223553111-663d1170-cc4f-4dab-a14f-7ab8e3e767d6.png)
