### ISSUE TITLE
Icon request: filled star & closed eye

### ISSUE THREAD

**Issue by 3lmanana** [tabler/tabler-icons#55]
These two icons seem important to me, because we already have star icon which I mainly use as "favorite" action - so filled star icon would resemble when item is favorited.

Second one is closed eye I planned to use on "password fields" for a user to toggle if password is visible or not while typing.

**Comment by anserwaseem** [comment]
@3lmanana 
There should be a **half-filled star** too. What do you think about that!

<img width="124" alt="half-filled star" src="https://user-images.githubusercontent.com/32386713/89755516-2c1c8580-daf9-11ea-96ad-4a8a9aec6185.png">

**Comment by anserwaseem** [comment]
<img width="71" alt="half-filled star" src="https://user-images.githubusercontent.com/32386713/89755734-dbf1f300-daf9-11ea-9773-56a320ba4ae3.png">

Just take a look at these pair of pictures of stars. One is completely filled, other one is not. One half-filled star would be good addition.

**Comment by 3lmanana** [comment]
Agree, it would be a good addition 👍

**Comment by codecalm** [comment]
closed eye has been added in [v1.22.0](https://github.com/tabler/tabler-icons/releases/tag/v1.22.0)
task for stars is here #63
