### ISSUE TITLE
@tabler/icons-svelte package.json main/module entry is incorrect.

### ISSUE THREAD

**Issue by FranciscoMessina** [tabler/tabler-icons#550]
When trying to use the package with SvelteKit it error and says it couldn't resolve the entry for the package, after checking the included package json the ` "module" ` and `"main"` entries point to ` "dist/esm/tabler-icons-svelte.js"`, but from browsing the code I think it should point to `"dist/es/tabler-icons-svelte.js"` after changing the entries to the last value the package works properly.

**Comment by codecalm** [comment]
@SyntaxJoker working on it :) soon should be fixed! :)
