### ISSUE TITLE
Icon user-plus has a border in release 2.8.0

### ISSUE THREAD

**Issue by kmaic** [tabler/tabler-icons#559]
The icon user-plus, in the latest version 2.8.0, has a border.

![image](https://user-images.githubusercontent.com/98522475/223702945-2ef07216-cb63-49f0-bf51-7193101e203c.png)

If it is a bug can you get it fixed or indicate if the previous version is now a new icon please?

Thanks in advance!

**Comment by codecalm** [comment]
yes, there is bug. Today it will be fixed! :)

**Comment by kmaic** [comment]
@codecalm thanks for the feedback!

**Comment by codecalm** [comment]
fixed! :)
