### ISSUE TITLE
Incorrect rendering in Figma

### ISSUE THREAD

**Issue by n-apps** [tabler/tabler-icons#56]
Repeat, repeat-once, arrow-forward…

![image](https://user-images.githubusercontent.com/16646251/89766135-51f95880-db00-11ea-9a26-418eb2df040b.png)

They look well on browser, though.

**Comment by codecalm** [comment]
hi @n-apps!
it looks like the Figma bug. See here: https://twitter.com/webalys/status/1121858129657040898
