### ISSUE TITLE
IconFont:  wrong aligment/size of icon with texts

### ISSUE THREAD

**Issue by mauriblint** [tabler/tabler-icons#57]
I'm testing the icon font and seem to have a problem with the alignment/size of the icons and text itself.

![image](https://user-images.githubusercontent.com/1857729/90009203-05368e80-dc74-11ea-9904-46c25f7749c1.png)

Reproduce:
https://jsfiddle.net/mauriblint/6zd7jsL1/

Thanks,
Mauricio

**Comment by codecalm** [comment]
Hi!
you can manipulate of alignment with `vertical-align: bottom;` CSS property :)

**Comment by bbugh** [comment]
FYI you'll want to use `vertical-align: text-bottom` or `text-top` with tabler-icons SVGs, not `bottom`, if you're trying to align the SVG in-line with text. (This is well-supported by all browsers going back years)

```css
.icon.icon-tabler {
  vertical-align: text-bottom;
}
```

Examples:

| | | |
|---|---|--|
| `middle` | <img width="93" alt="image" src="https://user-images.githubusercontent.com/438465/90828191-36adfa80-e303-11ea-8539-c635970ca18e.png"> | too low |
| `bottom` | <img width="109" alt="image" src="https://user-images.githubusercontent.com/438465/90828209-3dd50880-e303-11ea-8767-57a5f8bd4deb.png"> | too low |
| `text-bottom` | <img width="96" alt="image" src="https://user-images.githubusercontent.com/438465/90828255-504f4200-e303-11ea-8dee-489a8591ade3.png"> | 👍 |
| `text-top` | <img width="100" alt="image" src="https://user-images.githubusercontent.com/438465/90828509-bfc53180-e303-11ea-850e-a8d1b6f6bcf0.png"> | 👍 |

**Comment by cospin** [comment]
I can't make the icons align with that property. I also use the Ant Design icons, and by reviewing the properties what they do is put: `-0.125em`
So my solution was to add:
```
.icon-tabler {
  vertical-align: -0.125em;
}
```

Now it works fine and in line with the antd icons.
