### ISSUE TITLE
Icon Removed? Latest package does not include `IconQuestionCircle`

### ISSUE THREAD

**Issue by raulfdm** [tabler/tabler-icons#576]
## Description

Hi peps! 👋 

Just a question, after upgrading `@tabler/icons-react` from 2.7 to 2.11, my build started failing due a missing `IconQuestionCircle`.

Was this icon removed at all? I tried to find in the CHANGELOG but it seems only new icons was added. 🤔 

Also, I no longer can find it in the home page:

![Screenshot 2023-03-20 at 15 56 00](https://user-images.githubusercontent.com/12464600/226379121-d83d3632-d7c2-4088-ab7d-300320da0420.png)

## Steps to reproduce

To see the problem you can access this Vite + React Stackblitz project: https://stackblitz.com/edit/vitejs-vite-fkw5rl?file=src/App.tsx.

There, in the `App.tsx`, you'll notice there's two imports:
1.  `import { IconQuestionMark } from '@tabler/icons-react-latest';` is the latest version. If you try to import `IconQuestionCircle`, you'll see the error
2. `import { IconQuestionCircle } from '@tabler/icons-react-with-question';` is the version `2.7.0`, there we still have the `IconQuestionCircle`

Please let me know if it's enough information.

**Comment by codecalm** [comment]
hi @raulfdm! tablericons.com is not official website of Tabler Icons. It's not connected to pur project. 
All icons are available on https://tabler-icons.io 

New icon is available as `IconHelpCircle` :) 
look at demos: https://tabler-icons.io/i/help-circle

**Comment by raulfdm** [comment]
Thanks @codecalm .

I didn't know I was looking at a third-party website 😅 

So, in summary, the icon was removed/renamed, right?

May I suggest you something? Please, follow semantic versioning. For consumers, it's essential to know that something has dramatically changed with a minor version bump. I'd expect a breaking change like this from `v2` to `v3`. 

One possible strategy for this case could maybe keep both icons and add a "deprecation" message so we can start to prepare for changes when needed.

Thanks for answering me and please keep doing this awesome job. This lib saved me a ton already!

**Comment by codecalm** [comment]
thank you for your idea! I'll flag icons as deprecated! :)
