### ISSUE TITLE
Could not find icon as per example

### ISSUE THREAD

**Issue by alaksandarjesus** [tabler/tabler-icons#58]
I tried to use 
<a href="">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    class="icon icon-tabler icon-tabler-disabled"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    stroke-width="1.25"
    stroke="currentColor"
    fill="none"
    stroke-linecap="round"
    stroke-linejoin="round"
  >
    ...
  </svg>
  Click me
</a>

and i get below as output

![image](https://user-images.githubusercontent.com/4712552/90307785-47bbcd80-def7-11ea-84c7-c8cccbb31031.png)

Below works perfectly, but could not set the stroke width

<svg width="24" height="24">
  <use xlink:href="path/to/tabler-sprite.svg#tabler-activity" />
</svg>

**Comment by alaksandarjesus** [comment]
Sorry.. I missed that 3 dots. If we want this svg, then we need to show up like this. 

copy pasted from https://tablericons.com/

<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-disabled" width="44" height="44" viewBox="0 0 24 24" stroke-width="1" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z"/>
  <circle cx="11" cy="5" r="2" />
  <polyline points="11 7 11 15 15 15 19 20" />
  <line x1="11" y1="11" x2="16" y2="11" />
  <path d="M7 11.5a4.97 4.97 0 1 0 6 7.5" />
</svg>

**Comment by codecalm** [comment]
tablericons.com are not connected with this repo, you should write to owner of this site :)
