### ISSUE TITLE
[Icon Request] filled variante of mail

### ISSUE THREAD

**Issue by u1b4n** [tabler/tabler-icons#580]
Would it be possible to provide the [mail](https://tabler-icons.io/i/mail) icon filled as well? Thanks for the answer. :)

**Comment by codecalm** [comment]
added in [2.15.0](https://github.com/tabler/tabler-icons/releases/tag/v2.15.0) :)

![tabler-icons-2 15 0](https://user-images.githubusercontent.com/1282324/230884502-68dfee08-95a3-4777-b27f-76503747c4b0.png)
