### ISSUE TITLE
[Icon Request] Chevron Up Down

### ISSUE THREAD

**Issue by ronaldtveen** [tabler/tabler-icons#583]
[Heroicons.com](https://heroicons.com/) has the `chevron-up-down` icon which can be used in dropdown comboboxes ([example](https://headlessui.com/vue/combobox)).

**Comment by codecalm** [comment]
how about `selector` icon? https://tabler-icons.io/i/selector

**Comment by ronaldtveen** [comment]
Perfect, don’t know how I missed that one.
