### ISSUE TITLE
[Icon Request] decimal

### ISSUE THREAD

**Issue by phungtranminh** [tabler/tabler-icons#590]
Thanks for creating these beautiful icons.

It would be nice to have icon for decimal.

As an initial idea, it can looks like current number with a dot, such as `1.2` or `1.23`

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.14.0 :) 

![tabler-icons-2 14 0](https://user-images.githubusercontent.com/1282324/229924798-708205fc-bb73-4e5d-91a7-0c2e99bcbede.png)

**Comment by phungtranminh** [comment]
Thanks it looks great!
