### ISSUE TITLE
[Icon request] Terraform

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#593]
Logo icon for the popular IaaC tool Terraform

https://terraform.io

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
