### ISSUE TITLE
[Icon request] TOML

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#595]
Similar to the `JSON` icon, but for TOML used in Rust / Cargo projects

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
