### ISSUE TITLE
stroke-width ignored

### ISSUE THREAD

**Issue by vict0rsch** [tabler/tabler-icons#6]
Hi,

thanks for your beautiful work! I'm having a hard time with `stroke-width`:

html:
```
<svg class="tabler-icon">
	<use xlink:href="../../icons/tabler-sprite.svg#tabler-circle-x" />
</svg>
```

and css:
```
.tabler-icon {
    height: 32px;
    width: 32px;
    color: #b31b1b;
    stroke-width: 0.85;
}
```

The size and color attributes are taken into account but not stroke-width. Any idea why?

**Comment by codecalm** [comment]
Hi @vict0rsch!

Unfortunately, it is not possible to modify property `stroke-width` when stroke is declared inside svg sprite.

I've released version 1.0.2 of tabler icons with new file `tabler-sprite-nostroke.svg`. Using this file you can modify stroke of the icon with css :)

**Comment by vict0rsch** [comment]
Thanks!

**Comment by lacwebadmin** [comment]
Is it also possible for the stroke to be adjusted on Webfont via font-weight? Well, I tried and it doesn't work.
