### ISSUE TITLE
[Icon request] OAuth / OAuth2

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#600]
OAuth is a popular authentication framework, it would be great to have an icon representing it on Tabler

references:
![image](https://user-images.githubusercontent.com/33750251/230042327-7da7659a-63b5-4a8e-9a20-3ded74494c2a.png)
![image](https://user-images.githubusercontent.com/33750251/230042296-ce2b88b6-59d7-46a0-b5b0-29dc1b00dceb.png)

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
