### ISSUE TITLE
[Icon request] Storj

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#602]
Storj is a web 3 / decentralized S3 alternative, this is a brand icon request

Not affiliated with the brand

![image](https://user-images.githubusercontent.com/33750251/230043000-606a156c-7f2a-4f7e-9ff5-d9d4fa85b261.png)

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
