### ISSUE TITLE
[Emoji update request] Discord

### ISSUE THREAD

**Issue by Steellgold** [tabler/tabler-icons#608]
Hey 👋 

Is it possible to update your Discord icon? because between Discord's icon and yours there is a big difference 😅

![image](https://user-images.githubusercontent.com/51505384/230073468-7211133f-515a-4c73-8e19-a706386a4e5d.png)

![image](https://user-images.githubusercontent.com/51505384/230073555-31dc3a3f-a747-4b08-b888-2e524528a1d1.png)

https://discord.com/branding

**Comment by josiahcbloomer** [comment]
This is the ugliest thing I've seen in my life. Also, it's not symmetrical.

**Comment by codecalm** [comment]
@josiahcbloomer make a better one, I look forward to your PR :)

**Comment by josiahcbloomer** [comment]
@codecalm Okay, but am I wrong in that the brand icons should follow the company's brand guidelines? So the discord icon should be minimally modified from the one on their website?

**Comment by MentorFilou** [comment]
Although this was changed it is still looking quiet different from what discord provides.
It was changed to be very angular, but the tabler icon is still very curvy.

From what I have read on the branding page, discord does not want their logo to be changed if used.
To quote discord's branding page: "Please do not edit, change, distort, recolor, or reconfigure the Discord logo.", although the logo without text "[should only be used when] the Discord brand is clearly visible or has been well established elsewhere on the page or in the design. (When in doubt, use the other one [with 'Discord' text].) ", but thats ultimately task of the tabler-icon users.

They provide the .svg file directly from their branding page (mentioned above), so it could be copied and rescaled to fit as a tabler icon i think. Thanks in advance!
