### ISSUE TITLE
[Icon Request] Iranian Rial Currency

### ISSUE THREAD

**Issue by AlirezaIvaz** [tabler/tabler-icons#609]
https://en.wikipedia.org/wiki/Iranian_rial
https://upload.wikimedia.org/wikipedia/commons/a/a1/Iranian_Rial.svg

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
