### ISSUE TITLE
Icon request: LinkedIn

### ISSUE THREAD

**Issue by a-zurcher** [tabler/tabler-icons#61]
Using this icon set for my resume, a LinkedIn icon would be great! Thanks for an amazing set of icons

**Comment by codecalm** [comment]
done! :) 

<img width="168" alt="Screenshot 2020-08-24 at 19 31 19" src="https://user-images.githubusercontent.com/1282324/91076858-6846fe80-e640-11ea-807e-7183a9ba4cdd.png">
