### ISSUE TITLE
Include Iconfont in package

### ISSUE THREAD

**Issue by trymeouteh** [tabler/tabler-icons#616]
The icon font CSS files are not included in the NPM package, and the only way to get the icon fonts is to use the CDN

`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/tabler-icons.min.css">`

Please include the icon font in the package.

**Comment by n9** [comment]
Or create a second package with fonts?

**Comment by ShahriarKh** [comment]
https://www.npmjs.com/package/@tabler/icons-webfont
