### ISSUE TITLE
Icon request: 2 new arrows

### ISSUE THREAD

**Issue by rickghome** [tabler/tabler-icons#62]
Can you please add  "arrow-bar-top" and "arrow-bar-bottom" to the set for symmetry?  You already have "arrow-bar-down" and "arrow-bar-up" which are great.  Illustrated suggestion below.

![Screen Shot 2020-08-22 at 2 31 31 PM](https://user-images.githubusercontent.com/869874/90966195-69333100-e484-11ea-991c-a3649b5a24d0.jpg)

**Comment by codecalm** [comment]
done, thank you! :)
