### ISSUE TITLE
[Icon Request] Brand Swift

### ISSUE THREAD

**Issue by nayaabkhan** [tabler/tabler-icons#621]
![5968371](https://user-images.githubusercontent.com/234889/230707086-e8089743-a03e-4d1a-a2c8-1c0ec0493cef.png)

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
