### ISSUE TITLE
[Icon Request] Brand LeetCode

### ISSUE THREAD

**Issue by schemetastic** [tabler/tabler-icons#622]
It could be useful for programmers to direct others to it's LeetCode profile, such as when creating a personal portfolio website, or other self-promoting content.

(I'm not Sponsoring and I'm not the owner of that trademark or brand).

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)

**Comment by schemetastic** [comment]
Wow! So fast! Great, thank you!
