### ISSUE TITLE
New HTTP `Query` Method

### ISSUE THREAD

**Issue by 0xflotus** [tabler/tabler-icons#623]
While there are some HTTP Methods in the icon set, please consider to add also the [new `QUERY` method](https://www.ietf.org/archive/id/draft-ietf-httpbis-safe-method-w-body-02.html).

**Comment by codecalm** [comment]
added in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

![tabler-icons-2 16 0](https://user-images.githubusercontent.com/1282324/232062695-9e324662-a16f-4b65-98db-66233460c874.png)
