### ISSUE TITLE
rename `http-path` to `http-patch`

### ISSUE THREAD

**Issue by JustGreg** [tabler/tabler-icons#625]
`http-path` should be renamed to `http-patch`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH
https://tabler-icons.io/i/http-path

**Comment by codecalm** [comment]
fixed in [2.16](https://github.com/tabler/tabler-icons/releases/tag/v2.16.0)! :)

thank you! ❤️
