### ISSUE TITLE
Icon request: Stars filled to 25, 50, 75, 100%

### ISSUE THREAD

**Issue by oczki** [tabler/tabler-icons#63]
Could you please add four new icons for stars that are filled up to various points?

Example: (hollow star already exists)
![image](https://user-images.githubusercontent.com/2924029/90987718-5d7f6180-e58d-11ea-9463-ef59e71b8a24.png)

This would allow making a rating component with half-stars.

Thanks for the awesome icon pack!

**Comment by jrlanglois** [comment]
I guess this also relates to https://github.com/tabler/tabler-icons/issues/55
