### ISSUE TITLE
Package size exceeded the configured limit of 100 MB.

### ISSUE THREAD

**Issue by marcoshw** [tabler/tabler-icons#636]
I cant see my app icons, I`m using CDN
https://cdn.jsdelivr.net/npm/@tabler/icons/iconfont/tabler-icons.min.css

When I try to reload that link, get the message
Package size exceeded the configured limit of 100 MB.

Thanks in advance

**Comment by Aunero** [comment]
I have the same problem, please help solve, thank you

**Comment by ShahriarKh** [comment]
Seems like the number of icons in the latest version broke it
https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/tabler-icons.min.css

**Comment by codecalm** [comment]
try use `@tabler/icons-webfont` instead of `@tabler/icons` 

from 2.0 all webfonts are moved to `@tabler/icons-webfont` package

https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css

**Comment by lekoala** [comment]
i have the same issue, i need the svg since i only load some of them when using last-icon
https://github.com/lekoala/last-icon
there must be a way to avoid the size limit ? maybe make a package with only the svg ?
