### ISSUE TITLE
Sccs example does not work

### ISSUE THREAD

**Issue by eerison** [tabler/tabler-icons#641]
I'm trying to use [scss example](https://tabler-icons.io/i/school), But it's not working :/ 

e.g:

```scss
@import 'node_modules/@tabler/icons-webfont/tabler-icons.scss';

div {
    content: $ti-icon-school;
}
```

error

```
 Error: Can't find stylesheet to import.
    ╷
  3 │ @import 'node_modules/@tabler/icons-webfont/tabler-icons.scss';

```

**Comment by codecalm** [comment]
@eerison which version of `@tabler/icons-webfont` do you use? We had similar issues with CSS files and was fixed in `2.17.0`

**Comment by eerison** [comment]
Ohhh I didn't know that I should install `@tabler/icons-webfont`, I will install that ;)

I have only `@tabler/icons@2.17.0 `

**Comment by eerison** [comment]
But it's dependency of icons, I already have it installed 

```
eerison@Erisons-MBP myprofile % npm show @tabler/icons-webfont

@tabler/icons-webfont@2.17.0 | Proprietary | deps: 1 | versions: 23
A set of free MIT-licensed high-quality SVG icons for you to use in your web projects.
https://tabler-icons.io

```
