### ISSUE TITLE
[Icon request] Wikipedia

### ISSUE THREAD

**Issue by alxlg** [tabler/tabler-icons#642]
I think Wikipedia is a fairly popular brand that deserves its icon and it would be useful for me. A serif "W" should be enough:

![](https://cdn.icon-icons.com/icons2/602/PNG/512/Wikipedia_icon-icons.com_55780.png)

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.18.0! 🙂

![tabler-icons-2 18 0](https://github.com/tabler/tabler-icons/assets/1282324/c8a7eda5-5a72-4390-86da-3aae3274f939)

**Comment by alxlg** [comment]
@codecalm perfect! I spotted good old FileZilla and VLC there, nice!
