### ISSUE TITLE
table-icons CDN doesn't work

### ISSUE THREAD

**Issue by wardvisual** [tabler/tabler-icons#644]
I noticed that the CDN doesn't work.
 
![image](https://user-images.githubusercontent.com/64777371/234852031-b764ed27-d9d0-4cbf-a885-1fd49407a446.png)

**Comment by Tetsuya485** [comment]
I'm trying to access the following URL:
https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/tabler-icons.min.css

However, I'm receiving a 403 error with the following message:
"Package size exceeded the configured limit of 100 MB."

**Comment by zobweyt** [comment]
I think they decided to separate everything into different packages. From now on, you need to add the following piece of code to your `head` to make it work:
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.17.0/tabler-icons.min.css" />
```

See more at https://tabler.io/docs/icons/webfont.

**Comment by MartinKolarik** [comment]
Hi, Martin from jsDelivr here. We've removed the size limit here, so the link works again, but note that, as @zobweyt points out, that file doesn't actually exist in the latest release of the package. We're falling back to `1.119.0` in this case, which is the latest version in which the file exists.

**Comment by Tetsuya485** [comment]
> I think they decided to separate everything into different packages. From now on, you need to add the following piece of code to your `head` to make it work:
> 
> ```
> <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.17.0/tabler-icons.min.css" />
> ```
> 
> See more at https://tabler.io/docs/icons/webfont.

Thanks to your help, the problem has been resolved. Thank you very much.
