### ISSUE TITLE
[Icon Request] More laundry icons

### ISSUE THREAD

**Issue by rudnovd** [tabler/tabler-icons#649]
- **Ironing without dots** - to indicate ironing on any temperature
![Ironing without dots](https://user-images.githubusercontent.com/15265510/235356887-44e3e381-0a04-4435-a958-0f1f191f36e9.png)

- **Dry flat**
![Dry flat](https://user-images.githubusercontent.com/15265510/235357045-61815594-d611-451d-a1aa-f6e05415bc2b.png)

- **Do not wet clean**
![Do not wet clean](https://user-images.githubusercontent.com/15265510/235357275-d15827b0-87fb-4cc3-9001-f587238fe5a2.png)

- **Hand wash**
![Hand wash](https://user-images.githubusercontent.com/15265510/235357371-6ddf20ea-aa8a-457a-862f-e74a23ab2042.png)

Dry in shade for other icons:

- [wash-dry-hang](https://tabler-icons.io/i/wash-dry-hang) in shade;
- [wash-dry-dip](https://tabler-icons.io/i/wash-dry-dip) in shade;
- **Dry flat in shade**;

Wash icons:

- [wash-press](https://tabler-icons.io/i/wash-press) for other temperatures ([wash-temperature-1](https://tabler-icons.io/i/wash-temperature-1)-press, [wash-temperature-2](https://tabler-icons.io/i/wash-temperature-2)-press etc.);
- [wash-gentle](https://tabler-icons.io/i/wash-gentle) for other temperatures ([wash-temperature-1](https://tabler-icons.io/i/wash-temperature-1)-gentle, [wash-temperature-2](https://tabler-icons.io/i/wash-temperature-2)-gentle etc.);
- **wash** with temperature numbers;

Dry cleaning:

- [wash-dry-f](https://tabler-icons.io/i/wash-dry-f)-gentle (one line);
- [wash-dry-f](https://tabler-icons.io/i/wash-dry-f)-very-gentle (two lines);
- [wash-dry-p](https://tabler-icons.io/i/wash-dry-p)-gentle (one line);
- [wash-dry-p](https://tabler-icons.io/i/wash-dry-p)-very-gentle (two lines);
- [wash-dry-w](https://tabler-icons.io/i/wash-dry-w)-gentle (one line);
- [wash-dry-w](https://tabler-icons.io/i/wash-dry-w)-very-gentle (two lines).

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.18.0! 🙂

![tabler-icons-2 18 0](https://github.com/tabler/tabler-icons/assets/1282324/c8a7eda5-5a72-4390-86da-3aae3274f939)
