### ISSUE TITLE
[Icon request] Repair or tools icons

### ISSUE THREAD

**Issue by Akif-Imran** [tabler/tabler-icons#655]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/76550232/237024449-35dc3667-33f2-479e-8b85-254126d96702.png">

**Comment by AnuragNishad12** [comment]
Is this a issue?

**Comment by BG-Software-BG** [comment]
Maybe you could use this [tool](https://tabler.io/icons/icon/tool) icon?
