### ISSUE TITLE
[Icon Request] Open folder

### ISSUE THREAD

**Issue by neutralshady** [tabler/tabler-icons#659]
An open folder is quite important in file explorers and typical places where the folder icon is used. I would like to have an open folder icon :).

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.24.0 🙂 

![](https://github.com/tabler/tabler-icons/assets/1282324/9364cd66-3445-4631-8b13-5de6160828df)
