### ISSUE TITLE
[Payment Icon Request] Add iDEAL as a payment method svg

### ISSUE THREAD

**Issue by rubenuijtdewilligen** [tabler/tabler-icons#660]
This was posted on [https://github.com/tabler/tabler/issues/1552](https://github.com/tabler/tabler/issues/1552) first, but I was told to post here.

[iDEAL](https://en.wikipedia.org/wiki/IDEAL) is the most used payment method in the Netherlands and all Dutch webshops have an iDEAL icon placed on their website. It was also recently acquired by the European Payments Initiative [to become the standard in Europe](https://nltimes.nl/2023/04/25/dutch-payment-processor-ideal-become-european-standard). I think it would be great to add an svg logo of this major payment method to Tabler.

**Comment by BG-Software-BG** [comment]
If it's the official logo of IDeal it will be impossible to create an icon with 24x24 px size.

Let us know if there is more appropriate logotype for an icon.
