### ISSUE TITLE
[Icon Request] Triangular prism; 3d solids with add symbol

### ISSUE THREAD

**Issue by PeterTYLiu** [tabler/tabler-icons#662]
![Screenshot 2023-05-17 at 7 39 54 PM](https://github.com/tabler/tabler-icons/assets/24631198/489800ff-54ad-4fa4-990b-9a223d6a96cb)

**Comment by codecalm** [comment]
I've made 14 new 3d icons, but I have no idea what to call some of them 😂 

![Screenshot 2023-05-20 at 00 57 25](https://github.com/tabler/tabler-icons/assets/1282324/dbb55aec-b21c-4407-9a24-077597bd08f5)

**Comment by PeterTYLiu** [comment]
@codecalm Looks great! Here are my proposals

1. Cylinder
2. Pyramid
3. Cone
4. HexagonalPyramid
5. Sphere
6. Cube
7. HexagonalPrism
8. [Octahedron](https://en.wikipedia.org/wiki/Octahedron) or [Bipyramid](https://en.wikipedia.org/wiki/Bipyramid) (?)
9. Prism
10. [Frustum](https://en.wikipedia.org/wiki/Frustum)
11. ???
12. ???
13. RectandularPrism
14. Hemisphere

**Comment by codecalm** [comment]
@PeterTYLiu fo 11 and 12 i found like this:

11. irregular polyhedron - https://www.svgrepo.com/svg/382602/3d-design-3d-irregular-polyhedron-3d-shape-geometric-geometry-irregular-polyhedron
12. irregular cylinder 3d - https://www.svgrepo.com/svg/382605/3d-design-3d-irregular-cylinder-3d-shape-geometric-geometry-irregular-cylinder

what do you think about this?

**Comment by PeterTYLiu** [comment]
@codecalm I guess 12 would be best described as an irregular decahedron. I have no idea about 11, except perhaps a "inverted conical bifustrum" or [diabolo](https://www.google.com/search?q=diabolo)

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v2.20.0 😍

![tabler-icons-2 20 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/5b735fa0-cf5e-424b-a175-b0a47d97865d)

**Comment by PeterTYLiu** [comment]
@codecalm Wow! That's phenomenal, thank you so much! I've already used them in [my project ](https://petertyliu.github.io/toaster/) and they look awesome!

**Comment by codecalm** [comment]
@PeterTYLiu wow, looks awesome! ❤️ if you need any extra icons give me know 🙂
