### ISSUE TITLE
[Icon Request] delete Table(tableOff); delete column(columnOff); delete row(rowOff)

### ISSUE THREAD

**Issue by jackyleefu** [tabler/tabler-icons#665]

**Comment by upview** [comment]
this would be really useful

**Comment by upview** [comment]
Currently using icons from remixixon to do so ![image](https://github.com/tabler/tabler-icons/assets/8210527/1f826814-63c0-4a73-a627-0714671a1a83)

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.24.0 🙂 

![](https://github.com/tabler/tabler-icons/assets/1282324/9364cd66-3445-4631-8b13-5de6160828df)

**Comment by upview** [comment]
Thanks a lot!! <3
