### ISSUE TITLE
[Icon Request] Brand - Rumble (SVG Provided)

### ISSUE THREAD

**Issue by scrothers** [tabler/tabler-icons#672]
![rumble_icon](https://github.com/tabler/tabler-icons/assets/111015/f6b56e90-39ba-4b75-8380-5b15f13de120)

Can we please have this icon added to the brands section?

Thanks!

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.22.0 🙂
