### ISSUE TITLE
[Icon request] Add stretch options to the Align Box icons

### ISSUE THREAD

**Issue by piotrkulpinski** [tabler/tabler-icons#673]
Something like this, for every side variant:
<img width="116" alt="CleanShot 2023-05-26 at 13 20 11" src="https://github.com/tabler/tabler-icons/assets/358412/627e40b4-396e-454b-8792-89f65ffec51a">

**Comment by AnuragNishad12** [comment]
hey bro @piotrkulpinski  when i run live server of index.html its show 
<img width="248" alt="image" src="https://github.com/tabler/tabler-icons/assets/124987038/540889bb-5018-47aa-9187-5b6ed1c37479">
why ? can u help me

**Comment by codecalm** [comment]
@piotrkulpinski added in https://github.com/tabler/tabler-icons/releases/tag/v2.22.0 🙂
