### ISSUE TITLE
Icon Request: Waveform Icons

### ISSUE THREAD

**Issue by jrlanglois** [tabler/tabler-icons#68]
- Sine
- Square
- Sawtooth
- Triangle

Example:

<img src="https://cdn4.explainthatstuff.com/types-of-waveform.png" width="350"></img>

**Comment by codecalm** [comment]
@jrlanglois how about that?

![Screenshot 2020-09-03 at 19 28 14](https://user-images.githubusercontent.com/1282324/92147580-a18b2580-ee1b-11ea-9bef-a50b96eb113c.png)

**Comment by jrlanglois** [comment]
Snap - I guess I missed them, or have some kind of weird page caching happening!

**Comment by codecalm** [comment]
done, will be published in version 1.19 :) 

![Screenshot 2020-09-03 at 21 41 30](https://user-images.githubusercontent.com/1282324/92159818-4d3d7100-ee2e-11ea-8b15-64f75218183a.png)
