### ISSUE TITLE
suggest a new brand icons

### ISSUE THREAD

**Issue by xakxa01** [tabler/tabler-icons#680]
- express.js
- node.js

**Comment by codecalm** [comment]
added in 2.33 🙂 https://github.com/tabler/tabler-icons/releases/tag/v2.23.0

![](https://github.com/tabler/tabler-icons/assets/1282324/a71d1ce0-5ce3-45d0-838c-928b6b0c4e6b)

**Comment by kadilab** [comment]
😍
