### ISSUE TITLE
[Icon request] Combine arrow-bar-right and arrow-bar-left

### ISSUE THREAD

**Issue by Tomic-Riedel** [tabler/tabler-icons#681]
An icon like "arrow-bar-right" and "arrow-bar-left", where there are 2 arrows pointing in the opposite direction.
Like this:
← | →

**Comment by codecalm** [comment]
added in 2.33 🙂 https://github.com/tabler/tabler-icons/releases/tag/v2.23.0

![](https://github.com/tabler/tabler-icons/assets/1282324/a71d1ce0-5ce3-45d0-838c-928b6b0c4e6b)
