### ISSUE TITLE
[Icon request] First/Last Page Icons for Pagination

### ISSUE THREAD

**Issue by KevinVandy** [tabler/tabler-icons#687]
### Discussed in https://github.com/tabler/tabler-icons/discussions/682

<div type='discussions-op-text'>

<sup>Originally posted by **KevinVandy** June 11, 2023</sup>
Right now I manually make a last page icon by combining a Chevron left/right and a pipe. It would be nice if it was built-in into Tabler.

 |< and >|

They are different from media skip controls as they are not filled in triangles.

https://mui.com/material-ui/material-icons/?query=las&selected=FirstPage

https://mui.com/material-ui/material-icons/?query=las&selected=LastPage</div>

**Comment by codecalm** [comment]
added in 2.33 🙂 https://github.com/tabler/tabler-icons/releases/tag/v2.23.0

![](https://github.com/tabler/tabler-icons/assets/1282324/a71d1ce0-5ce3-45d0-838c-928b6b0c4e6b)

**Comment by KevinVandy** [comment]
@codecalm dang there's like 5 icons I needed in this release

**Comment by codecalm** [comment]
you're welcome 🙂
