### ISSUE TITLE
[Icon request] Apple Vision Pro

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#688]
Useful for differentiating devices, specifically Apple's VisionPro considering there might be other Vision products i.e. non pro editions

**Comment by codecalm** [comment]
added in 2.33 🙂 https://github.com/tabler/tabler-icons/releases/tag/v2.23.0

![](https://github.com/tabler/tabler-icons/assets/1282324/a71d1ce0-5ce3-45d0-838c-928b6b0c4e6b)
