### ISSUE TITLE
[Request] Math Obelus / Divide sign and percent

### ISSUE THREAD

**Issue by LouizFC** [tabler/tabler-icons#69]
First I want to thank you for these icons, they are really beautiful and really fit in (almost) any ui.

I would like to request an Obelus sign, also know as "divide sign" and a lone "Percentage icon"

I am already using a modified tax/discount icon to fit my use case. I just took off the "frame" and rotated it.

Thanks in advance

**Comment by codecalm** [comment]
divide sign has been added in [v1.22.0](https://github.com/tabler/tabler-icons/releases/tag/v1.22.0)

**Comment by codecalm** [comment]
done :)
