### ISSUE TITLE
[Icon request] Microsoft Teams

### ISSUE THREAD

**Issue by ashleyyy94** [tabler/tabler-icons#690]
Hi team,

Love the icons! Can I request for the logo of Microsoft Teams to be added? Some samples from the react-icons package below

<img width="364" alt="image" src="https://github.com/tabler/tabler-icons/assets/20836965/4cf9ee45-9cef-40dd-b2bc-a4e21c6ee8da">

Thank you!

**Comment by codecalm** [comment]
added in 2.33 🙂 https://github.com/tabler/tabler-icons/releases/tag/v2.23.0

![](https://github.com/tabler/tabler-icons/assets/1282324/a71d1ce0-5ce3-45d0-838c-928b6b0c4e6b)
