### ISSUE TITLE
[Icon request] Brand Icon of Yandex

### ISSUE THREAD

**Issue by Jourloy** [tabler/tabler-icons#691]
Hello, add please Yandex icon :)

Example:

<img width="115" alt="Снимок экрана 2023-06-21 в 20 21 07" src="https://github.com/tabler/tabler-icons/assets/24356459/67c30f46-99c5-4e85-b942-50c732cf6359">

**Comment by codecalm** [comment]
added in 2.33 🙂 https://github.com/tabler/tabler-icons/releases/tag/v2.23.0

![](https://github.com/tabler/tabler-icons/assets/1282324/a71d1ce0-5ce3-45d0-838c-928b6b0c4e6b)
