### ISSUE TITLE
Update icons-svelte package to svelte 4

### ISSUE THREAD

**Issue by anatoliydarma** [tabler/tabler-icons#693]
Please update icons-svelte package to svelte 4

[https://svelte.dev/docs/v4-migration-guide](https://svelte.dev/docs/v4-migration-guide)

**Comment by Bliztle** [comment]
Having issues with this as well, what can i do to help? Is anyone working on it or do i make a PR?

**Comment by codecalm** [comment]
@anatoliydarma @Bliztle I've added Svelte 4 in [Release 2.28.0](https://github.com/tabler/tabler-icons/releases/tag/v2.28.0) 

Can you test it is everything okay? Because I don't have too much experience in Svelte 🙂

**Comment by devcsrj** [comment]
Can confirm, no more dependency conflict errors

**Comment by Bliztle** [comment]
It does seem to be breaking on SSR, though I can't say whether that's new or not. I haven't used it before svelte 4.

`Error when evaluating SSR module"
|- Error: Failed to resolve entry for package "@tabler/icons-svelte". The package may have incorrect main/module/exports specified in its package.json.`

I am also quite new to Svelte though, so I do not currently know how to fix it

**Comment by Bliztle** [comment]
Found a solution . package.json currently contains

```json
{
    "main": "dist/esm/tabler-icons-svelte.js",
    "module": "dist/esm/tabler-icons-svelte.js",
}
```

Which is reffering to files that do not exist. Those files can however be found by changing it to

```json
{
    "main": "dist/esm/packages/icons-svelte/src/tabler-icons-svelte.js",
    "module": "dist/esm/packages/icons-svelte/src/tabler-icons-svelte.js",
}
```

Since I do not know the intended location, I will just leave this here for someone else to handle.
