### ISSUE TITLE
[Icon Request] Restore

### ISSUE THREAD

**Issue by mojtabakaviani** [tabler/tabler-icons#699]
Please add restore icon.

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.24.0 🙂 

![](https://github.com/tabler/tabler-icons/assets/1282324/9364cd66-3445-4631-8b13-5de6160828df)

**Comment by mojtabakaviani** [comment]
Thanks, a lot!
