### ISSUE TITLE
Building and places types icons

### ISSUE THREAD

**Issue by pietia94** [tabler/tabler-icons#7]
**Religous**
Church
Synagogue
Mosque
Temple
Monastery

**Historical:**
Palace
Castle
Mansion
Column
Monument
Historical place

**Public utility:**
Government building
Educational building (schools, universities, etc.)
Cultural building (museum, theater, opera house)
Park
Square
Stadium / Entertainment hall
Cemetery
Hospital
Zoo
Racing Track
Market

**Infrastructure:**
Bridge
Station (bus or train for example)
Seaport
Airport
Dam
Street

**Military**
Tower
Fortification building
Wall

**Residential:**
Tenement house
House

**Natural:**
Mountain
Natural monument
Waterfall
National Park
Lake
River

**Other:**
Skyscraper
Hotel

**Comment by alriksson** [comment]
Could also add icon requests to the list, finance, gaming/gambling sports, social related icons. Outside that, I miss a certificate and language icon.

**Comment by dandanio** [comment]
@pietia94 @wpsumo There is that Sponsor button on the top of this page, you know, just saying... :)

Amazing work by @codecalm ! Once I get any $$$ flowing from my project, I will hit the tip jar!

**Comment by pietia94** [comment]
Hi @codecalm, will you be able to make these icons?

**Comment by codecalm** [comment]
first part of icons:

<img width="1246" alt="Screenshot 2020-10-14 at 16 09 12" src="https://user-images.githubusercontent.com/1282324/96000864-a807b680-0e37-11eb-8965-09d07e3154e1.png">

**Comment by pietia94** [comment]
@codecalm can i help you somehow with creating further icons?
