### ISSUE TITLE
Please add a closed eye, and a bell that is ringing...

### ISSUE THREAD

**Issue by rickghome** [tabler/tabler-icons#70]
You've done such a great job, and you've been incredibly responsive.  Could you please also consider adding a "closed eye" icon to pair up with your open-eye icon, as well as a "ringing-bell" to go with your existing bell?

**Comment by zaddok** [comment]
Yes, I was looking for the closed eye icon as well. Used for the Mark "Visible/Not visible" type button.

**Comment by codecalm** [comment]
closed eye has been added in [v1.22.0](https://github.com/tabler/tabler-icons/releases/tag/v1.22.0)

**Comment by rickghome** [comment]
You’re doing amazing work!  Thank you so much!

best
rickg

**Comment by codecalm** [comment]
done :)
