### ISSUE TITLE
Using CSS, how do I use a light font?

### ISSUE THREAD

**Issue by dropways** [tabler/tabler-icons#706]
**Like stroke 1**

![image](https://github.com/tabler/tabler-icons/assets/38377336/dca695ca-3188-4ac5-bc53-6379a0a89184)

**Comment by arduinoturkbatu** [comment]
There is a `stroke` property in CSS. If you are usign SVG, you can use that stroke thing in CSS. But I don't know how to use that for Icon Font.

**Comment by dropways** [comment]
No, we're using fonts instead of SVG for our CSS. If there is a choice for font weight in the feature, I believe we should use a light font.

**Comment by ShahriarKh** [comment]
related: https://github.com/tabler/tabler-icons/discussions/271
