### ISSUE TITLE
Icon request: brand-threads

### ISSUE THREAD

**Issue by arduinoturkbatu** [tabler/tabler-icons#710]
Since Threads app announced, I think there should be a Threads icon

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.25.0 🙂 

<img src="https://github.com/tabler/tabler-icons/assets/1282324/1449e453-7124-4cf0-8a84-3014b8340ea5" width="584" alt="" />
