### ISSUE TITLE
Icons request: Generic cola

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#712]
Its impossible to represent every cola brand, so having a generic cola icon would help, with three separate editions: filled, half-fileld, and non-filled

**Comment by itsezc** [comment]
@BG-Software-BG is there any particular reason this was rejected?

**Comment by codecalm** [comment]
it's not possible to make coca-cola logo in 24x24px grid and 2px stroke

**Comment by itsezc** [comment]
> it's not possible to make coca-cola logo in 24x24px grid and 2px stroke

My request isn't for a Coca Cola logo, but rather a generic cola, i.e. it could be an aluminium can or a can with cola written on it
