### ISSUE TITLE
Graduation Cap

### ISSUE THREAD

**Issue by eluce2** [tabler/tabler-icons#716]
Would love to see a graduation cap icon

**Comment by ShahriarKh** [comment]
It's really needed, no need to mention the number of online learning platforms :-)

**Comment by codecalm** [comment]
its already exists 🙂 https://tabler-icons.io/i/school

**Comment by mokhosh** [comment]
@codecalm honestly "school" is such a bad name for this icon.
Please at least make it searchable using these keywords:
- Graduation
- Academic
- Scholar
- Cap
- Hat
