### ISSUE TITLE
[Icon Request] Shopping bag variants

### ISSUE THREAD

**Issue by ShahriarKh** [tabler/tabler-icons#723]
Shopping bag with plus, minus, ...

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.28.0 🙂 

<img src="https://github.com/tabler/tabler-icons/assets/1282324/deb7266b-7079-45ed-8d49-12df5fbc2aed" width="584" alt="" />

**Comment by ShahriarKh** [comment]
Awesome!
The cart icons are great, but since we are using the cart icon for another thing, I decided to use shopping bag icon for actual cart. Honestly, the `shopping-bag` icon is much better than `basket`... I wish we had variants for that too.

**Comment by codecalm** [comment]
oh damn, I tough about shopping cart 😂 I'll add shopping-bag in next release 🙂

**Comment by ShahriarKh** [comment]
I see you added them in the latest release! Thank you so much ❤️‍🔥
