### ISSUE TITLE
Unable to integrate @tabler/icons-svelte package into new SvelteKit project

### ISSUE THREAD

**Issue by leroytromp** [tabler/tabler-icons#724]
Attempting to install the @tabler/icons-svelte package in a new SvelteKit project results in a dependency conflict, because this package expects Svelte version 3, while new SvelteKit project are on a new major version of Svelte, namely version 4.
![dependency_conflict](https://github.com/tabler/tabler-icons/assets/84224065/9407c046-88c5-4a81-b84e-0c3c960ea9bf)

**Comment by Plorenzo** [comment]
already reported https://github.com/tabler/tabler-icons/issues/693
