### ISSUE TITLE
Please Add a Discord Icon

### ISSUE THREAD

**Issue by souvik362** [tabler/tabler-icons#73]
# Discord is a popular chat and community service and its now popular so it will be helpful for us

**Comment by codecalm** [comment]
done :) 

![Screenshot 2020-09-17 at 23 14 35](https://user-images.githubusercontent.com/1282324/93529050-94058d80-f93b-11ea-9414-6261615aba1e.png)

**Comment by souvik362** [comment]
Thanks :) 
but i please add it on icons ICONS-PNG & ICONS directory for better usability .
and can use tell me if this possible to render the icons in png using CMD or Gulp

**Comment by codecalm** [comment]
@souvik362 will be available in next release
