### ISSUE TITLE
User Settings / Role Icon

### ISSUE THREAD

**Issue by zaddok** [tabler/tabler-icons#74]
Tried to make one myself, it didn't turn out that well. Can we have something like this?
<img width="71" alt="Screen Shot 2020-09-18 at 9 28 13 am" src="https://user-images.githubusercontent.com/20467896/93538346-4a479200-f991-11ea-83a4-eff249e7ba57.png">

**Comment by iAlborz** [comment]
I think a setting icon with a small user next to it would be better in this case. since the cog has more detail, making it small would be a bit difficult. 
alternativaly you could keep the same layout and use a wrench instead of a cog! I think that would work too.

**Comment by iAlborz** [comment]
I have a new comment to add to my old comment. 

Keeping it the same layout as you have above can work. But I think the cog needs to go down to 6 teeth from 8. That should be enough to make it less busy.
