### ISSUE TITLE
[Suggestion] Add country flag icons

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [tabler/tabler-icons#744]
Hi, could you consider making icons for country flags?

**Comment by codecalm** [comment]
we are creating monocolor icons, so it's impossible to create countries flag without colors and in 24x24px grid 🙂

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Thanks for the response 👍
