### ISSUE TITLE
Video call icon

### ISSUE THREAD

**Issue by zaddok** [tabler/tabler-icons#75]
Zoom, Facetime, Google meet style video camera icon:

![images](https://user-images.githubusercontent.com/20467896/93710860-0caf5880-fb8d-11ea-9582-27640dc675a4.jpeg)

**Comment by codecalm** [comment]
done :) 

![Screenshot 2020-09-22 at 12 49 44](https://user-images.githubusercontent.com/1282324/93873543-273f1a00-fcd2-11ea-8edd-72c7730c85b9.png)

**Comment by zaddok** [comment]
Amazing! Thankyou!

**Comment by codecalm** [comment]
@zaddok if you need any more icons just create the issue :)
