### ISSUE TITLE
Please add the old map-pin icon again

### ISSUE THREAD

**Issue by orsilyon** [tabler/tabler-icons#757]
![image](https://github.com/tabler/tabler-icons/assets/140499210/78d595fe-0b7c-44ca-ade3-fd545ed7916c)

**Comment by Umbrien** [comment]
+1, this icon is now same as map-2

**Comment by nguyenkhois** [comment]
I have created a new issue for duplicate icons [here](https://github.com/tabler/tabler-icons/issues/787).

**Comment by nguyenkhois** [comment]
This request is fixed in the latest release [2.31.0](https://github.com/tabler/tabler-icons/releases/tag/v2.31.0) 👍
