### ISSUE TITLE
Error for stroke-width attribute when using TypeScript

### ISSUE THREAD

**Issue by ronaldtveen** [tabler/tabler-icons#758]
I'm using the `@tablericons/vue` package but keep getting an error when using typescript:

Basic example:
```ts
<script lang="ts" setup>
import { IconSearch } from '@tabler/icons-vue'
</script>
<template>
  <div>
     <IconSearch :size="18" stroke-width="1" />
  </div>
</template
```

This returns the error (see screenshot below):
```
Argument of type '{ strokeWidth: string; size: number; color: string; }' is not assignable to parameter of type 'SVGProps'.
  Object literal may only specify known properties, but 'strokeWidth' does not exist in type 'SVGProps'. Did you mean to write 'stroke-width'?ts(2345)
(property) strokeWidth: string
```

I have also tried using it is a number via `<IconSearch ... :stroke-width="1" />`

In `tabler-icons-vue.d.ts` it says:
```
4 // Create interface extending SVGAttributes
5 export interface SVGProps extends Partial<SVGAttributes> {
6  size?: 24 | number
7 }
```
When I add `strokeWidth?: 2 | number` to it and reload my VSC window, it actually works.

The [docs](https://tabler.io/docs/icons/vue#how-to-use) makes it more confusing/inconsistent by saying we should use `stroke-with="1.25"` but the prop is just `stroke` (number)?

What is the best way to go about this?

---

#### Attachment
<img width="854" alt="tabler-vue-stroke-width" src="https://github.com/tabler/tabler-icons/assets/7911547/f7b04f39-12f1-4c69-b76c-ed7adfe7a57e">

**Comment by DanielTamargo** [comment]
Same happened to me and yes, docs made it more confusing 🤯  

As a very quick workaround to avoid those linter errors, I added the following line to tabler-icons-vue.d.ts:  
![image](https://github.com/tabler/tabler-icons/assets/32647764/1e8fad6b-a3ca-4abf-af16-341be027f0c4)  
_(make sure to reload developer window after adding this line)_  
After that, you can use both `stroke-width="2"` (string) or `:stroke-width="2"` (number) and works fine.

But I'm still confused, strokes are often modified so I guess I'm not understanding something basic or how to configure it properly.  
Hope someone can help us 🤍

**Comment by DanielTamargo** [comment]
I found a simpler (and cleaner) way to avoid this linter error.
I created a **tabler-icons.d.ts** file and added the following code  
```ts
export {};

declare module "@tabler/icons-vue" {
    interface SVGProps {
        strokeWidth?: number | string;
    }
}
```
So now I don't need to modify package files (yaaay 🎉).  

If creating a whole separated file feels "heavy", you can move it to any **common.d.ts** or **global.d.ts** or w/e file you use for type declarations (I usually use global.d.ts for window attached variables like window.axios or w/e) (dunno if that's a good practice, I'm learning with baby steps).  

I found the solution following this post: [**Extending Global or Third Party Library Typing** by **malcolmkee**](https://malcolmkee.com/today-i-learnt/extending-global-or-third-party-type/)  

Hope this helps!
