### ISSUE TITLE
Contributing to tabler.io

### ISSUE THREAD

**Issue by quazar-omega** [tabler/tabler-icons#764]
Is there a public repository for the website https://tabler.io?  
I was looking for it because I would have liked to try and contribute a small feature to dynamically append query parameters to the URL for easy bookmarking and sharing of results

**Comment by codecalm** [comment]
Hi, website of tabler.io is here: https://github.com/tabler/tabler/tree/dev/site 🙂

**Comment by quazar-omega** [comment]
Thanks a lot! I'll look into it

**Comment by quazar-omega** [comment]
Oh I'm very sorry, I made a mistake, I meant to say https://tabler-icons.io instead, that's where the search feature is
