### ISSUE TITLE
[Icon request] announcement/notice icon

### ISSUE THREAD

**Issue by woodlou** [tabler/tabler-icons#767]
like this <img width="224" alt="image" src="https://github.com/tabler/tabler-icons/assets/8233827/991b01d9-c69b-4e91-a370-3e98d2e77f20">

**Comment by net-tech** [comment]
This already exists https://tabler-icons.io/i/speakerphone

**Comment by codecalm** [comment]
[tabler-icons.io/i/speakerphone](https://tabler-icons.io/i/speakerphone)
