### ISSUE TITLE
angular usage

### ISSUE THREAD

**Issue by gkathire** [tabler/tabler-icons#77]
Can anyone let me know how svg icons can be used in the angular apps ?

**Comment by VolticFroogo** [comment]
The easiest way is probably to use [the iconfont](../tree/master/iconfont) (though this is currently bugged right now, see issue #13) as this should work flawlessly even in an SPA.

If you are not using SPA with Angular routing, just using the sprite sheet like normal via HTML works fine. Though if you are using Angular routing, it will reload the sprite sheet when navigating causing a performance hit and flickers.

### Using [mat-icon](https://material.angular.io/components/icon/overview) with Angular

Until the iconfont is fixed, I have been using [mat-icon](https://material.angular.io/components/icon/overview) from [the official Angular Material framework](https://material.angular.io/) with the MatIconRegistry to add Tabler Icons.

If you do want to use [mat-icon](https://material.angular.io/components/icon/overview), you can register the Tabler Icons sprite like this in your `app.component.ts`'s constructor (or anywhere which is called during initialisation):
```ts
constructor(private matIconRegistry: MatIconRegistry, private domSanitizer: DomSanitizer) {
  matIconRegistry.addSvgIconSet(this.domSanitizer.bypassSecurityTrustResourceUrl('assets/tabler-sprite.svg'));
}
```

Then you can utilise those customs icons in your components like so:
```html
<mat-icon svgIcon="tabler-brand-tabler"></mat-icon>
```
