### ISSUE TITLE
[Icon Request] More avatar options

### ISSUE THREAD

**Issue by augiethehuman** [tabler/tabler-icons#771]
Would be great to have more avatar options. Hexagon avatar,  square avatar, avatar inside of gear icon, etc.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.31.0 ! 🙂 

![tabler-icons-2 31 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/fb4a1463-3252-43ec-85d0-203d6aad9bc3)

**Comment by augiethehuman** [comment]
Thank you sir!
