### ISSUE TITLE
[Icon request]: Brand Icon for Databricks

### ISSUE THREAD

**Issue by phzietsman** [tabler/tabler-icons#773]
Databricks brand guide: https://brand.databricks.com/

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.31.0 ! 🙂 

![tabler-icons-2 31 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/fb4a1463-3252-43ec-85d0-203d6aad9bc3)
