### ISSUE TITLE
[Icon Request] Caret Down & Up in one

### ISSUE THREAD

**Issue by noahstuesser** [tabler/tabler-icons#774]
I would love to see a caret down & up (also the filled version) in one icon. An alternative arrow-sort icon.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.31.0 ! 🙂 

![tabler-icons-2 31 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/fb4a1463-3252-43ec-85d0-203d6aad9bc3)
