### ISSUE TITLE
[Icon Request] Trojan horse

### ISSUE THREAD

**Issue by noahstuesser** [tabler/tabler-icons#775]
I would love to see a trojan horse. Like the horse toy icon but without the curved bottom but with maybe 2 wheels or so.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.31.0 ! 🙂 

![tabler-icons-2 31 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/fb4a1463-3252-43ec-85d0-203d6aad9bc3)
