### ISSUE TITLE
[Icon Request] Versus

### ISSUE THREAD

**Issue by noahstuesser** [tabler/tabler-icons#776]
I am missing a versus icon in different variations. VS as the abbreviation in a box and without like the AD icons.

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.31.0 ! 🙂 

![tabler-icons-2 31 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/fb4a1463-3252-43ec-85d0-203d6aad9bc3)
