### ISSUE TITLE
Icon request: Twitter rebrand to X

### ISSUE THREAD

**Issue by patrickmccallum** [tabler/tabler-icons#779]
Now that Twitter is officially X, the Twitter Icon needs an update (or companion) to IconBrandX.

**Comment by patrickmccallum** [comment]
Apologies, I see this in the commit logs now. :)

**Comment by monlinkleo** [comment]
> Apologies, I see this in the commit logs now. :)

<img width="1402" alt="image" src="https://github.com/tabler/tabler-icons/assets/84716121/9f1c7a7b-c953-4762-ac3b-8069076654f7">
I'm sorry to bother you, but can you find the latest Twitter icon in the official catalog?

**Comment by codecalm** [comment]
I've added tags to brand-x icon 🙂
