### ISSUE TITLE
Icon Request: pined

### ISSUE THREAD

**Issue by scrollbar-ww** [tabler/tabler-icons#78]
Could you add a "pined" icon ?  ~ed status of the "pin" icon.
And thanks for these awesome icons !

**Comment by Chaphasilor** [comment]
I think the word you're looking for is 'pinned' :D

**Comment by codecalm** [comment]
:) 

<img width="411" alt="Screenshot 2020-10-01 at 13 32 55" src="https://user-images.githubusercontent.com/1282324/94804154-a4f9d880-03ea-11eb-8020-21972243c6e5.png">

**Comment by scrollbar-ww** [comment]
Pretty good ! Thank you !
