### ISSUE TITLE
[Icon request] 500px

### ISSUE THREAD

**Issue by wernergusset** [tabler/tabler-icons#780]
I would love to see an icon for 500px.

**Comment by BG-Software-BG** [comment]
@wernergusset did you mean this logo https://logowik.com/500px-logo-vector-svg-pdf-ai-eps-cdr-free-download-13273.html ?

**Comment by wernergusset** [comment]
> @wernergusset did you mean this logo https://logowik.com/500px-logo-vector-svg-pdf-ai-eps-cdr-free-download-13273.html ?

Yes, this one

**Comment by BG-Software-BG** [comment]
So, it seems impossible to create a 24x24px icon with this logo.

**Comment by wernergusset** [comment]
I can also see it that way. I hadn't thought about it before.
