### ISSUE TITLE
Megaphone or Announcements (icon request)

### ISSUE THREAD

**Issue by tofful** [tabler/tabler-icons#79]
Would you consider adding a megaphone or announcements icon, please?

The FontAwes*me 🙈 version would be this one (just adding for references)
![image](https://user-images.githubusercontent.com/1058850/94773585-90ccd000-0418-11eb-997e-66f7d7622a19.png)

**Comment by codecalm** [comment]
done :) 

<img width="116" alt="Screenshot 2020-10-01 at 13 08 18" src="https://user-images.githubusercontent.com/1282324/94802008-32d3c480-03e7-11eb-9c22-400ce658e183.png">

**Comment by tofful** [comment]
under which name can I find the icon? @codecalm

**Comment by tofful** [comment]
Awesome thank you @codecalm
