### ISSUE TITLE
[Icon Request] -- Alpha List Icon

### ISSUE THREAD

**Issue by rickghome** [tabler/tabler-icons#790]
This project is fantastic, and I'm delighted that each time I look for an icon, it usually exists already. Would it be possible to add another list item icon (that goes with the "numbered list" icon)?  I've drawn a lousy version in the illustration attached:
<img width="162" alt="Screenshot 2023-08-16 at 4 02 38 PM" src="https://github.com/tabler/tabler-icons/assets/869874/e46272da-5b13-48b6-805d-1a127fab2b1e">

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.31.0 ! 🙂 

![tabler-icons-2 31 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/fb4a1463-3252-43ec-85d0-203d6aad9bc3)

**Comment by rickghome** [comment]
This is perfect. I'm really thankful for all your amazing work.
