### ISSUE TITLE
Square rounded plus seems changed unintentionally

### ISSUE THREAD

**Issue by phungtranminh** [tabler/tabler-icons#796]
Hi,

For some reasons, square rounded plus seems to change from 

<img width="41" alt="Screenshot 2023-08-22 at 5 17 15 pm" src="https://github.com/tabler/tabler-icons/assets/77000018/54633a6f-8a03-4360-9278-48335dcad355">

to this

<img width="40" alt="Screenshot 2023-08-22 at 5 17 41 pm" src="https://github.com/tabler/tabler-icons/assets/77000018/f4922176-ffb6-4d04-acac-9eecdfe34f43">

It seems unintended as filled square rounded plus seems unchanged?

<img width="315" alt="Screenshot 2023-08-22 at 5 18 16 pm" src="https://github.com/tabler/tabler-icons/assets/77000018/4057718b-54e9-41d7-9c0f-acd7d6d36add">

**Comment by baba43** [comment]
I noticed the same with the `IconCirclePlus`

**Comment by codecalm** [comment]
yes, it's unintentionally 🙂 I'll fix it in next release

**Comment by phungtranminh** [comment]
Hi @codecalm thanks for looking into this, but looks like you were fixing `circle-plus` while the issue is with `square-rounded-plus`?

**Comment by gigobyte** [comment]
I can confirm `square-rounded-plus` is still not the right icon.
