### ISSUE TITLE
Try to fix the points, some icons are imported broken

### ISSUE THREAD

**Issue by marlon-borges** [tabler/tabler-icons#798]
Like settings

![image](https://github.com/tabler/tabler-icons/assets/115946238/14860e03-4950-4c1d-a921-8b00de4cc347)

**Comment by codecalm** [comment]
can you remove "Paste icons as outline" option? It looks like a Figma bug

**Comment by marlon-borges** [comment]
Yes, removing the option "Paste icons as outline" the stroke is imported correctly. I didn't know that the plugin used the "Outline stroke" from Figma, I thought it was imported from some bank already without the stroke, but that's ok, thanks for answering!
