### ISSUE TITLE
File conflict for `device-game-pad.svg` and `device-gamepad.svg`

### ISSUE THREAD

**Issue by knulpi** [tabler/tabler-icons#799]
Since release `2.32.0`, svelte won't build with `icons-svelte` anymore. The problem boils down to the newly introduced `device-game-pad.svg` icon. It causes a file conflict, so that only `IconDeviceGamePad.svelte` is in the release, but not `IconDeviceGamepad.svelte`. The latter, however, is still referenced in the built `tabler-icons-svelte.js` file, causing the svelte build to fail when using `2.32.0`.

Suggestion: As there already are two gamepad icons, change the latest added one to be `device-gamepad-3.svg`. I will open a PR for that.

**Comment by knulpi** [comment]
> Could this be the cause of this following error? I'm I have tried v2.31 and v2.32 and when building it in docker it fails. Just wanted to double check before making another issue.
> 
> ![image](https://user-images.githubusercontent.com/11448029/263555604-dcf2bd45-ed39-462d-9eac-91f584844959.png)

yes, that's exactly the one.

**Comment by miguelgargallo** [comment]
I solved using

`"@tabler/icons-svelte": "2.30.0",`
