### ISSUE TITLE
[Super Quick] 'Scan' icon

### ISSUE THREAD

**Issue by Chaphasilor** [tabler/tabler-icons#80]
I'm basically looking for a mix of the 'Shield' and 'Search' icons, the same why that 'Shield-Check' and 'Shield-Off' combine two icons.
Given that both icons are already available and only need to be combined, I think this should be really easy to do, right?

Reason is I need a button for 'Scan for viruses'.

A separate scan icon without the shield would also work of course :)

Thanks in advance!

**Comment by codecalm** [comment]
done :) 

<img width="180" alt="Screenshot 2020-10-01 at 12 37 49" src="https://user-images.githubusercontent.com/1282324/94799183-074edb00-03e3-11eb-96ff-dcb94a6cb0e3.png">

**Comment by codecalm** [comment]
i've also added `virus-off` icon 

<img width="131" alt="Screenshot 2020-10-01 at 12 48 27" src="https://user-images.githubusercontent.com/1282324/94800155-7f69d080-03e4-11eb-809b-bcfd18f10fca.png">

**Comment by Chaphasilor** [comment]
You're an awesome person! <3

**Comment by codecalm** [comment]
@Chaphasilor thank you :) If you still need any more icons just let me know :)
