### ISSUE TITLE
New .ti-circle-plus

### ISSUE THREAD

**Issue by heeroyuiGO** [tabler/tabler-icons#805]
I have a problem with the new .ti-circle-plus in v2.32.0 (and 2.31)

before, i have a + in circle but its totaly different now

<img width="204" alt="Capture d’écran 2023-08-28 à 18 13 28" src="https://github.com/tabler/tabler-icons/assets/35996646/d417fdef-541e-4fb0-bbd2-c236ceab096e">
<img width="221" alt="Capture d’écran 2023-08-28 à 18 13 57" src="https://github.com/tabler/tabler-icons/assets/35996646/089170e9-ebc6-48cf-965b-faeda3cc0c72">

it's preferable to create a new icon (class, svg, etc.).

**Comment by Tooni** [comment]
same as this issue i think 
https://github.com/tabler/tabler-icons/issues/796#issuecomment-1687887447

**Comment by codecalm** [comment]
it's fixed! 🙂 [tabler-icons.io/i/circle-plus](https://tabler-icons.io/i/circle-plus)
