### ISSUE TITLE
[Icon Request] Login-2

### ISSUE THREAD

**Issue by christoph-jeanluc-schneider** [tabler/tabler-icons#809]
Logout has a Logout-2, Login is missing it.

#### Logout and Logout-2:
![logout-2](https://github.com/tabler/tabler-icons/assets/19204727/eb548d19-10ea-4461-b46c-70615467a4af)
![logout](https://github.com/tabler/tabler-icons/assets/19204727/1f001945-1d68-41e9-b543-7f62b9103060)

#### Login:
![login](https://github.com/tabler/tabler-icons/assets/19204727/609fbbc7-a47d-4980-8ebb-ce16648f1fad)

#### Requesting the following:
![login-2](https://github.com/tabler/tabler-icons/assets/19204727/ed7eac75-2867-4523-98f0-acd84569a136)

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.33.0 🙂 

<img src="https://github.com/tabler/tabler-icons/assets/1282324/33d7e0ff-702a-48e9-9b6a-59e00d2310cc" width="584" alt="" />
