### ISSUE TITLE
Icon request: function

### ISSUE THREAD

**Issue by dflock** [tabler/tabler-icons#81]
Simple icon that represents a function: `f(x)` - something like this:

![](https://user-images.githubusercontent.com/47756/41008691-4051bc00-68e1-11e8-9f2c-5a72a545546e.png)

**Comment by codecalm** [comment]
<img width="225" alt="Screenshot 2020-10-14 at 16 05 50" src="https://user-images.githubusercontent.com/1282324/96000458-3596d680-0e37-11eb-9b57-648a8a770ed4.png">

:)

**Comment by dflock** [comment]
This is nice, but the brackets are important, I think. "fx" could mean Foreign Exchange (i.e. currency trading) etc..., but "f(x)" unambiguously means Function.

**Comment by iAlborz** [comment]
I think the curved ƒ is enough to show that this is function. I've used this icon before in an analytics tools and people didn't have a problem recognizing this. Within the right context it was very clear that this means function. (next to other mathematical, analytical icons)
