### ISSUE TITLE
Square/circle plus discrepancies

### ISSUE THREAD

**Issue by dasveloper** [tabler/tabler-icons#822]
There are some discrepancies between circle-plus and square-plus variants that I would love to see normalized.

`circle-plus` is a circle with a plus in the center, `square-plus` is a square with a plus in the bottom right. `square-plus-rounded` is a square with the plus in the bottom right,  `square-plus-rounded-filled` has the plus back in the center. It appears release 2.31.0 was when the bottom-right variants were introduced. 

I think it would be preferably if both variants were supported but under different namespaces (like `square-plus` and `square-plus-centered` or something), but it would at least be nice to have them all the same.

**Comment by juliuspopa** [comment]
The circle with a plus sign in the middle glyph is missing from the .ttf

The website says that `circle-plus`- the circle with a plus in the middle should have the `ea69` hex value. However, this value renders the circle with the plus sign in the bottom right. Browsing through all the glyphs of the .ttf and not able to find the circle with a plus sign in the middle.

**Comment by codecalm** [comment]
fixed in https://github.com/tabler/tabler-icons/releases/tag/v2.35.0 🙂 

![tabler-icons-2 35 0@2x](https://github.com/tabler/tabler-icons/assets/1282324/cbef91f1-07a1-437e-aa9c-84e6e9b2fe34)
