### ISSUE TITLE
Multiple Files Icon

### ISSUE THREAD

**Issue by Chaphasilor** [tabler/tabler-icons#83]
I have a button that will download multiple files. I designed some icons myself but I'm currently switching to Tabler because they simply look much better.

Anyway, here's what I'm looking for:  

<img src="https://user-images.githubusercontent.com/18015147/95349932-e47b6580-08bf-11eb-953c-d12eb833a0af.png" width="50"/>

Could you be so kind an add something like this? :)

**Comment by codecalm** [comment]
<img width="416" alt="Screenshot 2020-10-14 at 16 07 39" src="https://user-images.githubusercontent.com/1282324/96000632-65de7500-0e37-11eb-84a8-347d709dc1f4.png">

:)

**Comment by Chaphasilor** [comment]
Thanks a ton! :D
