### ISSUE TITLE
IconCodeAsterix typo

### ISSUE THREAD

**Issue by piotrkulpinski** [tabler/tabler-icons#839]
Hi, 

Just a minor issue I've found. There's a typo in the `IconCodeAsterix` name. It should be `IconCodeAsterisk` if I'm not mistaken. 
Not sure about the backward compatibility but may be easy fix in the next major release.

Thanks

**Comment by Narcha** [comment]
Nice catch. I went ahead and opened a PR for it (#856)

**Comment by BG-Software-BG** [comment]
Thanks for reporting this @piotrkulpinski . Will be fixed in v3.

**Comment by BG-Software-BG** [comment]
Typo fixed: https://tabler.io/icons/icon/code-asterisk
