### ISSUE TITLE
Hidden path in all icons

### ISSUE THREAD

**Issue by scorredoira** [tabler/tabler-icons#84]
Hi, 

is this path in every icon some kind of watermark?

` <path stroke="none" d="M0 0h24v24H0z" fill="none"/>`

I love how minimalistic the icons are, so, is there any problem removing it?

**Comment by codecalm** [comment]
Hi! It fixes the icons where are importing in Sketch, Figma, Illustrator, etc. If you use icons as svg icon you can remove it :) 

check this issue: https://github.com/tabler/tabler-icons/issues/4

**Comment by scorredoira** [comment]
OK, thank you!
