### ISSUE TITLE
How to use icon in Nuxt JS?

### ISSUE THREAD

**Issue by joewilson27** [tabler/tabler-icons#840]
Hi, I'm new to this awesome library. I can use them in vue perfectly, but when I use NuxtJS, it doesn't work...
I have installed tabler/core and tabler/icons and put that on nuxt config, but still didn't work...
Can you guys give an simple example?

**Comment by roiLeo** [comment]
Hello it does work for me https://stackblitz.com/edit/nuxt-starter-xhys4j?file=app.vue

which version of Nuxt are you using? did you install `@tabler/icons-vue` package?

**Comment by joewilson27** [comment]
Hi, thanks for answer..

I'm using nuxt version ^2.15.8

I have tried just just like your example, import the icon in vue component but it was error...
should I upgrade my nuxt to version 3.x.x ?

**Comment by joewilson27** [comment]
this is my package json
<img width="821" alt="Screenshot 2023-09-18 at 23 32 13" src="https://github.com/tabler/tabler-icons/assets/32589650/b71d400d-4e19-42d2-8395-24e39bbaa69e">


this is my define component
<img width="555" alt="Screenshot 2023-09-18 at 23 34 41" src="https://github.com/tabler/tabler-icons/assets/32589650/88d07a2f-939d-46d8-9f95-92b56a3bb22a">

and then I call them in the same file component as declare the HomeIcon above
<img width="491" alt="Screenshot 2023-09-18 at 23 36 15" src="https://github.com/tabler/tabler-icons/assets/32589650/45a6fbd7-7c14-44ef-ad73-d48b9a231fa7">


Then this is error what I got
<img width="1432" alt="Screenshot 2023-09-18 at 23 34 02" src="https://github.com/tabler/tabler-icons/assets/32589650/5409c3aa-f814-4351-8a9a-fc4601705119">

**Comment by roiLeo** [comment]
Looks like this package only work with Vue3, consider using new nuxt version

**Comment by joewilson27** [comment]
thanks @roiLeo 

it seems the issue was clear, it's about the version compatibility..

thanks
