### ISSUE TITLE
[IconRequest] Brand Auth0

### ISSUE THREAD

**Issue by piotrkulpinski** [tabler/tabler-icons#846]
I would love to have the Auth0 brand included in the library to use for social login using Auth0.
<img width="34" alt="CleanShot 2023-09-22 at 21 57 45" src="https://github.com/tabler/tabler-icons/assets/358412/396766ad-92d5-402c-a006-14130b806a63">

Thanks!

**Comment by codecalm** [comment]
added in https://github.com/tabler/tabler-icons/releases/tag/v2.37.0 🙂
