### ISSUE TITLE
Missing Stripe icon

### ISSUE THREAD

**Issue by DanielGibbsNZ** [tabler/tabler-icons#85]
The Stripe icon is shown on the icons page in the latest version of Tabler (https://preview-dev.tabler.io/icons.html) but doesn't seem to be included in this package. Would it be possible to add it?

**Comment by codecalm** [comment]
there is icon from https://simpleicons.org, but i'll add Stripe icon to tabler icons :)

**Comment by FreexD** [comment]
https://tabler-icons.io/i/brand-stripe
