### ISSUE TITLE
brand-google filled

### ISSUE THREAD

**Issue by RiceCrisp** [tabler/tabler-icons#859]
The google brand "G" does not look like the brand by default. Maybe add a filled version that doesn't rely on the stroke-width to be recognizable?

**Comment by codecalm** [comment]
added and fixed in https://github.com/tabler/tabler-icons/releases/tag/v2.40.0

<img src="https://github.com/tabler/tabler-icons/assets/1282324/527a23b9-2cae-4fd0-be5c-5ca7122fc9c4" width="584" alt="" />
