### ISSUE TITLE
Sprite approach - how can be configured directly?

### ISSUE THREAD

**Issue by Kcko** [tabler/tabler-icons#86]
```
<svg width="24" height="24">
  <use xlink:href="path/to/tabler-sprite.svg#tabler-activity" />
</svg>
```

Can be configured directly within this code? (Stroke, color ...) or how can i do that?
Btw great work!

**Comment by codecalm** [comment]
Hi @Kcko, you should use `tabler-sprite-nostroke.svg` if you can manipulate of stroke :)

**Comment by Kcko** [comment]
Hi @codecalm,
I meant it differently.  WHen i use first approach - inline html , I can easily influence the settings (width, height, stroke, color etc ...)

How can i do that with svg sprite? I dont see full usage in example.

Thx.
