### ISSUE TITLE
Rename discount variants --> rosette variants

### ISSUE THREAD

**Issue by mauriciabad** [tabler/tabler-icons#861]
Some `discount` icons are actually `rosette` icons. 

Moreover, I suggest adding some tags like: `wavy`, `curved` and `wiggly`.

And the collection would be `Shapes`, not `E-commerce`.

![](https://github.com/tabler/tabler-icons/assets/12821361/c01f2981-fbdb-4135-b7b8-5c992d3e4435)

**Comment by BG-Software-BG** [comment]
Thanks for the suggestion. Will be fixed in v3.

**Comment by BG-Software-BG** [comment]
Icons renamed in v3

![image](https://github.com/tabler/tabler-icons/assets/73077398/6aa9209a-e747-407b-8579-a4f9c91ac913)
