### ISSUE TITLE
Physiotherapist icon

### ISSUE THREAD

**Issue by aszwaj** [tabler/tabler-icons#88]
Could you create icon similar to icons "run", "bike" which presents physiotherapist?

Proposition:
![physiotherapist](https://user-images.githubusercontent.com/6988085/97034338-0d108a00-1565-11eb-9696-62eeb558cdcc.jpg)

**Comment by eladeyal-intel** [comment]
#2 🙂

**Comment by codecalm** [comment]
done, will be added in next release :)

**Comment by aszwaj** [comment]
#4 looks best for me. #3&#5 are also fine.
#2 brings into my mind rather massage :)
#1 - I really don't know ;)

pt., 23 paź 2020, 20:45 użytkownik Paweł Kuna <notifications@github.com>
napisał:

**Comment by codecalm** [comment]
@aszwaj I'll also add other icons :)

**Comment by aszwaj** [comment]
@codecalm : what name this icon has been released under?
