### ISSUE TITLE
Two more icons ;)

### ISSUE THREAD

**Issue by FilipeNas** [tabler/tabler-icons#884]
JFrog Platform (Artifactory)
Splunk

**Comment by gorobey** [comment]
add printables and thingiverse !

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.40.0 🙂 

<img src="https://github.com/tabler/tabler-icons/assets/1282324/527a23b9-2cae-4fd0-be5c-5ca7122fc9c4" width="584" alt="" />

**Comment by FilipeNas** [comment]
@codecalm did you add the jfrog and splunk logos?
