### ISSUE TITLE
hand-rock is actually "love-you" 🤟🏼 and sign-of-the-horns 🤘🏽 is missing

### ISSUE THREAD

**Issue by naughton** [tabler/tabler-icons#885]
the gesture for "rock on dude" is the sign of the horns, with the thumb crossed over the two middle fingers (🤘🏽)

the current icon called "[hand-rock](https://github.com/tabler/tabler-icons/blob/master/icons/hand-rock.svg)" (🤟🏼) is the ASL sign for "love you".

**Comment by BG-Software-BG** [comment]
Thanks for reporting this. Will be fixed in v3.

**Comment by BG-Software-BG** [comment]
hand-rock icon was renamed to [hand-love-you](https://tabler.io/icons/icon/hand-love-you).

New issue opened for [hand sign of the horns](https://github.com/tabler/tabler-icons/issues/1034).
