### ISSUE TITLE
Stack position icons.

### ISSUE THREAD

**Issue by rickghome** [tabler/tabler-icons#889]
Thanks again for this amazing library!  I'm wondering if you would consider adding a four-icon set for "stack ordering". This is used in drawing and layout apps, and typically contains a "back", "below", "above", and "front" icons. Here's an example taken from the keynote slide presentation app.

<img width="260" alt="Screenshot 2023-10-24 at 11 56 11 AM" src="https://github.com/tabler/tabler-icons/assets/869874/567b9370-0a1f-4914-9bb4-a5d821553e45">

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v2.40.0 🙂 

<img src="https://github.com/tabler/tabler-icons/assets/1282324/527a23b9-2cae-4fd0-be5c-5ca7122fc9c4" width="584" alt="" />
