### ISSUE TITLE
Request: .ti-brand-etsy

### ISSUE THREAD

**Issue by moerphie** [tabler/tabler-icons#90]
Could you please add an icon for Etsy shops?

![1280px-Etsy_logo svg](https://user-images.githubusercontent.com/12500071/97704192-3aec5600-1ab2-11eb-8fcc-89f1734fc635.png)
![download](https://user-images.githubusercontent.com/12500071/97704194-3c1d8300-1ab2-11eb-9ed9-d2f392a0a134.png)

**Comment by codecalm** [comment]
https://tabler-icons.io/i/brand-etsy
