### ISSUE TITLE
SVGs with no stoke weight

### ISSUE THREAD

**Issue by snapey** [tabler/tabler-icons#91]
Would it be possible to produce a folder of svgs with no stroke value?

I created a component for Laravel that allows the developer to control the stroke weight.  This works when using the nostroke sprite file but means the browser has to download the 300K+ file.

https://talltips.novate.co.uk/laravel/tabler-icons-component

**Comment by FreexD** [comment]
Hi @snapey! Did you mean the `stroke-width` property? For now, `tabler-icons` do not support that! 

What you can do is try to transform svg icons from `icons` directory to strip that property of them by yourself in your project, or you can try to import a single icon into your component and override it's `stroke-width` using appropriate CSS rules :)

**Comment by snapey** [comment]
There is a version of the sprite file that has no stroke width `stroke="none"` leaving it to be specified instead of being fixed at 2px. In the linked post, I created a general purpose component that can be used to insert any icon.   The only downside with this approach is needing to send the 300K+ file to the client.

**Comment by codecalm** [comment]
This is the idea of sprite files, you load icons with one request, but unfortunately you also download icons that you do not use.

**Comment by FreexD** [comment]
You can easily override icons stroke width from outside SVG using CSS - https://codepen.io/freexd/pen/wvWXbJW.
