### ISSUE TITLE
[Icon request] Caret-Up-Down like styled like chevron-up/down

### ISSUE THREAD

**Issue by fecony** [tabler/tabler-icons#914]
Basically chevron-up-down but without central part
<img width="188" alt="Screenshot 2023-11-22 at 20 46 30" src="https://github.com/tabler/tabler-icons/assets/36774784/29237f1e-9619-43a0-9014-2c0a5c751f52">
<img width="486" alt="Screenshot 2023-11-22 at 20 46 09" src="https://github.com/tabler/tabler-icons/assets/36774784/a4294849-69f4-4972-a66e-0379d828fa5e">
<img width="476" alt="Screenshot 2023-11-22 at 20 46 16" src="https://github.com/tabler/tabler-icons/assets/36774784/8c629484-8289-4892-b534-5e8f92834963">

**Comment by noahstuesser** [comment]
There's a IconSelector but the chevrons of it could be smaller but I am not sure.

**Comment by fecony** [comment]
> There's a IconSelector but the chevrons of it could be smaller but I am not sure.

![Screenshot 2023-11-28 at 12 12 29](https://github.com/tabler/tabler-icons/assets/36774784/10ded682-c71f-4440-a423-60846a27ee8d)

oh you are right, didnt even find it 😄

**Comment by noahstuesser** [comment]
Maybe a rename to chevron-up-down would be helpful and easier to find.
