### ISSUE TITLE
Search results are off

### ISSUE THREAD

**Issue by hornta** [tabler/tabler-icons#916]
It seems like the search results are a bit off. It seems like if any of the typed characters appear somewhere in the icon name or icon tag, then its a match. I believe it makes it more difficult to find what I'm looking for.

![image](https://github.com/tabler/tabler-icons/assets/4553604/3719f7ed-a3ef-442b-aed5-ebf9fcb412b7)

**Comment by BG-Software-BG** [comment]
https://www.fusejs.io/ is used for search

**Comment by activenode** [comment]
Hm. Even though fuzzy search is a good approach I think in the case of icons a rather hard match is more useful or at least the option to toggle fuzzy off on.

**Comment by BG-Software-BG** [comment]
@hornta - search was improved. Hope it'll be easier to find icons.

**Comment by YazeedAlKhalaf** [comment]
@BG-Software-BG 
We are trying to makea. tabler icons search, what search way do you use with fuse?

Is it open sourced somewhere or private?

**Comment by BG-Software-BG** [comment]
@YazeedAlKhalaf 

Project for https://tabler.io/icons is private.
