### ISSUE TITLE
[Icon request] broom 

### ISSUE THREAD

**Issue by mla-v-office** [tabler/tabler-icons#926]
https://www.svgrepo.com/svg/490586/broom
https://www.svgrepo.com/svg/490030/broom

Could the broom icons please be added?

**Comment by katywings** [comment]
Bump 😅

**Comment by Streusel** [comment]
I too would like this broom. I don't understand why a grill spatula exists and a broom doesn't.

**Comment by bessone** [comment]
The Broom can be useful for "clear" or "reset", for example in filter/search forms.
