### ISSUE TITLE
[Icon request] EA FC

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#933]
EA FC is the rebranded title of FIFA, a popular football / soccer game and has grown massively in popularity, it'd be great if we can get an icon on tabler.

![image](https://github.com/tabler/tabler-icons/assets/33750251/3e83a6e0-fbd5-4c07-8466-e31a1ba0c242)

**Comment by BG-Software-BG** [comment]
There are no plans to add icons for video games
