### ISSUE TITLE
[Icon request] GTA 6

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#934]
GTA 6 has been announced recently, it'd be great if we can icon on tabler for it

Concept that I found really interesting:
![image](https://github.com/tabler/tabler-icons/assets/33750251/9916a020-9057-4759-9412-101a1ec8aad2)

The official logo:
![image](https://github.com/tabler/tabler-icons/assets/33750251/eeebc76e-285b-4a25-865c-73055a044340)

**Comment by BG-Software-BG** [comment]
There are no plans to add icons for video games
