### ISSUE TITLE
Error on Svelte 5

### ISSUE THREAD

**Issue by h1sashin** [tabler/tabler-icons#935]
I keep getting this error using Tabler icons

```bash
SyntaxError: Named export 'SvelteComponent' not found. The requested module '../../../node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

I don't know what more I can say about the issue. 
`@tabler/icons-svelte` version is `2.44.0`

**Comment by BG-Software-BG** [comment]
@h1sashin is this still an issue in the newest versions of @tabler/icons-svelte?

**Comment by h1sashin** [comment]
> @h1sashin is this still an issue in the newest versions of @tabler/icons-svelte?

Didn't get that error so I assume it's already fixed
