### ISSUE TITLE
[Icon Request] tag-filled

### ISSUE THREAD

**Issue by eai04191** [tabler/tabler-icons#937]
As the name suggests, it is just a filled tag.

I created an svg and previewed it. If there is no problem, please leave a comment and I will create a PR.
(or feel free to modify/use and add to your release. I'm not sure how to contribute as there is no guide to adding new icons.)

```svg
<path d="M2 6c0-2.194 1.806-4 4-4h5.172c.795 0 1.559.317 2.121.879l7.71 7.71a3.425 3.425 0 0 1 0 4.822l-5.592 5.592a3.425 3.425 0 0 1-4.822 0l-7.71-7.71A3.002 3.002 0 0 1 2 11.172V6Zm3.5 1.5c0 1.097.903 2 2 2s2-.903 2-2-.903-2-2-2-2 .903-2 2Z" fill="currentColor" stroke-width="0" />

```

![preview](https://github.com/tabler/tabler-icons/assets/3516343/ac60a090-dfe4-4a4c-87ba-886630e61ab0)

**Comment by BG-Software-BG** [comment]
Filled version of [tag icon](https://tabler.io/icons/icon/tag) was added in v3.6.
