### ISSUE TITLE
[Icon Request] Silent

### ISSUE THREAD

**Issue by schieska** [tabler/tabler-icons#943]
I would like to have a shush icon. something to signefy a silent mode.

**Comment by BG-Software-BG** [comment]
Maybe you can use https://tabler.io/icons/icon/volume-off?

**Comment by schieska** [comment]
Not ideal, I would like something that signefies that we turned our divice in silent operation mode, the noise it produces is not by a speaker

**Comment by BG-Software-BG** [comment]
Can you give some example?
