### ISSUE TITLE
Brand Icon Request

### ISSUE THREAD

**Issue by zacharymctague** [tabler/tabler-icons#95]
Love your work! Would be great to see the [Linktree](https://linktr.ee/) logo here.

<img width="185" alt="Screen Shot 2020-11-20 at 8 55 48 AM" src="https://user-images.githubusercontent.com/12935065/99734270-3abe0400-2b0e-11eb-8ad7-fc7d4f4a7634.png">

**Comment by beeznutzdev** [comment]
Yes, I agree. 👀

**Comment by codecalm** [comment]
https://tabler-icons.io/i/brand-linktree :)
