### ISSUE TITLE
IconSquarexFilled instead of IconSquareXFilled on the website

### ISSUE THREAD

**Issue by mikouaji** [tabler/tabler-icons#953]
Hi,
just found that there is a typo [here](https://tabler.io/icons/icon/square-x-filled), it says `IconSquarexFilled` instead of `IconSquareXFilled` in the React and Vue tabs. Copying the import statement causes an error.

I would add a PR with a fix but either there is no source for the website to make changes in or I just cannot find it.

**Comment by codecalm** [comment]
fixed! thank you 🙂
