### ISSUE TITLE
Astro: The icons brand-x and brand-x-filled not working

### ISSUE THREAD

**Issue by naujrevilo** [tabler/tabler-icons#955]
Astro 4. When using the tabler icons it does not recognize "brand-x" and "brand-x-filled". Attached is an image of the error.
It should be noted that the other icons have worked well.
![brand-x error](https://github.com/tabler/tabler-icons/assets/14898430/ab96ae49-bbc7-4cf1-a3ee-5e79b5bf7fb7)

![image](https://github.com/tabler/tabler-icons/assets/14898430/ed3a3091-c1f3-486d-b490-ed0a3437e717)

**Comment by BG-Software-BG** [comment]
@naujrevilo is this still an issue? Which version of the package are you using?

**Comment by naujrevilo** [comment]
Oh, hello. Uh, no. I solved the problem shortly after, I think it turned out to be a package update, I don't quite remember.
