### ISSUE TITLE
add to folder and create alert icon request. 

### ISSUE THREAD

**Issue by iAlborz** [tabler/tabler-icons#96]
Could you please add these two icons:
add to folder is useful for when you want to move an item to another destination or folder. 
the other icon is used when a user wants to turn on notifications or create a custom alert. 
![EnOWcYaVoAEmB9s](https://user-images.githubusercontent.com/4399410/99826319-0f86e500-2b0d-11eb-9425-648f93712fa0.jpg)

**Comment by iAlborz** [comment]
<img width="680" alt="Screen Shot 2020-11-30 at 2 42 00 PM" src="https://user-images.githubusercontent.com/4399410/100674609-471a3c00-331a-11eb-821f-20928c000258.png">
[move to folder and create alarm.zip](https://github.com/tabler/tabler-icons/files/5619144/move.to.folder.and.create.alarm.zip)
made a quick version of them in sketch. not sure if it would help save time or not, but here they are.

**Comment by codecalm** [comment]
Added in https://github.com/tabler/tabler-icons/releases/tag/v1.37.0 :)

![tabler-icons-1 37 0](https://user-images.githubusercontent.com/1282324/101258407-9c8f8800-3722-11eb-935f-3b675b717780.png)
