### ISSUE TITLE
[Icon request] Square meter icon

### ISSUE THREAD

**Issue by codecalm** [tabler/tabler-icons#961]
### Discussed in https://github.com/tabler/tabler-icons/discussions/870

<div type='discussions-op-text'>

<sup>Originally posted by **aleyrizvi** October 14, 2023</sup>
Hello,
If you remember me, I requested onlyfans icon.

I am here again with unusual icon request :D

I would like to have a square meter icon. Idea for the icon can be seen here: https://www.google.com/search?q=square+meter+icon&sca_esv=573502981&rlz=1C5CHFA_enEE1039EE1039&tbm=isch&sxsrf=AM9HkKnzjBrO9tzxoCuiRqvXtoBLwW6CVA:1697317187192&source=lnms&sa=X&sqi=2&ved=2ahUKEwj_4I2gt_aBAxVnCBAIHWcoCuwQ_AUoAXoECAMQAw&biw=1512&bih=753&dpr=2

Thank you in advance.</div>

**Comment by BG-Software-BG** [comment]
[square meter icon](https://tabler.io/icons/icon/meter-square) added in v2.45
