### ISSUE TITLE
@tabler/icons-react is not working with vite

### ISSUE THREAD

**Issue by tejaswankalluri** [tabler/tabler-icons#963]
![image](https://github.com/tabler/tabler-icons/assets/49343044/549813f6-0677-4a28-b2d3-1a741ef5ba87)

dependency:
    "@tabler/icons": "^2.44.0",
    "@tabler/icons-react": "^2.44.0",
    "vite": "^5.0.10"

**Comment by BG-Software-BG** [comment]
Closing as https://github.com/vitejs/vite/issues/15550 is resolved and no more activity here.
