### ISSUE TITLE
[Icon Request] Brand yarn and pnpm

### ISSUE THREAD

**Issue by stone-zeng** [tabler/tabler-icons#966]
Yarn: https://github.com/yarnpkg/berry/blob/master/packages/docusaurus/static/img/yarn-favicon.svg

![image](https://github.com/tabler/tabler-icons/assets/18233088/381cdabe-866e-4fd5-857c-bff93cfb7961)

pnpm: https://github.com/pnpm/pnpm.io/blob/main/static/img/pnpm-no-name-with-frame.svg

![image](https://github.com/tabler/tabler-icons/assets/18233088/a7cfd23f-c338-4246-824b-64552c6eae11)

**Comment by BG-Software-BG** [comment]
[pnpm](https://tabler.io/icons/icon/brand-pnpm) and [yarn](https://tabler.io/icons/icon/brand-yarn) added in v2.45
