### ISSUE TITLE
Numbered (ordered) list icon

### ISSUE THREAD

**Issue by Kassaila** [tabler/tabler-icons#97]
Hi.
Nice set and good job.
Will be fine to see 'numbered (ordered) list' icon, for collection of list icons 
![tabler list icons](https://user-images.githubusercontent.com/38295556/100263351-158a2500-2f56-11eb-8529-dc47252e1be4.png).
Something like this
![github list](https://user-images.githubusercontent.com/38295556/100262967-9137a200-2f55-11eb-92ac-758d8f22aa44.png)

**Comment by codecalm** [comment]
done in https://github.com/tabler/tabler-icons/releases/tag/v1.40.0 :)

**Comment by Kassaila** [comment]
Thanks
