### ISSUE TITLE
shopping-cart-minus/cog/search not working

### ISSUE THREAD

**Issue by vFurky** [tabler/tabler-icons#982]
Hello. Firstly, im sorry for my bad English. 
I try usage tabler icons on my Vuexy admin template. shopping-cart-plus is working but minus, cog or search is not working. Or, shopping-cart-plus is working but doesn't look the same as the icon in tabler.io.
Is it Vuexy or is there a problem? I can also take a picture if you want. Thanks!

**Comment by BG-Software-BG** [comment]
Please, provide an example - code and screenshots.

**Comment by vFurky** [comment]
![image](https://github.com/tabler/tabler-icons/assets/89664220/d4dd5414-d306-4d61-8118-cad275279e21)
![image](https://github.com/tabler/tabler-icons/assets/89664220/9fed6ca5-492c-452f-b577-628428c1ec35)
The codes look like the first picture, and the project looks like the second picture. So it doesn't work properly.

**Comment by vFurky** [comment]
Hello, anybody is here?

**Comment by codecalm** [comment]
@vFurky we are working on it 🙂
