### ISSUE TITLE
Typo on sort-deacending-small-big

### ISSUE THREAD

**Issue by agil3st** [tabler/tabler-icons#983]
`sort-deacending-small-big` should be changed to `sort-descending-small-big`
Not a big deal. Please fix when you ready.

**Comment by vikasviks** [comment]
Hi @agil3st 
I have changed the sort-deacending-small-big to sort-descending-small-big.
Please review and merge.
thanks

**Comment by BG-Software-BG** [comment]
Thanks for catching this. Will be fixed in v3.
