### ISSUE TITLE
icons match-max and math-min are constant source of distraction

### ISSUE THREAD

**Issue by rpbouman** [tabler/tabler-icons#992]
Not sure if I'm doing the right thing but it has come up a couple of times already and I think it might be useful to put it on the table here.

In my app I have a bunch of statistical/mathematical function and I use the tabler icons to represent them. I love the icon library and it has really helped me, so thanks for that!

There is one thing that keeps coming back though. Whenever I do a live demo, a lot of the time, audience gets distracted. A growing sample of the people I demo it to think the min and max icons "look like boobs". 

Are others experiencing this? Do you have suggestions for alternative tabler-icons to represent minimum and maximum (in the context of statistical metrics)? Thanks in advance.

![image](https://github.com/tabler/tabler-icons/assets/647315/bb5316d5-2ab6-4e6d-970d-d4db20aa4136)

**Comment by BG-Software-BG** [comment]
Both icons are fixed already!

[math-min icon](https://tabler.io/icons/icon/math-min)   
[math-max icon](https://tabler.io/icons/icon/math-max)   

... and [math-max-min icon](https://tabler.io/icons/icon/math-max-min) was added in v2.47 today :)
